LPS-184639, LPS-184640, LPS-190570 Add a new table to map each folder id with its Permission Template settings
liferay-content-management/liferay-portal pull request #4997
Opened 2023-12-11 09:12 UTC by tototrinh

Hi team,
Please help review this PR and give your feedback.
cc: @locpham97 @ces-quanhuynh @ces-luannguyen
Previous PR: https://github.com/brianchandotcom/liferay-portal/pull/142550
# Motivation
[LPS-184639](https://liferay.atlassian.net/browse/LPS-184639) _Add a new table to map each folder id with its propagation settings_
[LPS-184640](https://liferay.atlassian.net/browse/LPS-184640) _Update the checkbox value to the database when creating new Folder_
[LPS-190570](https://liferay.atlassian.net/browse/LPS-190570) _Make it work with publications_
These tickets are subtasks of [LPS-154515](https://liferay.atlassian.net/browse/LPS-154515) _As a documents manager I want to set permissions from folders to folders at creation time_
Each folder will have a permissions propagation setting, and its value will affect how the permissions of newly created subfolders are determined
# Solution
- In a new module `permission-template`, creating a new entity `PermissionTemplate to map each _folderId_ with its permission template settings with these columns - `companyId`, `groupId`, `classNameId`, `classPK`, and `permissionTemplateEnabled`. 
`classNameId` identifies the kind of thing (see ClassNameLocalService) and `classPK` would be its primkey (e.g. folderId, ...).

- Publication: Enable change-tracking-enabled to true for `PermissionTemplate` and create two new classes to integrate Liferay Publication Framework - `PermissionTemplateCTDisplayRenderer` and `PermissionTemplateTableReferenceDefinition`
Regards,

2023-12-11 09:12 UTC, liferay-continuous-integration commented
CI is automatically triggering the following test suites:
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**sf**

2023-12-11 09:16 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-9.liferay.com/job/test-portal-source-format/4881/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-9.liferay.com/userContent/jobs/test-portal-source-format/builds/4881/jenkins-report.html">here</a>.</b></p>

2023-12-11 09:19 UTC, liferay-continuous-integration commented
<html><h3>:heavy_check_mark: ci:test:sf - 1 out of 1 jobs passed in 4 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/f781bbbd4519d89107ce7a55cbf0bbbfb2ff3703">f781bbbd4519d89107ce7a55cbf0bbbfb2ff3703</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/tototrinh/liferay-portal/tree/LPS-154515-refactor">LPS-154515-refactor</a><br/>Branch GIT ID: <a href="https://github.com/tototrinh/liferay-portal/commit/7b657c6f8a45a63bc23105a59d3d88e5bab4937d">7b657c6f8a45a63bc23105a59d3d88e5bab4937d</a></p>1 out of 1jobs PASSED<details><summary><strong>1 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-9.liferay.com/job/test-portal-source-format/4881/">test-portal-source-format</a></li></ul></details><h5>For more details click <a href="https://test-1-9.liferay.com/userContent/jobs/test-portal-source-format/builds/4881/jenkins-report.html">here</a>.</h5></details></html>

2023-12-11 09:23 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-9.liferay.com/job/test-portal-source-format/4881/">test-portal-source-format#4881</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-9.liferay.com/userContent/jobs/test-portal-source-format/builds/4881/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-lima/liferay-portal/pull/4997">liferay-lima#4997</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=2472865320">[master] ci:test:sf - tototrinh &gt; liferay-lima - PR#4997 - 2023-12-11[01:15:17]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-9.liferay.com/job/publish-testray-report/5615/">publish-testray-report#5615</a><br/></div></div>

2023-12-12 15:22 UTC, marcogalluzzi requested changes
Nice work! 

BTW, I think that the new module should be added in file _module.properties_

2023-12-12 15:22 UTC, marcogalluzzi commented on modules/apps/permission-template/permission-template-service/src/main/java/com/liferay/permission/template/service/impl/PermissionTemplateLocalServiceImpl.java
> +		PermissionTemplate permissionTemplate = fetchPermissionTemplate(
Only one `PermissionTemplate` can exist with the key `(className, classPK)`? Or is it possible to have different ones depending on the `companyId` or `groupId`?

2023-12-14 12:43 UTC, tototrinh commented
Hi @marcogalluzzi, thanks for your comment, I updated the PR, please help take a look. Thanks.

2023-12-14 12:45 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-34.liferay.com/job/test-portal-source-format/3049/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-34.liferay.com/userContent/jobs/test-portal-source-format/builds/3049/jenkins-report.html">here</a>.</b></p>

2023-12-14 12:46 UTC, liferay-continuous-integration commented
<html><h3>:heavy_check_mark: ci:test:sf - 1 out of 1 jobs passed in 3 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/6af76e46fccdeab086dc5da2bd0f08cbddbfa39a">6af76e46fccdeab086dc5da2bd0f08cbddbfa39a</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/tototrinh/liferay-portal/tree/LPS-154515-refactor">LPS-154515-refactor</a><br/>Branch GIT ID: <a href="https://github.com/tototrinh/liferay-portal/commit/725eb714f48092e28bfc8f0a645cbee2f9497877">725eb714f48092e28bfc8f0a645cbee2f9497877</a></p>1 out of 1jobs PASSED<details><summary><strong>1 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-34.liferay.com/job/test-portal-source-format/3049/">test-portal-source-format</a></li></ul></details><h5>For more details click <a href="https://test-1-34.liferay.com/userContent/jobs/test-portal-source-format/builds/3049/jenkins-report.html">here</a>.</h5></details></html>

2023-12-14 12:49 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-34.liferay.com/job/test-portal-source-format/3049/">test-portal-source-format#3049</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-34.liferay.com/userContent/jobs/test-portal-source-format/builds/3049/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-lima/liferay-portal/pull/4997">liferay-lima#4997</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=2474480474">[master] ci:test:sf - tototrinh &gt; liferay-lima - PR#4997 - 2023-12-14[04:43:36]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-34.liferay.com/job/publish-testray-report/22259/">publish-testray-report#22259</a><br/></div></div>

2023-12-15 08:45 UTC, marcogalluzzi approved these changes

2023-12-18 12:11 UTC, adolfopa commented
This may take some time to review and to move it forward. Putting it on hold.

2025-04-12 13:07 UTC, jkappler commented
@adolfopa, it's been quite a long time, so I'm closing this for now until we get back to it

2025-04-12 13:07 UTC, closed without merging