LPD-26755 The URL redirects to the correct language when a category has a translation
liferay-content-management/liferay-portal pull request #5573
Opened 2024-06-14 13:00 UTC by boton

# What is this trying to solve?

https://liferay.atlassian.net/browse/LPD-26755

We are adding a playwright test to check friendly URL redirection to the correct language when a category has a translation

# How am I fixing it?

We are adding a functional test.

# How can you verify that it works?

1. Go to `/modules/test/playwright`
3. Run `npm install` (setup)
4. Run `npm run playwright test -- -g "LPD-26755"` to run the test

# Local test results

## Blogs-web

```sh
npm run playwright test -- --project blogs-web --reporter list
```

![image](https://github.com/liferay-content-management/liferay-portal/assets/67901/41812521-f572-4d6a-94dd-df0989898089)

## Repeat the test

```sh
npm run playwright test -- -g "LPD-26755" --reporter list --repeat-each 10
```

![image](https://github.com/liferay-content-management/liferay-portal/assets/67901/74f823b7-e213-4100-9335-4c453c292f77)

> [!IMPORTANT]  
> Unrelated fail in login

# Screenrecord test execution

[blogEntry-LPD-26755-The-URL-redirects-to-the-correct-language-when-a-category-has-a-translation-blogs-web.webm](https://github.com/liferay-content-management/liferay-portal/assets/67901/5fb43663-2784-4567-8862-2189ab4e0bc6)

# UI Screenshot with visible URL
![image](https://github.com/liferay-content-management/liferay-portal/assets/67901/4a27520d-64dd-4e92-82a3-bad7fb241dd5)

2024-06-14 13:00 UTC, liferay-continuous-integration commented
CI is automatically triggering the following test suites:
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**sf**

2024-06-14 13:00 UTC, boton commented
ci:test:playwright

2024-06-14 13:01 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-38.liferay.com/job/test-portal-source-format/5717/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-38.liferay.com/userContent/jobs/test-portal-source-format/builds/5717/jenkins-report.html">here</a>.</b></p>

2024-06-14 13:03 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>playwright</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-36.liferay.com/job/test-portal-acceptance-pullrequest(master)/6285/">test-portal-acceptance-pullrequest(master)</a></p><p><b>For more details click <a href="https://test-1-36.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/6285/jenkins-report.html">here</a>.</b></p>

2024-06-14 13:05 UTC, liferay-continuous-integration commented
<html><h3>:x: ci:test:sf - 0 out of 1 jobs passed in 4 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/02584af42556ad3fb7436c423bab63d6d45ea3f1">02584af42556ad3fb7436c423bab63d6d45ea3f1</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/boton/liferay-portal/tree/LPD-26755-TEST-Blogs-friendlyURL-translated-categories">LPD-26755-TEST-Blogs-friendlyURL-translated-categories</a><br/>Branch GIT ID: <a href="https://github.com/boton/liferay-portal/commit/494d750757772530e1ac6b28111ca3150d54c459">494d750757772530e1ac6b28111ca3150d54c459</a></p>0 out of 1jobs PASSED<div><h4>1 Failed Jobs:</h4><ul><li><a href="https://test-1-38.liferay.com/job/test-portal-source-format/5717/"><strike>test-portal-source-format</strike></a></li></ul></div><h5>For more details click <a href="https://test-1-38.liferay.com/userContent/jobs/test-portal-source-format/builds/5717/jenkins-report.html">here</a>.</h5><pre>     [exec] npm WARN deprecated babel-eslint@10.1.0: babel-eslint is now @babel/eslint-parser. This package will no longer receive updates.
     [exec] 
     [exec] added 387 packages, and audited 388 packages in 3s
     [exec] 
     [exec] 111 packages are looking for funding
     [exec]   run `npm fund` for details
     [exec] 
     [exec] 1 high severity vulnerability
     [exec] 
     [exec] To address all issues, run:
     [exec]   npm audit fix
     [exec] 
     [exec] Run `npm audit` for details.
     [exec] 
     [exec] &gt; Task :packageRunCheckFormat
     [exec] npm WARN config production Use `--omit=dev` instead.
     [exec] 
     [exec] &gt; @liferay/playwright@1.0.0 checkFormat
     [exec] &gt; tsc &amp;&amp; node scripts.mjs checkFormat
     [exec] 
     [exec] tests/workspaces/liferay-workspace-marketplace/marketplaceCustomerDashboard.spec.ts(73,38): error TS2551: Property 'assingUserToAccountRole' does not exist on type 'HeadlessAdminUserApiHelper'. Did you mean 'assignUserToAccountRole'?
     [exec] 
     [exec] &gt; Task :packageRunCheckFormat FAILED
     [exec] 
     [exec] 
     [exec] FAILURE: Build failed with an exception.
     [exec] 
     [exec] * What went wrong:
     [exec] Execution failed for task ':packageRunCheckFormat'.
     [exec] &gt; Process 'command '/opt/dev/projects/github/liferay-portal/modules/test/playwright/build/node/bin/node'' finished with non-zero exit value 2
     [exec] Gradle build finished at 2024-06-14 13:04:34.792.
     [exec] 3 actionable tasks: 3 executed
     [exec] 
     [exec] 
     [exec] * Try:
     [exec] &gt; Run with --info or --debug option to get more log output.
     [exec] &gt; Run with --scan to get full insights.
     [exec] See the profiling report at: file:///opt/dev/projects/github/liferay-portal/modules/test/playwright/build/reports/profile/profile-2024-06-14-06-04-10.html&gt; Get more help at https://help.gradle.org.
     [exec] 
     [exec] 
     [exec] * Exception is:
     [exec] A fine-grained performance profile is available: use the --scan option.
     [exec] org.gradle.api.tasks.TaskExecutionException: Execution failed for task ':packageRunCheckFormat'.
     [exec]   at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.lambda\$executeIfValid\$1(ExecuteActionsTaskExecuter.java:148)
     [exec]   at org.gradle.internal.Try\$Failure.ifSuccessfulOrElse(Try.java:282)
     [exec]   at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeIfValid(ExecuteActionsTaskExecuter.java:146)</pre></details></html>

2024-06-14 13:07 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-38.liferay.com/job/test-portal-source-format/5717/">test-portal-source-format#5717</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-38.liferay.com/userContent/jobs/test-portal-source-format/builds/5717/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-content-management/liferay-portal/pull/5573">liferay-content-management#5573</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/#/project/34754/routines/34756">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/#/project/34754/routines/34756/build/17739526">[master] ci:test:sf - boton &gt; liferay-content-management - PR#5573 - 2024-06-14[06:00:44]</a><br/></div><div><strong>Testray Build ID:</strong><span></span>17739526<br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-38.liferay.com/job/publish-testray-report/22284/">publish-testray-report#22284</a><br/></div></div>

2024-06-14 13:15 UTC, boton commented
It's an external error. 
I've added a typo fix but I rollback I prefer to test with more time

2024-06-14 14:38 UTC, liferay-continuous-integration commented
<html><h3>:x: ci:test:playwright - 24 out of 35 jobs passed in 1 hour 34 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/02584af42556ad3fb7436c423bab63d6d45ea3f1">02584af42556ad3fb7436c423bab63d6d45ea3f1</a></p><h4>Upstream Comparison:</h4><p>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/2784e13c30d2623314f0a38b11510b5461b80826">2784e13c30d2623314f0a38b11510b5461b80826</a><br/>Jenkins Build URL: <a href="https://testray.liferay.com/#/project/34754/routines/174485/build/17500075">EE Development Acceptance (master) - 597 - 2024-06-13[16:39:33]</a></p><details><summary><strong>ci:test:playwright - 24 out of 35 jobs PASSED</strong></summary><div><h4>11 Failed Jobs:</h4><ul><li><a href="https://test-1-36.liferay.com/job/test-portal-acceptance-pullrequest(master)/6285/"><strike>test-portal-acceptance-pullrequest(master)</strike></a></li><li>playwright-compile-jdk8<ul><li><a href="https://test-1-40.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/662171/">playwright-compile-jdk8/0/0</a></li></ul></li><li>playwright-js-tomcat90-mysql57-jdk8<ul><li><a href="https://test-1-26.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1131563/">playwright-js-tomcat90-mysql57-jdk8/0/0</a></li><li><a href="https://test-1-36.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/966681/"><strike>playwright-js-tomcat90-mysql57-jdk8/1/0</strike></a></li><li><a href="https://test-1-27.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1012246/">playwright-js-tomcat90-mysql57-jdk8/2/0</a></li><li><a href="https://test-1-40.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/662177/">playwright-js-tomcat90-mysql57-jdk8/3/0</a></li><li><a href="https://test-1-37.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1131822/">playwright-js-tomcat90-mysql57-jdk8/4/0</a></li><li><a href="https://test-1-30.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/977731/"><strike>playwright-js-tomcat90-mysql57-jdk8/5/0</strike></a></li><li><a href="https://test-1-33.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/852007/">playwright-js-tomcat90-mysql57-jdk8/6/0</a></li><li><a href="https://test-1-40.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/662173/"><strike>playwright-js-tomcat90-mysql57-jdk8/7/0</strike></a></li><li><a href="https://test-1-40.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/662172/">playwright-js-tomcat90-mysql57-jdk8/8/0</a></li><li><a href="https://test-1-40.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/662175/">playwright-js-tomcat90-mysql57-jdk8/9/0</a></li><li><a href="https://test-1-33.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/852008/"><strike>playwright-js-tomcat90-mysql57-jdk8/10/0</strike></a></li><li><a href="https://test-1-30.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/977732/">playwright-js-tomcat90-mysql57-jdk8/11/0</a></li><li><a href="https://test-1-27.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1012247/">playwright-js-tomcat90-mysql57-jdk8/12/0</a></li><li><a href="https://test-1-36.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/966682/">playwright-js-tomcat90-mysql57-jdk8/13/0</a></li><li><a href="https://test-1-37.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1131824/"><strike>playwright-js-tomcat90-mysql57-jdk8/14/0</strike></a></li><li><a href="https://test-1-40.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/662178/">playwright-js-tomcat90-mysql57-jdk8/15/0</a></li><li><a href="https://test-1-30.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/977733/">playwright-js-tomcat90-mysql57-jdk8/16/0</a></li><li><a href="https://test-1-34.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/940427/">playwright-js-tomcat90-mysql57-jdk8/17/0</a></li><li><a href="https://test-1-40.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/662170/">playwright-js-tomcat90-mysql57-jdk8/18/0</a></li><li><a href="https://test-1-40.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/662169/">playwright-js-tomcat90-mysql57-jdk8/19/0</a></li><li><a href="https://test-1-40.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/662174/"><strike>playwright-js-tomcat90-mysql57-jdk8/20/0</strike></a></li><li><a href="https://test-1-36.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/966679/">playwright-js-tomcat90-mysql57-jdk8/21/0</a></li><li><a href="https://test-1-36.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/966678/">playwright-js-tomcat90-mysql57-jdk8/22/0</a></li><li><a href="https://test-1-37.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1131821/">playwright-js-tomcat90-mysql57-jdk8/23/0</a></li><li><a href="https://test-1-37.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1131820/"><strike>playwright-js-tomcat90-mysql57-jdk8/24/0</strike></a></li><li><a href="https://test-1-26.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1131562/"><strike>playwright-js-tomcat90-mysql57-jdk8/25/0</strike></a></li><li><a href="https://test-1-40.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/662176/"><strike>playwright-js-tomcat90-mysql57-jdk8/26/0</strike></a></li><li><a href="https://test-1-27.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1012245/">playwright-js-tomcat90-mysql57-jdk8/27/0</a></li><li><a href="https://test-1-30.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/977730/">playwright-js-tomcat90-mysql57-jdk8/28/0</a></li><li><a href="https://test-1-36.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/966680/">playwright-js-tomcat90-mysql57-jdk8/29/0</a></li><li><a href="https://test-1-39.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/908724/">playwright-js-tomcat90-mysql57-jdk8/30/0</a></li><li><a href="https://test-1-36.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/966745/"><strike>playwright-js-tomcat90-mysql57-jdk8/31/0</strike></a></li><li><a href="https://test-1-26.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1131564/">playwright-js-tomcat90-mysql57-jdk8/32/0</a></li></ul></li></ul></div><details><summary><strong>24 Successful Jobs:</strong></summary><ul/></details></details><h5>For more details click <a href="https://test-1-36.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/6285/jenkins-report.html">here</a>.</h5><hr/><h4>Failures unique to this pull:</h4><ol><li><div><a href="https://test-1-36.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/966681//consoleText">playwright-js-tomcat90-mysql57-jdk8/1/0</a> - <a href="https://testray.liferay.com/reports/production/logs/2024-06/test-1-36/test-portal-acceptance-pullrequest(master)/6285/playwright-js-tomcat90-mysql57-jdk8/1/0/playwright-report/index.html">Playwright Report</a><ol><li><details><summary><a href="https://test-1-36.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/966681/testReport/object-web_objectRelationships.spec/ts">object-web/objectRelationships.spec.ts</a></summary><div><ol><li><a href="https://test-1-36.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/966681//testReport/object-web_objectRelationships.spec/ts/Manage_object_relationships_through_Model_Builder___can_create_relationship_by_dragging_node_handles">Manage object relationships through Model Builder  [...]

2024-06-17 10:49 UTC, boton commented
ci:test:playwright

2024-06-17 10:49 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>playwright</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-30.liferay.com/job/test-portal-acceptance-pullrequest(master)/9395/">test-portal-acceptance-pullrequest(master)</a></p><p><b>For more details click <a href="https://test-1-30.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/9395/jenkins-report.html">here</a>.</b></p>

2024-06-17 12:20 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-38.liferay.com/job/test-portal-source-format/5719/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-38.liferay.com/userContent/jobs/test-portal-source-format/builds/5719/jenkins-report.html">here</a>.</b></p>

2024-06-17 12:24 UTC, liferay-continuous-integration commented
<html><h3>:heavy_check_mark: ci:test:sf - 1 out of 1 jobs passed in 5 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/768d84f176aaf86f2e2922f23e4c985bae9c3369">768d84f176aaf86f2e2922f23e4c985bae9c3369</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/boton/liferay-portal/tree/LPD-26755-TEST-Blogs-friendlyURL-translated-categories">LPD-26755-TEST-Blogs-friendlyURL-translated-categories</a><br/>Branch GIT ID: <a href="https://github.com/boton/liferay-portal/commit/099cce86058f00716185e49587c650d5a75582bd">099cce86058f00716185e49587c650d5a75582bd</a></p>1 out of 1jobs PASSED<details><summary><strong>1 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-38.liferay.com/job/test-portal-source-format/5719/">test-portal-source-format</a></li></ul></details><h5>For more details click <a href="https://test-1-38.liferay.com/userContent/jobs/test-portal-source-format/builds/5719/jenkins-report.html">here</a>.</h5></details></html>

2024-06-17 12:27 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-38.liferay.com/job/test-portal-source-format/5719/">test-portal-source-format#5719</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-38.liferay.com/userContent/jobs/test-portal-source-format/builds/5719/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-content-management/liferay-portal/pull/5573">liferay-content-management#5573</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/#/project/34754/routines/34756">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/#/project/34754/routines/34756/build/19008306">[master] ci:test:sf - boton &gt; liferay-content-management - PR#5573 - 2024-06-17[05:19:07]</a><br/></div><div><strong>Testray Build ID:</strong><span></span>19008306<br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-38.liferay.com/job/publish-testray-report/22304/">publish-testray-report#22304</a><br/></div></div>

2024-06-17 12:41 UTC, liferay-continuous-integration commented
<html><h3>:x: ci:test:playwright - 25 out of 35 jobs passed in 1 hour 51 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/768d84f176aaf86f2e2922f23e4c985bae9c3369">768d84f176aaf86f2e2922f23e4c985bae9c3369</a></p><h4>Upstream Comparison:</h4><p>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/768d84f176aaf86f2e2922f23e4c985bae9c3369">768d84f176aaf86f2e2922f23e4c985bae9c3369</a><br/>Jenkins Build URL: <a href="https://testray.liferay.com/#/project/34754/routines/174485/build/18909767">EE Development Acceptance (master) - 601 - 2024-06-16[20:43:59]</a></p><details><summary><strong>ci:test:playwright - 25 out of 35 jobs PASSED</strong></summary><div><h4>10 Failed Jobs:</h4><ul><li><a href="https://test-1-30.liferay.com/job/test-portal-acceptance-pullrequest(master)/9395/"><strike>test-portal-acceptance-pullrequest(master)</strike></a></li><li>playwright-compile-jdk8<ul><li><a href="https://test-1-40.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/663893/">playwright-compile-jdk8/0/0</a></li></ul></li><li>playwright-js-tomcat90-mysql57-jdk8<ul><li><a href="https://test-1-27.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1013739/">playwright-js-tomcat90-mysql57-jdk8/0/0</a></li><li><a href="https://test-1-32.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1025773/"><strike>playwright-js-tomcat90-mysql57-jdk8/1/0</strike></a></li><li><a href="https://test-1-40.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/663898/">playwright-js-tomcat90-mysql57-jdk8/2/0</a></li><li><a href="https://test-1-40.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/663897/">playwright-js-tomcat90-mysql57-jdk8/3/0</a></li><li><a href="https://test-1-27.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1013738/">playwright-js-tomcat90-mysql57-jdk8/4/0</a></li><li><a href="https://test-1-28.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/915507/"><strike>playwright-js-tomcat90-mysql57-jdk8/5/0</strike></a></li><li><a href="https://test-1-30.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/979353/">playwright-js-tomcat90-mysql57-jdk8/6/0</a></li><li><a href="https://test-1-27.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1013735/"><strike>playwright-js-tomcat90-mysql57-jdk8/7/0</strike></a></li><li><a href="https://test-1-28.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/915503/">playwright-js-tomcat90-mysql57-jdk8/8/0</a></li><li><a href="https://test-1-30.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/979350/">playwright-js-tomcat90-mysql57-jdk8/9/0</a></li><li><a href="https://test-1-27.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1013740/"><strike>playwright-js-tomcat90-mysql57-jdk8/10/0</strike></a></li><li><a href="https://test-1-40.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/663899/">playwright-js-tomcat90-mysql57-jdk8/11/0</a></li><li><a href="https://test-1-32.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1025774/">playwright-js-tomcat90-mysql57-jdk8/12/0</a></li><li><a href="https://test-1-30.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/979355/">playwright-js-tomcat90-mysql57-jdk8/13/0</a></li><li><a href="https://test-1-28.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/915509/"><strike>playwright-js-tomcat90-mysql57-jdk8/14/0</strike></a></li><li><a href="https://test-1-27.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1013741/">playwright-js-tomcat90-mysql57-jdk8/15/0</a></li><li><a href="https://test-1-40.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/663900/">playwright-js-tomcat90-mysql57-jdk8/16/0</a></li><li><a href="https://test-1-26.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1133011/">playwright-js-tomcat90-mysql57-jdk8/17/0</a></li><li><a href="https://test-1-27.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1013734/">playwright-js-tomcat90-mysql57-jdk8/18/0</a></li><li><a href="https://test-1-40.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/663892/">playwright-js-tomcat90-mysql57-jdk8/19/0</a></li><li><a href="https://test-1-40.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/663894/"><strike>playwright-js-tomcat90-mysql57-jdk8/20/0</strike></a></li><li><a href="https://test-1-27.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1013736/">playwright-js-tomcat90-mysql57-jdk8/21/0</a></li><li><a href="https://test-1-28.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/915504/">playwright-js-tomcat90-mysql57-jdk8/22/0</a></li><li><a href="https://test-1-30.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/979351/">playwright-js-tomcat90-mysql57-jdk8/23/0</a></li><li><a href="https://test-1-40.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/663895/"><strike>playwright-js-tomcat90-mysql57-jdk8/24/0</strike></a></li><li><a href="https://test-1-27.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1013737/"><strike>playwright-js-tomcat90-mysql57-jdk8/25/0</strike></a></li><li><a href="https://test-1-28.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/915505/">playwright-js-tomcat90-mysql57-jdk8/26/0</a></li><li><a href="https://test-1-30.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/979352/">playwright-js-tomcat90-mysql57-jdk8/27/0</a></li><li><a href="https://test-1-40.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/663896/">playwright-js-tomcat90-mysql57-jdk8/28/0</a></li><li><a href="https://test-1-28.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/915506/">playwright-js-tomcat90-mysql57-jdk8/29/0</a></li><li><a href="https://test-1-28.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/915508/">playwright-js-tomcat90-mysql57-jdk8/30/0</a></li><li><a href="https://test-1-30.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/979354/"><strike>playwright-js-tomcat90-mysql57-jdk8/31/0</strike></a></li><li><a href="https://test-1-34.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/941781/">playwright-js-tomcat90-mysql57-jdk8/32/0</a></li></ul></li></ul></div><details><summary><strong>25 Successful Jobs:</strong></summary><ul/></details></details><h5>For more details click <a href="https://test-1-30.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/9395/jenkins-report.html">here</a>.</h5><hr/><h4>Failures unique to this pull:</h4><ol><li><div><a href="https://test-1-27.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1013740//consoleText">playwright-js-tomcat90-mysql57-jdk8/10/0</a> - <a href="https://testray.liferay.com/reports/production/logs/2024-06/test-1-30/test-portal-acceptance-pullrequest(master)/9395/playwright-js-tomcat90-mysql57-jdk8/10/0/playwright-report/index.html">Playwright Report</a><ol><li><details><summary><a href="https://test-1-27.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1013740/testReport/frontend-data-set-views-web_settings.spec/ts">frontend-data-set-views-web/settings.spec.ts</a></summary><div><ol><li><a href="https://test-1-27.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1013740//testReport/frontend-data-set-views-web_settings.spec/ts/Data_Set_Default_Visualization_Mode_in_fragment___When_the_default_visualization_mode_is_changed_in_the_Data_Set_Manager__the_change_is_reflected [...]

2024-06-17 12:44 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-30.liferay.com/job/test-portal-acceptance-pullrequest(master)/9395/">test-portal-acceptance-pullrequest(master)#9395</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-30.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/9395/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>playwright<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-content-management/liferay-portal/pull/5573">liferay-content-management#5573</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/#/project/34754/routines/34756">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/#/project/34754/routines/34756/build/19027483">[master] ci:test:playwright - boton &gt; liferay-content-management - PR#5573 - 2024-06-17[03:49:32]</a><br/></div><div><strong>Testray Build ID:</strong><span></span>19027483<br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-30.liferay.com/job/publish-testray-report/22451/">publish-testray-report#22451</a><br/></div></div>

2024-06-18 07:55 UTC, boton commented
No failures related to `blogs-web` ✅

2024-06-18 10:45 UTC, robertoDiaz requested changes
Changes look good to me.

My only concern is related with parameter and attribute names to match the new pattern.

Please change this and forward the PR :)

2024-06-18 10:45 UTC, robertoDiaz commented on modules/test/playwright/helpers/HeadlessAdminTaxonomyApiHelper.ts
> +	async postSiteKeyword({name, siteId}: postTagProps): Promise<{id: number}> {
Shouldn't we also rename `postTagProps` param to `postSiteKeywordProps`?

2024-06-18 10:45 UTC, robertoDiaz commented on modules/test/playwright/tests/blogs-web/utils/createCategories.ts
> +import type {postCategoryProps} from '../../../helpers/HeadlessAdminTaxonomyApiHelper';
Apply new naming pattern as well to match `postSiteTaxonomyVocabulary `

2024-06-19 12:16 UTC, boton commented
ci:test:playwright

2024-06-19 13:26 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>playwright</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-26.liferay.com/job/test-portal-acceptance-pullrequest(master)/13612/">test-portal-acceptance-pullrequest(master)</a></p><p><b>For more details click <a href="https://test-1-26.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/13612/jenkins-report.html">here</a>.</b></p>

2024-06-19 15:31 UTC, boton commented
Rebased, nuked the DB and files and re-test and all looks good ✅ 

![image](https://github.com/liferay-content-management/liferay-portal/assets/67901/55d3b809-a5bb-42da-b829-d6874dd737dc)

@robertoDiaz I applied your feedback ca39d5c5464b8fb0d6d3db8c872d2374fe84317d 😄  Can you review it?

2024-06-19 16:04 UTC, liferay-continuous-integration commented
<html><h3>:x: ci:test:playwright - 25 out of 35 jobs passed in 2 hours 38 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/2b88fe62f86d68c98ed3d15abc7d533c9145cc14">2b88fe62f86d68c98ed3d15abc7d533c9145cc14</a></p><h4>Upstream Comparison:</h4><p>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/2b88fe62f86d68c98ed3d15abc7d533c9145cc14">2b88fe62f86d68c98ed3d15abc7d533c9145cc14</a><br/>Jenkins Build URL: <a href="https://testray.liferay.com/#/project/34754/routines/174485/build/20886842">EE Development Acceptance (master) - 610 - 2024-06-18[20:39:40]</a></p><details><summary><strong>ci:test:playwright - 25 out of 35 jobs PASSED</strong></summary><div><h4>10 Failed Jobs:</h4><ul><li><a href="https://test-1-26.liferay.com/job/test-portal-acceptance-pullrequest(master)/13612/"><strike>test-portal-acceptance-pullrequest(master)</strike></a></li><li>playwright-compile-jdk8<ul><li><a href="https://test-1-25.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/617985/">playwright-compile-jdk8/0/0</a></li></ul></li><li>playwright-js-tomcat90-mysql57-jdk8<ul><li><a href="https://test-1-34.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/944089/"><strike>playwright-js-tomcat90-mysql57-jdk8/0/0</strike></a></li><li><a href="https://test-1-36.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/971834/"><strike>playwright-js-tomcat90-mysql57-jdk8/1/0</strike></a></li><li><a href="https://test-1-31.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1035904/">playwright-js-tomcat90-mysql57-jdk8/2/0</a></li><li><a href="https://test-1-35.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/898628/">playwright-js-tomcat90-mysql57-jdk8/3/0</a></li><li><a href="https://test-1-25.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/617990/">playwright-js-tomcat90-mysql57-jdk8/4/0</a></li><li><a href="https://test-1-27.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1016569/"><strike>playwright-js-tomcat90-mysql57-jdk8/5/0</strike></a></li><li><a href="https://test-1-35.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/898629/">playwright-js-tomcat90-mysql57-jdk8/6/0</a></li><li><a href="https://test-1-25.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/617986/"><strike>playwright-js-tomcat90-mysql57-jdk8/7/0</strike></a></li><li><a href="https://test-1-38.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/897136/">playwright-js-tomcat90-mysql57-jdk8/8/0</a></li><li><a href="https://test-1-38.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/897137/">playwright-js-tomcat90-mysql57-jdk8/9/0</a></li><li><a href="https://test-1-34.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/944090/"><strike>playwright-js-tomcat90-mysql57-jdk8/10/0</strike></a></li><li><a href="https://test-1-25.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/617991/">playwright-js-tomcat90-mysql57-jdk8/11/0</a></li><li><a href="https://test-1-31.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1035905/">playwright-js-tomcat90-mysql57-jdk8/12/0</a></li><li><a href="https://test-1-36.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/971835/">playwright-js-tomcat90-mysql57-jdk8/13/0</a></li><li><a href="https://test-1-27.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1016571/">playwright-js-tomcat90-mysql57-jdk8/14/0</a></li><li><a href="https://test-1-38.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/897138/">playwright-js-tomcat90-mysql57-jdk8/15/0</a></li><li><a href="https://test-1-34.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/944091/">playwright-js-tomcat90-mysql57-jdk8/16/0</a></li><li><a href="https://test-1-32.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1028224/">playwright-js-tomcat90-mysql57-jdk8/17/0</a></li><li><a href="https://test-1-38.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/897135/">playwright-js-tomcat90-mysql57-jdk8/18/0</a></li><li><a href="https://test-1-25.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/617984/">playwright-js-tomcat90-mysql57-jdk8/19/0</a></li><li><a href="https://test-1-27.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1016565/"><strike>playwright-js-tomcat90-mysql57-jdk8/20/0</strike></a></li><li><a href="https://test-1-35.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/898625/">playwright-js-tomcat90-mysql57-jdk8/21/0</a></li><li><a href="https://test-1-25.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/617987/">playwright-js-tomcat90-mysql57-jdk8/22/0</a></li><li><a href="https://test-1-25.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/617988/">playwright-js-tomcat90-mysql57-jdk8/23/0</a></li><li><a href="https://test-1-27.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1016566/"><strike>playwright-js-tomcat90-mysql57-jdk8/24/0</strike></a></li><li><a href="https://test-1-27.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1016567/">playwright-js-tomcat90-mysql57-jdk8/25/0</a></li><li><a href="https://test-1-35.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/898626/"><strike>playwright-js-tomcat90-mysql57-jdk8/26/0</strike></a></li><li><a href="https://test-1-25.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/617989/">playwright-js-tomcat90-mysql57-jdk8/27/0</a></li><li><a href="https://test-1-35.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/898627/">playwright-js-tomcat90-mysql57-jdk8/28/0</a></li><li><a href="https://test-1-27.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1016568/">playwright-js-tomcat90-mysql57-jdk8/29/0</a></li><li><a href="https://test-1-32.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1028223/">playwright-js-tomcat90-mysql57-jdk8/30/0</a></li><li><a href="https://test-1-27.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1016570/"><strike>playwright-js-tomcat90-mysql57-jdk8/31/0</strike></a></li><li><a href="https://test-1-35.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/898630/">playwright-js-tomcat90-mysql57-jdk8/32/0</a></li></ul></li></ul></div><details><summary><strong>25 Successful Jobs:</strong></summary><ul/></details></details><h5>For more details click <a href="https://test-1-26.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/13612/jenkins-report.html">here</a>.</h5><hr/><h4>Failures unique to this pull:</h4><ol><li><div><a href="https://test-1-34.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/944090//consoleText">playwright-js-tomcat90-mysql57-jdk8/10/0</a><pre>Build was aborted</pre></div></li><li><div><a href="https://test-1-34.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/944089//consoleText">playwright-js-tomcat90-mysql57-jdk8/0/0</a> - <a href="https://testray.liferay.com/reports/production/logs/2024-06/test-1-26/test-portal-acceptance-pullrequest(master)/13612/playwright-js-tomcat90-mysql57-jdk8/0/0/playwright-report/index.html">Playwright Report</a><ol><li><details><summary><a href="https://test-1-34.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/944089/testReport/frontend-data-set-web_itemActions.spec/ts">frontend-data-set-web/itemActions.spec.ts</a></summary><div><ol><li><a href="https://test-1-34.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/944089 [...]

2024-06-19 16:07 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-26.liferay.com/job/test-portal-acceptance-pullrequest(master)/13612/">test-portal-acceptance-pullrequest(master)#13612</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-26.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/13612/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>playwright<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-content-management/liferay-portal/pull/5573">liferay-content-management#5573</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/#/project/34754/routines/34756">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/#/project/34754/routines/34756/build/21168775">[master] ci:test:playwright - boton &gt; liferay-content-management - PR#5573 - 2024-06-19[06:25:52]</a><br/></div><div><strong>Testray Build ID:</strong><span></span>21168775<br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-26.liferay.com/job/publish-testray-report/31699/">publish-testray-report#31699</a><br/></div></div>

2024-06-19 18:13 UTC, robertoDiaz approved these changes

2024-06-19 18:13 UTC, robertoDiaz commented
ci:forward

2024-06-19 18:13 UTC, liferay-continuous-integration commented
CI is automatically triggering the following test suites:
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**relevant**
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**sf**
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**stable**

The pull request will automatically be forwarded to the user `brianchandotcom` If the following test suites pass:
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**relevant**
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**sf**
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**stable**

2024-06-19 18:14 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>relevant</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-28.liferay.com/job/test-portal-acceptance-pullrequest(master)/9633/">test-portal-acceptance-pullrequest(master)</a></p><p><b>For more details click <a href="https://test-1-28.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/9633/jenkins-report.html">here</a>.</b></p>

2024-06-19 18:15 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-28.liferay.com/job/test-portal-source-format/5390/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-28.liferay.com/userContent/jobs/test-portal-source-format/builds/5390/jenkins-report.html">here</a>.</b></p>

2024-06-19 18:19 UTC, liferay-continuous-integration commented
<html><h3>:heavy_check_mark: ci:test:sf - 1 out of 1 jobs passed in 5 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/dcb486343a4974e3fc8b67ede7d3d44a686d3afa">dcb486343a4974e3fc8b67ede7d3d44a686d3afa</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/boton/liferay-portal/tree/LPD-26755-TEST-Blogs-friendlyURL-translated-categories">LPD-26755-TEST-Blogs-friendlyURL-translated-categories</a><br/>Branch GIT ID: <a href="https://github.com/boton/liferay-portal/commit/ca39d5c5464b8fb0d6d3db8c872d2374fe84317d">ca39d5c5464b8fb0d6d3db8c872d2374fe84317d</a></p>1 out of 1jobs PASSED<details><summary><strong>1 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-28.liferay.com/job/test-portal-source-format/5390/">test-portal-source-format</a></li></ul></details><h5>For more details click <a href="https://test-1-28.liferay.com/userContent/jobs/test-portal-source-format/builds/5390/jenkins-report.html">here</a>.</h5></details></html>

2024-06-19 18:19 UTC, liferay-continuous-integration commented
All required test suite(s) passed.
Forwarding pull request to `brianchandotcom`.
[Console](https://test-1-28.liferay.com/job/test-portal-source-format/5390//consoleFull)

2024-06-19 18:19 UTC, closed without merging

2024-06-19 18:23 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-28.liferay.com/job/test-portal-acceptance-pullrequest(master)/9633/">test-portal-acceptance-pullrequest(master)#9633</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-28.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/9633/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>relevant<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-content-management/liferay-portal/pull/5573">liferay-content-management#5573</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/#/project/34754/routines/34756">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/#/project/34754/routines/34756/build/21274646">[master] ci:test:relevant - boton &gt; liferay-content-management - PR#5573 - 2024-06-19[11:13:58]</a><br/></div><div><strong>Testray Build ID:</strong><span></span>21274646<br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-28.liferay.com/job/publish-testray-report/21302/">publish-testray-report#21302</a><br/></div></div>