LPD-25633
liferay-content-management/liferay-portal pull request #5715
Opened 2024-07-24 20:58 UTC by gustavolimav

2024-07-24 20:58 UTC, liferay-continuous-integration commented
CI is automatically triggering the following test suites:
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**sf**

2024-07-24 21:01 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-3.liferay.com/job/test-portal-source-format/7944/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-3.liferay.com/userContent/jobs/test-portal-source-format/builds/7944/jenkins-report.html">here</a>.</b></p>

2024-07-24 21:04 UTC, liferay-continuous-integration commented
<html><h3>:heavy_check_mark: ci:test:sf - 1 out of 1 jobs passed in 5 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/cdcdc2fc2e3ddf93a5f162c717adad0a60ddc6ce">cdcdc2fc2e3ddf93a5f162c717adad0a60ddc6ce</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/gustavolimav/liferay-portal/tree/2024_22_07_PERFORMANCE_LPD-25633_BRYAN_FOLLOW_UP">2024_22_07_PERFORMANCE_LPD-25633_BRYAN_FOLLOW_UP</a><br/>Branch GIT ID: <a href="https://github.com/gustavolimav/liferay-portal/commit/ecb962df23e4258150e47f2ed766041dd2248133">ecb962df23e4258150e47f2ed766041dd2248133</a></p>1 out of 1jobs PASSED<details><summary><strong>1 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-3.liferay.com/job/test-portal-source-format/7944/">test-portal-source-format</a></li></ul></details><h5>For more details click <a href="https://test-1-3.liferay.com/userContent/jobs/test-portal-source-format/builds/7944/jenkins-report.html">here</a>.</h5></details></html>

2024-07-24 21:08 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-3.liferay.com/job/test-portal-source-format/7944/">test-portal-source-format#7944</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-3.liferay.com/userContent/jobs/test-portal-source-format/builds/7944/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-content-management/liferay-portal/pull/5715">liferay-content-management#5715</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/#/project/34754/routines/34756">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/#/project/34754/routines/34756/build/44658780">[master] ci:test:sf - gustavolimav &gt; liferay-content-management - PR#5715 - 2024-07-24[13:59:10]</a><br/></div><div><strong>Testray Build ID:</strong><span></span>44658780<br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-3.liferay.com/job/publish-testray-report/4315/">publish-testray-report#4315</a><br/></div></div>

2024-08-01 14:10 UTC, jkappler commented
Hi @gustavolimav, changes look good, but can we add some tests for it?

@AliciaGarciaGarcia

2024-08-01 14:13 UTC, gustavolimav commented
Hey @jkappler, sure I can! I will forward to headless team to review while I am creating it. Thx!

2024-08-01 14:17 UTC, jkappler commented
ok, perfect. Thanks @gustavolimav!

2024-08-01 14:18 UTC, gustavolimav commented
https://github.com/liferay-headless/liferay-portal/pull/2136

2024-08-01 20:10 UTC, gustavolimav commented
Hey @jkappler, pushed a test for this bug here https://github.com/liferay-content-management/liferay-portal/pull/5715/commits/13004c0c66b9a48013e09b62f46b309e3105c373.

2024-08-02 10:53 UTC, jkappler requested changes
@gustavolimav, test looks good, just those two small comments. Thanks for this!

2024-08-02 10:53 UTC, jkappler commented on modules/apps/wiki/wiki-test/src/testIntegration/java/com/liferay/wiki/search/test/WikiPageIndexerTest.java
> +		UserTestUtil.setUser(TestPropsValues.getUser());
Hi @gustavolimav, instead of setting the user, you can use the PermissionCheckerMethodTestRule in the aggregateTestRule

2024-08-02 10:53 UTC, jkappler commented on modules/apps/wiki/wiki-test/src/testIntegration/java/com/liferay/wiki/search/test/WikiPageIndexerTest.java
> +		String title = RandomTestUtil.randomString();
Better change the order @gustavolimav. Title first, then searchContext

2024-08-02 12:28 UTC, gustavolimav commented
Thx for the review @jkappler! I did the changes and I will close this PR to continue from here https://github.com/liferay-headless/liferay-portal/pull/2136

2024-08-02 12:28 UTC, closed without merging

2024-08-02 17:15 UTC, jkappler commented
Perfect, thanks @gustavolimav!