LPD-31578 Make page reload after posting a comment so the workflow actions are updated correctly
liferay-content-management/liferay-portal pull request #5727
Opened 2024-07-31 13:21 UTC by rebsilva

Related issue: https://liferay.atlassian.net/browse/LPD-31578

hi everyone!

this is a follow up PR where i fix the same bug as this [previous PR](https://github.com/liferay-workflow/liferay-portal/pull/1205) but now on master instead of the 7.3; it also has a new test to cover the scenario from the bug.

the PR was already approved by bpm team and you just need to review this commit:

really appreciate all the help on this, thanks a lot! :cherry_blossom:

2024-07-31 13:21 UTC, liferay-continuous-integration commented
CI is automatically triggering the following test suites:
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**sf**

2024-07-31 13:22 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-28.liferay.com/job/test-portal-source-format/5614/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-28.liferay.com/userContent/jobs/test-portal-source-format/builds/5614/jenkins-report.html">here</a>.</b></p>

2024-07-31 13:25 UTC, liferay-continuous-integration commented
<html><h3>:heavy_check_mark: ci:test:sf - 1 out of 1 jobs passed in 4 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/126643a80aae9e7ad6931a9f19981f87f613cabe">126643a80aae9e7ad6931a9f19981f87f613cabe</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/rebsilva/liferay-portal/tree/LPD-31578">LPD-31578</a><br/>Branch GIT ID: <a href="https://github.com/rebsilva/liferay-portal/commit/06edcb4537f596cfc8b93771fa1da4d1244f430a">06edcb4537f596cfc8b93771fa1da4d1244f430a</a></p>1 out of 1jobs PASSED<details><summary><strong>1 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-28.liferay.com/job/test-portal-source-format/5614/">test-portal-source-format</a></li></ul></details><h5>For more details click <a href="https://test-1-28.liferay.com/userContent/jobs/test-portal-source-format/builds/5614/jenkins-report.html">here</a>.</h5></details></html>

2024-08-01 16:25 UTC, boton commented
ci:test:playwright

2024-08-01 16:25 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>playwright</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-40.liferay.com/job/test-portal-acceptance-pullrequest(master)/10529/">test-portal-acceptance-pullrequest(master)</a></p><p><b>For more details click <a href="https://test-1-40.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/10529/jenkins-report.html">here</a>.</b></p>

2024-08-01 18:30 UTC, liferay-continuous-integration commented
<html><h3>:x: ci:test:playwright - 39 out of 64 jobs passed in 2 hours 4 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/3a38b9895b23f60a08a89f40db3e9713c737a3f9">3a38b9895b23f60a08a89f40db3e9713c737a3f9</a></p><h4>Upstream Comparison:</h4><p>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/48056d18b802278913738e9f8de8d6565d8386b4">48056d18b802278913738e9f8de8d6565d8386b4</a><br/>Jenkins Build URL: <a href="https://testray.liferay.com/#/project/34754/routines/174485/build/50828229">EE Development Acceptance (master) - 708 - 2024-08-01[04:37:59]</a></p><details><summary><strong>ci:test:playwright - 39 out of 64 jobs PASSED</strong></summary><div><h4>25 Failed Jobs:</h4><ul><li><a href="https://test-1-40.liferay.com/job/test-portal-acceptance-pullrequest(master)/10529/"><strike>test-portal-acceptance-pullrequest(master)</strike></a></li><li>playwright-compile-jdk8<ul><li><a href="https://test-1-34.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/973748/">playwright-compile-jdk8/0/0</a></li></ul></li><li>playwright-js-tomcat90-mysql57-jdk8<ul><li><a href="https://test-1-26.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1164412/">playwright-js-tomcat90-mysql57-jdk8/0/0</a></li><li><a href="https://test-1-34.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/973749/"><strike>playwright-js-tomcat90-mysql57-jdk8/1/0</strike></a></li><li><a href="https://test-1-34.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/973747/">playwright-js-tomcat90-mysql57-jdk8/2/0</a></li><li><a href="https://test-1-36.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1004001/">playwright-js-tomcat90-mysql57-jdk8/3/0</a></li><li><a href="https://test-1-36.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1003999/"><strike>playwright-js-tomcat90-mysql57-jdk8/4/0</strike></a></li><li><a href="https://test-1-38.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/924138/">playwright-js-tomcat90-mysql57-jdk8/5/0</a></li><li><a href="https://test-1-38.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/924136/">playwright-js-tomcat90-mysql57-jdk8/6/0</a></li><li><a href="https://test-1-40.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/700951/"><strike>playwright-js-tomcat90-mysql57-jdk8/7/0</strike></a></li><li><a href="https://test-1-27.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1044932/"><strike>playwright-js-tomcat90-mysql57-jdk8/8/0</strike></a></li><li><a href="https://test-1-30.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1015118/">playwright-js-tomcat90-mysql57-jdk8/9/0</a></li><li><a href="https://test-1-30.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1015119/"><strike>playwright-js-tomcat90-mysql57-jdk8/10/0</strike></a></li><li><a href="https://test-1-33.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/884651/">playwright-js-tomcat90-mysql57-jdk8/11/0</a></li><li><a href="https://test-1-32.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1056763/"><strike>playwright-js-tomcat90-mysql57-jdk8/12/0</strike></a></li><li><a href="https://test-1-31.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1066215/">playwright-js-tomcat90-mysql57-jdk8/13/0</a></li><li><a href="https://test-1-25.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/646926/"><strike>playwright-js-tomcat90-mysql57-jdk8/14/0</strike></a></li><li><a href="https://test-1-37.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1169733/">playwright-js-tomcat90-mysql57-jdk8/15/0</a></li><li><a href="https://test-1-3.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/452868/">playwright-js-tomcat90-mysql57-jdk8/16/0</a></li><li><a href="https://test-1-1.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/347473/">playwright-js-tomcat90-mysql57-jdk8/17/0</a></li><li><a href="https://test-1-25.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/646924/"><strike>playwright-js-tomcat90-mysql57-jdk8/18/0</strike></a></li><li><a href="https://test-1-38.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/924137/"><strike>playwright-js-tomcat90-mysql57-jdk8/19/0</strike></a></li><li><a href="https://test-1-30.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1015120/"><strike>playwright-js-tomcat90-mysql57-jdk8/20/0</strike></a></li><li><a href="https://test-1-39.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/947314/">playwright-js-tomcat90-mysql57-jdk8/21/0</a></li><li><a href="https://test-1-39.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/947316/">playwright-js-tomcat90-mysql57-jdk8/22/0</a></li><li><a href="https://test-1-32.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1056762/"><strike>playwright-js-tomcat90-mysql57-jdk8/23/0</strike></a></li><li><a href="https://test-1-32.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1056764/">playwright-js-tomcat90-mysql57-jdk8/24/0</a></li><li><a href="https://test-1-37.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1169730/">playwright-js-tomcat90-mysql57-jdk8/25/0</a></li><li><a href="https://test-1-37.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1169732/">playwright-js-tomcat90-mysql57-jdk8/26/0</a></li><li><a href="https://test-1-25.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/646925/">playwright-js-tomcat90-mysql57-jdk8/27/0</a></li><li><a href="https://test-1-29.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/950891/"><strike>playwright-js-tomcat90-mysql57-jdk8/28/0</strike></a></li><li><a href="https://test-1-3.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/452869/">playwright-js-tomcat90-mysql57-jdk8/29/0</a></li><li><a href="https://test-1-40.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/700953/"><strike>playwright-js-tomcat90-mysql57-jdk8/30/0</strike></a></li><li><a href="https://test-1-27.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1044931/"><strike>playwright-js-tomcat90-mysql57-jdk8/31/0</strike></a></li><li><a href="https://test-1-30.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1015117/"><strike>playwright-js-tomcat90-mysql57-jdk8/32/0</strike></a></li><li><a href="https://test-1-39.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/947315/">playwright-js-tomcat90-mysql57-jdk8/33/0</a></li><li><a href="https://test-1-32.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1056761/"><strike>playwright-js-tomcat90-mysql57-jdk8/34/0</strike></a></li><li><a href="https://test-1-29.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/950738/"><strike>playwright-js-tomcat90-mysql57-jdk8/35/0</strike></a></li><li><a href="https://test-1-25.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/646928/">playwright-js-tomcat90-mysql57-jdk8/36/0</a></li><li><a href="https://test-1-1.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/347471/">playwright-js-tomcat90-mysql57-jdk8/37/0</a></li><li><a href="https://test-1-27.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1045066/"><strike>playwright-js-tomcat90-mysql57-jdk8/38/0</strike></a></li><li><a href="https://test-1-35.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/921020/"><strike>playwright-js-tomcat90-mysql57-jdk8/39/0</strike></a></li><li [...]

2024-08-01 18:34 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-40.liferay.com/job/test-portal-acceptance-pullrequest(master)/10529/">test-portal-acceptance-pullrequest(master)#10529</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-40.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/10529/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>playwright<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-content-management/liferay-portal/pull/5727">liferay-content-management#5727</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/#/project/34754/routines/34756">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/#/project/34754/routines/34756/build/51157208">[master] ci:test:playwright - rebsilva &gt; liferay-content-management - PR#5727 - 2024-08-01[09:25:25]</a><br/></div><div><strong>Testray Build ID:</strong><span></span>51157208<br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-40.liferay.com/job/publish-testray-report/22414/">publish-testray-report#22414</a><br/></div></div>

2024-08-02 11:51 UTC, boton reviewed
Thanks for the PR 😄  

After talking about it with the team, we have a question.

Could you please tell us why you're trying to fix some workflow issues in the comment taglib?

This change will reload the page in all of the places that the taglib is being used.

![image](https://github.com/user-attachments/assets/8d81bb67-df12-4138-8413-f29a93e8ecd1)

2024-08-05 14:04 UTC, rebsilva commented
hi @boton! thanks a lot for your review :blush: 

i'm trying to solve this problem: when we try to approve or reject an workflow task, after adding a comment on the "edit workflow task" page, the page breaks.


https://github.com/user-attachments/assets/75b70089-d504-46f8-88c0-85a3f7564ff7



from what i've investigated this happens because when we add a comment it only reloads the comment section and it interferes with the actions on the kebab menu to approve or reject the task ([here](https://github.com/liferay/liferay-portal/blob/master/modules/apps/portal-workflow/portal-workflow-task-web/src/main/resources/META-INF/resources/js/index.js) is the file where the actions are created). since the page is made by different `jsp` files, the only way i found to fix the problem is to reload the page so the actions can be built correctly again.

what you said is indeed true (the page will reload in other places) but i did the same thing on [this PR](https://github.com/liferay-workflow/liferay-portal/pull/1205) reviewed by the team for the 7.3, so i thought it wasn't a problem on this case. also since the `Comments.js` has the property `refreshPage` i thought it was an expected behavior in some places.

do you have any suggestions about what would be a better solution for this? maybe send a new property like `refreshPage` here on `edit_workflow_task.jsp`:

```
<liferay-comment:discussion
		assetEntryVisible="<%= false %>"
		className="<%= assetRenderer.getClassName() %>"
		classPK="<%= discussionClassPK %>"
		formName='<%= "fm" + discussionClassPK %>'
		ratingsEnabled="<%= false %>"
		redirect="<%= currentURL %>"
		userId="<%= user.getUserId() %>"
/>
```

if you have any new ideas or suggestions about this i would be very happy to hear! thanks again for your review and attention to keep the correct behaviors inside our portal; i'm here for any further questions you may have, thanks!!

2024-08-05 17:54 UTC, boton requested changes
Hi @rebsilva! thanks for the responses

> what you said is indeed true (the page will reload in other places) but i did the same thing on https://github.com/liferay-workflow/liferay-portal/pull/1205 reviewed by the team for the 7.3, so i thought it wasn't a problem on this case. 

Sorry, I guess we didn't realize it in the PR for 7.3, we will need to move these changes to 7.3 too

> also since the Comments.js has the property refreshPage i thought it was an expected behavior in some places.

You are right but before an investigation, the reload page only happens after a [successful modal login](https://github.com/liferay/liferay-portal/blob/7d8c7ca40986b4b9218504cd301092d72a1ee96a/modules/apps/comment/comment-taglib/src/main/resources/META-INF/resources/discussion/js/Comments.js#L321-L330)

> maybe send a new property like `refreshPage` here on edit_workflow_task.jsp

This is a good idea at least the full refresh on reply only happens in the `edit_workflow_task.jsp` ❤️  maybe the property mane `refreshPageOnReply` is more explicit

2024-08-05 18:11 UTC, rebsilva commented on modules/apps/comment/comment-taglib/src/main/resources/META-INF/resources/discussion/js/Comments.js
> +			setTimeout(() => window.location.reload(), 1000);
before my changes when a user add a comment the success message appears, so i tried to keep the same behavior; don't know if is really necessary, but i tried to keep as close as possible to the previous one.

i agree that is not optimal to show for only a second and it should be after the reload, but i couldn't find a way to put after the reload :thinking: any suggestions about this?

2024-08-05 18:20 UTC, rebsilva commented on modules/apps/comment/comment-taglib/src/main/resources/META-INF/resources/discussion/js/Comments.js
> +			setTimeout(() => window.location.reload(), 1000);
but yes, i can remove it from here since it will interfere on other pages as well

2024-08-05 18:22 UTC, rebsilva commented
hi @boton! thanks a lot for all the explanations :cherry_blossom:
i'll try to implement the changes we've discussed and send it soon!

2024-08-09 06:42 UTC, robertoDiaz commented
@rebsilva any update about this?

2024-08-12 13:29 UTC, closed without merging