LPD-33971
liferay-content-management/liferay-portal pull request #5759
Opened 2024-08-14 12:31 UTC by Mikellorza

2024-08-14 12:31 UTC, liferay-continuous-integration commented
CI is automatically triggering the following test suites:
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**sf**

2024-08-14 12:32 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-31.liferay.com/job/test-portal-source-format/6595/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-31.liferay.com/userContent/jobs/test-portal-source-format/builds/6595/jenkins-report.html">here</a>.</b></p>

2024-08-14 12:34 UTC, liferay-continuous-integration commented
<html><h3>:heavy_check_mark: ci:test:sf - 1 out of 1 jobs passed in 3 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/4ac2bb325f95f17c29dd79238837f75e9d9a886e">4ac2bb325f95f17c29dd79238837f75e9d9a886e</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/Mikellorza/liferay-portal/tree/LPD-33971">LPD-33971</a><br/>Branch GIT ID: <a href="https://github.com/Mikellorza/liferay-portal/commit/50f02340da2e53bc02efb2e9288c98a5d06c0b00">50f02340da2e53bc02efb2e9288c98a5d06c0b00</a></p>1 out of 1jobs PASSED<details><summary><strong>1 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-31.liferay.com/job/test-portal-source-format/6595/">test-portal-source-format</a></li></ul></details><h5>For more details click <a href="https://test-1-31.liferay.com/userContent/jobs/test-portal-source-format/builds/6595/jenkins-report.html">here</a>.</h5></details></html>

2024-08-14 12:36 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-31.liferay.com/job/test-portal-source-format/6595/">test-portal-source-format#6595</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-31.liferay.com/userContent/jobs/test-portal-source-format/builds/6595/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-content-management/liferay-portal/pull/5759">liferay-content-management#5759</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/#/project/34754/routines/34756">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/#/project/34754/routines/34756/build/60960598">[master] ci:test:sf - Mikellorza &gt; liferay-content-management - PR#5759 - 2024-08-14[05:31:33]</a><br/></div><div><strong>Testray Build ID:</strong><span></span>60960598<br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-31.liferay.com/job/publish-testray-report/25805/">publish-testray-report#25805</a><br/></div></div>

2024-08-14 12:45 UTC, Mikellorza commented
ci:test:sf

2024-08-14 12:46 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-27.liferay.com/job/test-portal-source-format/7072/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-27.liferay.com/userContent/jobs/test-portal-source-format/builds/7072/jenkins-report.html">here</a>.</b></p>

2024-08-14 12:50 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-27.liferay.com/job/test-portal-source-format/7072/">test-portal-source-format#7072</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-27.liferay.com/userContent/jobs/test-portal-source-format/builds/7072/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-content-management/liferay-portal/pull/5759">liferay-content-management#5759</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/#/project/34754/routines/34756">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/#/project/34754/routines/34756/build/60973417">[master] ci:test:sf - Mikellorza &gt; liferay-content-management - PR#5759 - 2024-08-14[05:45:39]</a><br/></div><div><strong>Testray Build ID:</strong><span></span>60973417<br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-27.liferay.com/job/publish-testray-report/27033/">publish-testray-report#27033</a><br/></div></div>

2024-08-19 14:22 UTC, AliciaGarciaGarcia requested changes
Failing test I seems relevant for this PR: 
```

com.liferay.document.library.internal.search.spi.model.index.contributor.test.DLFileEntryModelDocumentContributorTest > testFileEntryMetadataAttributes FAILED
    java.lang.AssertionError: expected:<225> but was:<0>
    	at org.junit.Assert.fail(Assert.java:89)
    	at org.junit.Assert.failNotEquals(Assert.java:835)
    	at org.junit.Assert.assertEquals(Assert.java:647)
    	at org.junit.Assert.assertEquals(Assert.java:633)
    	at com.liferay.document.library.internal.search.spi.model.index.contributor.test.DLFileEntryModelDocumentContributorTest._testFileEntryMetadataAttributesImageFileEntry(DLFileEntryModelDocumentContributorTest.java:443)
```

2024-08-19 14:22 UTC, AliciaGarciaGarcia commented on modules/apps/document-library/document-library-service/src/main/java/com/liferay/document/library/internal/search/spi/model/index/contributor/DLFileEntryModelDocumentContributor.java
> +					if ((tiffImageLength <= 300) && (tiffImageWidth <= 400)) {
magic number?

maybe to extract to a constants ?

2024-08-26 11:19 UTC, Mikellorza commented
Hi @AliciaGarciaGarcia ,

I made some changes related to your comments. Can you take a look again?

If you see that changes are fine we can run tests again to see if still fail but they should not fail.

thanks in advance!

2024-08-26 13:41 UTC, jkappler approved these changes

2024-08-26 13:41 UTC, jkappler commented
ci:forward

2024-08-26 13:42 UTC, liferay-continuous-integration commented
CI is automatically triggering the following test suites:
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**relevant**
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**sf**
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**stable**

The pull request will automatically be forwarded to the user `brianchandotcom` If the following test suites pass:
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**relevant**
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**sf**
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**stable**

2024-08-26 13:42 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>relevant</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-32.liferay.com/job/test-portal-acceptance-pullrequest(master)/4823/">test-portal-acceptance-pullrequest(master)</a></p><p><b>For more details click <a href="https://test-1-32.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/4823/jenkins-report.html">here</a>.</b></p>

2024-08-26 13:43 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-32.liferay.com/job/test-portal-source-format/8881/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-32.liferay.com/userContent/jobs/test-portal-source-format/builds/8881/jenkins-report.html">here</a>.</b></p>

2024-08-26 13:45 UTC, liferay-continuous-integration commented
<html><h3>:heavy_check_mark: ci:test:sf - 1 out of 1 jobs passed in 4 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/a52f173526c61780bf2bc8c5e53dac264d6f9560">a52f173526c61780bf2bc8c5e53dac264d6f9560</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/Mikellorza/liferay-portal/tree/LPD-33971">LPD-33971</a><br/>Branch GIT ID: <a href="https://github.com/Mikellorza/liferay-portal/commit/9506411cd02e512202145b5f8e57a21b71ea720a">9506411cd02e512202145b5f8e57a21b71ea720a</a></p>1 out of 1jobs PASSED<details><summary><strong>1 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-32.liferay.com/job/test-portal-source-format/8881/">test-portal-source-format</a></li></ul></details><h5>For more details click <a href="https://test-1-32.liferay.com/userContent/jobs/test-portal-source-format/builds/8881/jenkins-report.html">here</a>.</h5></details></html>

2024-08-26 13:47 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-32.liferay.com/job/test-portal-source-format/8881/">test-portal-source-format#8881</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-32.liferay.com/userContent/jobs/test-portal-source-format/builds/8881/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-content-management/liferay-portal/pull/5759">liferay-content-management#5759</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/#/project/34754/routines/34756">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/#/project/34754/routines/34756/build/71598619">[master] ci:test:sf - Mikellorza &gt; liferay-content-management - PR#5759 - 2024-08-26[06:42:06]</a><br/></div><div><strong>Testray Build ID:</strong><span></span>71598619<br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-32.liferay.com/job/publish-testray-report/33501/">publish-testray-report#33501</a><br/></div></div>

2024-08-26 15:16 UTC, liferay-continuous-integration commented
All required test suite(s) passed.
Forwarding pull request to `brianchandotcom`.
[Console](https://test-1-32.liferay.com/job/test-portal-acceptance-pullrequest(master)/4823//consoleFull)

2024-08-26 15:17 UTC, closed without merging

2024-08-26 15:17 UTC, liferay-continuous-integration commented
Pull request has been successfully forwarded to  https://github.com/brianchandotcom/liferay-portal/pull/153621
[Console](https://test-1-32.liferay.com/job/test-portal-acceptance-pullrequest(master)/4823//consoleFull)