LPD-33787 Add new ci:test:content-management-playwright suite
liferay-content-management/liferay-portal pull request #5780
Opened 2024-08-21 08:23 UTC by boton

# What is this trying to solve?

https://liferay.atlassian.net/browse/LPD-33787

I added a new `ci:test:content-management-playwright` suite for run only Content Management team playwright tests.

# How am I fixing it?

Adding the new `content-management-playwright` suite

# How can you verify that it works?

Comment

```sh
ci:test:content-management-playwright
```

in the PR to launch the suite :D

# Why doesn't this include any test?

Because it is an infraestruccture change to launch our Content Management playwright tests

2024-08-21 08:23 UTC, liferay-continuous-integration commented
CI is automatically triggering the following test suites:
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**sf**

2024-08-21 08:24 UTC, boton commented
ci:test:content-management-playwright

2024-08-21 08:24 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>content-management-playwright</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-31.liferay.com/job/test-portal-acceptance-pullrequest(master)/11249/">test-portal-acceptance-pullrequest(master)</a></p><p><b>For more details click <a href="https://test-1-31.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/11249/jenkins-report.html">here</a>.</b></p>

2024-08-21 08:25 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-30.liferay.com/job/test-portal-source-format/6105/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-30.liferay.com/userContent/jobs/test-portal-source-format/builds/6105/jenkins-report.html">here</a>.</b></p>

2024-08-21 08:27 UTC, liferay-continuous-integration commented
<html><h3>:heavy_check_mark: ci:test:sf - 1 out of 1 jobs passed in 3 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/db0e622aca8c7e78772f5bda1e0290d44f2707c8">db0e622aca8c7e78772f5bda1e0290d44f2707c8</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/boton/liferay-portal/tree/LPD-33787-FEAT-add-content-management-playwright-suite">LPD-33787-FEAT-add-content-management-playwright-suite</a><br/>Branch GIT ID: <a href="https://github.com/boton/liferay-portal/commit/2147f66f26be84d1bef14f40430cce0bce8c1abd">2147f66f26be84d1bef14f40430cce0bce8c1abd</a></p>1 out of 1jobs PASSED<details><summary><strong>1 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-30.liferay.com/job/test-portal-source-format/6105/">test-portal-source-format</a></li></ul></details><h5>For more details click <a href="https://test-1-30.liferay.com/userContent/jobs/test-portal-source-format/builds/6105/jenkins-report.html">here</a>.</h5></details></html>

2024-08-21 08:29 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-30.liferay.com/job/test-portal-source-format/6105/">test-portal-source-format#6105</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-30.liferay.com/userContent/jobs/test-portal-source-format/builds/6105/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-content-management/liferay-portal/pull/5780">liferay-content-management#5780</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/#/project/34754/routines/34756">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/#/project/34754/routines/34756/build/67509831">[master] ci:test:sf - boton &gt; liferay-content-management - PR#5780 - 2024-08-21[01:23:58]</a><br/></div><div><strong>Testray Build ID:</strong><span></span>67509831<br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-30.liferay.com/job/publish-testray-report/23661/">publish-testray-report#23661</a><br/></div></div>

2024-08-21 09:25 UTC, liferay-continuous-integration commented
<html><h3>:x: ci:test:content-management-playwright - 9 out of 13 jobs passed in 58 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/db0e622aca8c7e78772f5bda1e0290d44f2707c8">db0e622aca8c7e78772f5bda1e0290d44f2707c8</a></p><h4>Upstream Comparison:</h4><p>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/db0e622aca8c7e78772f5bda1e0290d44f2707c8">db0e622aca8c7e78772f5bda1e0290d44f2707c8</a><br/>Jenkins Build URL: <a href="https://testray.liferay.com/#/project/34754/routines/174485/build/67349847">EE Development Acceptance (master) - 760 - 2024-08-20[16:40:03]</a></p><details><summary><strong>ci:test:content-management-playwright - 9 out of 13 jobs PASSED</strong></summary><div><h4>4 Failed Jobs:</h4><ul><li><a href="https://test-1-31.liferay.com/job/test-portal-acceptance-pullrequest(master)/11249/"><strike>test-portal-acceptance-pullrequest(master)</strike></a></li><li>playwright-js-tomcat90-mysql57-jdk8<ul><li><a href="https://test-1-39.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/961580/">playwright-js-tomcat90-mysql57-jdk8/0/0</a></li><li><a href="https://test-1-25.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/660423/">playwright-js-tomcat90-mysql57-jdk8/1/0</a></li><li><a href="https://test-1-37.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1184363/">playwright-js-tomcat90-mysql57-jdk8/2/0</a></li><li><a href="https://test-1-10.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/419682/">playwright-js-tomcat90-mysql57-jdk8/3/0</a></li><li><a href="https://test-1-2.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/413205/">playwright-js-tomcat90-mysql57-jdk8/4/0</a></li><li><a href="https://test-1-33.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/898292/"><strike>playwright-js-tomcat90-mysql57-jdk8/5/0</strike></a></li><li><a href="https://test-1-3.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/459576/">playwright-js-tomcat90-mysql57-jdk8/6/0</a></li><li><a href="https://test-1-39.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/961579/">playwright-js-tomcat90-mysql57-jdk8/7/0</a></li><li><a href="https://test-1-3.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/459575/">playwright-js-tomcat90-mysql57-jdk8/8/0</a></li><li><a href="https://test-1-25.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/660424/"><strike>playwright-js-tomcat90-mysql57-jdk8/9/0</strike></a></li><li><a href="https://test-1-25.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/660425/"><strike>playwright-js-tomcat90-mysql57-jdk8/10/0</strike></a></li><li><a href="https://test-1-31.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1079900/">playwright-js-tomcat90-mysql57-jdk8/11/0</a></li></ul></li></ul></div><details><summary><strong>9 Successful Jobs:</strong></summary><ul/></details></details><h5>For more details click <a href="https://test-1-31.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/11249/jenkins-report.html">here</a>.</h5><hr/><h4>Failures unique to this pull:</h4><ol><li><div><a href="https://test-1-33.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/898292//consoleText">playwright-js-tomcat90-mysql57-jdk8/5/0</a> - <a href="https://testray.liferay.com/reports/production/logs/2024-08/test-1-31/test-portal-acceptance-pullrequest(master)/11249/playwright-js-tomcat90-mysql57-jdk8/5/0/playwright-report/index.html">Playwright Report</a><ol><li><details><summary><a href="https://test-1-33.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/898292/testReport/wiki-web_wiki.spec/ts">wiki-web/wiki.spec.ts</a></summary><div><ol><li><a href="https://test-1-33.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/898292//testReport/wiki-web_wiki.spec/ts/LPD_28898_Image_added_via_rich_text_editor_on_Wiki_tool_losing_reference">LPD-28898 Image added via rich text editor on Wiki tool losing reference</a></li></ol></div></details></li></ol></div></li><li><div><a href="https://test-1-25.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/660424//consoleText">playwright-js-tomcat90-mysql57-jdk8/9/0</a> - <a href="https://testray.liferay.com/reports/production/logs/2024-08/test-1-31/test-portal-acceptance-pullrequest(master)/11249/playwright-js-tomcat90-mysql57-jdk8/9/0/playwright-report/index.html">Playwright Report</a><ol><li><details><summary><a href="https://test-1-25.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/660424/testReport/journal-web_journalArticle.spec/ts">journal-web/journalArticle.spec.ts</a></summary><div><ol><li><a href="https://test-1-25.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/660424//testReport/journal-web_journalArticle.spec/ts/LPD_17245__Add_error_message_in_Translation_for_concurrent_users">LPD-17245: Add error message in Translation for concurrent users</a></li><li><a href="https://test-1-25.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/660424//testReport/journal-web_journalArticle.spec/ts/LPD_31072__Translation_is_removed_when_using_Undo_and_restored_when_using_Redo">LPD-31072: Translation is removed when using Undo and restored when using Redo</a></li></ol></div></details></li></ol></div></li><li><div><a href="https://test-1-25.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/660425//consoleText">playwright-js-tomcat90-mysql57-jdk8/10/0</a> - <a href="https://testray.liferay.com/reports/production/logs/2024-08/test-1-31/test-portal-acceptance-pullrequest(master)/11249/playwright-js-tomcat90-mysql57-jdk8/10/0/playwright-report/index.html">Playwright Report</a><ol><li><details><summary><a href="https://test-1-25.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/660425/testReport/document-library-web_fileEntry.spec/ts">document-library-web/fileEntry.spec.ts</a></summary><div><ol><li><a href="https://test-1-25.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/660425//testReport/document-library-web_fileEntry.spec/ts/LPD_16313_Show_icon_in_the_content_admin_and_content_editor">LPD-16313 Show icon in the content admin and content editor</a></li><li><a href="https://test-1-25.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/660425//testReport/document-library-web_fileEntry.spec/ts/LPD_29609_Error_uploading_multiples_files_with_custom_document_type">LPD-29609 Error uploading multiples files with custom document type</a></li></ol></div></details></li></ol></div></li></ol><h4>For upstream results, click <a href="https://test-1-40.liferay.com/job/test-portal-acceptance-upstream-dxp(master)">here</a>.</h4></details></html>

2024-08-21 09:29 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-31.liferay.com/job/test-portal-acceptance-pullrequest(master)/11249/">test-portal-acceptance-pullrequest(master)#11249</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-31.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/11249/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>content-management-playwright<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-content-management/liferay-portal/pull/5780">liferay-content-management#5780</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/#/project/34754/routines/34756">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/#/project/34754/routines/34756/build/67548037">[master] ci:test:content-management-playwright - boton &gt; liferay-content-management - PR#5780 - 2024-08-21[01:24:21]</a><br/></div><div><strong>Testray Build ID:</strong><span></span>67548037<br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-31.liferay.com/job/publish-testray-report/25925/">publish-testray-report#25925</a><br/></div></div>

2024-08-21 13:11 UTC, adolfopa requested changes

2024-08-22 06:50 UTC, boton commented on ci.properties
> +ci.test.suite.description[content-management-playwright]=Test Content Management team playwright tests.
Done! But it's a copy/paste from [echo / page-managment description](https://github.com/liferay-content-management/liferay-portal/blob/db0e622aca8c7e78772f5bda1e0290d44f2707c8/ci.properties#L352)

2024-08-23 06:35 UTC, adolfopa approved these changes

2024-08-23 06:35 UTC, adolfopa commented
ci:forward

2024-08-23 06:35 UTC, liferay-continuous-integration commented
CI is automatically triggering the following test suites:
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**relevant**
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**sf**
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**stable**

The pull request will automatically be forwarded to the user `brianchandotcom` If the following test suites pass:
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**relevant**
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**sf**
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**stable**

2024-08-23 06:38 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-25.liferay.com/job/test-portal-source-format/2975/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-25.liferay.com/userContent/jobs/test-portal-source-format/builds/2975/jenkins-report.html">here</a>.</b></p>

2024-08-23 06:40 UTC, liferay-continuous-integration commented
<html><h3>:heavy_check_mark: ci:test:sf - 1 out of 1 jobs passed in 3 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/90ef011c53315d02aea74b011f99613ecd37cf1a">90ef011c53315d02aea74b011f99613ecd37cf1a</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/boton/liferay-portal/tree/LPD-33787-FEAT-add-content-management-playwright-suite">LPD-33787-FEAT-add-content-management-playwright-suite</a><br/>Branch GIT ID: <a href="https://github.com/boton/liferay-portal/commit/b9367add3deafba6c0be056c280e31746ba7756b">b9367add3deafba6c0be056c280e31746ba7756b</a></p>1 out of 1jobs PASSED<details><summary><strong>1 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-25.liferay.com/job/test-portal-source-format/2975/">test-portal-source-format</a></li></ul></details><h5>For more details click <a href="https://test-1-25.liferay.com/userContent/jobs/test-portal-source-format/builds/2975/jenkins-report.html">here</a>.</h5></details></html>

2024-08-23 06:40 UTC, liferay-continuous-integration commented
All required test suite(s) passed.
Forwarding pull request to `brianchandotcom`.
[Console](https://test-1-25.liferay.com/job/test-portal-source-format/2975//consoleFull)

2024-08-23 06:40 UTC, closed without merging

2024-08-23 06:40 UTC, liferay-continuous-integration commented
Pull request has been successfully forwarded to  https://github.com/brianchandotcom/liferay-portal/pull/153552
[Console](https://test-1-25.liferay.com/job/test-portal-source-format/2975//consoleFull)

2024-08-23 06:42 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-25.liferay.com/job/test-portal-source-format/2975/">test-portal-source-format#2975</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-25.liferay.com/userContent/jobs/test-portal-source-format/builds/2975/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-content-management/liferay-portal/pull/5780">liferay-content-management#5780</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/#/project/34754/routines/34756">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/#/project/34754/routines/34756/build/70002522">[master] ci:test:sf - boton &gt; liferay-content-management - PR#5780 - 2024-08-22[23:36:48]</a><br/></div><div><strong>Testray Build ID:</strong><span></span>70002522<br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-25.liferay.com/job/publish-testray-report/12090/">publish-testray-report#12090</a><br/></div></div>

2024-08-23 07:17 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>relevant</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-25.liferay.com/job/test-portal-acceptance-pullrequest(master)/5887/">test-portal-acceptance-pullrequest(master)</a></p><p><b>For more details click <a href="https://test-1-25.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/5887/jenkins-report.html">here</a>.</b></p>

2024-08-23 07:25 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-25.liferay.com/job/test-portal-acceptance-pullrequest(master)/5887/">test-portal-acceptance-pullrequest(master)#5887</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-25.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/5887/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>relevant<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-content-management/liferay-portal/pull/5780">liferay-content-management#5780</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/#/project/34754/routines/34756">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/#/project/34754/routines/34756/build/70042102">[master] ci:test:relevant - boton &gt; liferay-content-management - PR#5780 - 2024-08-23[00:17:04]</a><br/></div><div><strong>Testray Build ID:</strong><span></span>70042102<br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-25.liferay.com/job/publish-testray-report/12091/">publish-testray-report#12091</a><br/></div></div>