LPD-38758 translate shows the duplicate fields - playwright test
liferay-content-management/liferay-portal pull request #5962
Opened 2024-10-08 14:50 UTC by gergelyszalay

Hi,
May I ask to review this PR .

Is it for https://liferay.atlassian.net/browse/LPD-38758. 

Solution: created TranslationsInterface#CanViewDuplicateFields test in playwright.

The issue was with the button to create the duplicated field. It is working in PW if we click outside first.

Removed the Poshi test as well.

Thank you!

2024-10-08 14:50 UTC, liferay-continuous-integration commented
CI is automatically triggering the following test suites:
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**sf**

2024-10-08 14:51 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-37.liferay.com/job/test-portal-source-format/10298/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-37.liferay.com/userContent/jobs/test-portal-source-format/builds/10298/jenkins-report.html">here</a>.</b></p>

2024-10-08 15:04 UTC, gergelyszalay commented
ci:test:content-management-playwright

2024-10-08 15:11 UTC, gergelyszalay commented
ci:test:content-management-playwright

2024-10-08 15:12 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>content-management-playwright</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-39.liferay.com/job/test-portal-acceptance-pullrequest(master)/11454/">test-portal-acceptance-pullrequest(master)</a></p><p><b>For more details click <a href="https://test-1-39.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/11454/jenkins-report.html">here</a>.</b></p>

2024-10-08 16:40 UTC, liferay-continuous-integration commented
<html><h3>:x: ci:test:content-management-playwright - 9 out of 12 jobs passed in 1 hour 28 minutes</h3><details><summary>Click here for more details.</summary><br/><p>This pull is eligible for <a href="https://grow.liferay.com/share/CI+liferay-continuous-integration+GitHub+Commands#General-Commands">reevaluation</a>. When this <a href="https://test-1-40.liferay.com/job/test-portal-acceptance-upstream-dxp(master)/898">upstream build</a> has completed, using the following CI command will compare this pull request result against a more recent upstream result:<pre>ci:reevaluate:1397401_11454</pre></p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/c3335394d64c7dca5cacf6024672e858a71f07b7">c3335394d64c7dca5cacf6024672e858a71f07b7</a></p><h4>Upstream Comparison:</h4><p>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/9ff1f1dca89f6c26d2481cb4cc0da2f41bfb81f0">9ff1f1dca89f6c26d2481cb4cc0da2f41bfb81f0</a><br/>Jenkins Build URL: <a href="https://testray.liferay.com/#/project/35392/routines/590307/build/35318812">EE Development Acceptance (master) - 897 - 2024-10-08[04:39:06]</a></p><details><summary><strong>ci:test:content-management-playwright - 9 out of 12 jobs PASSED</strong></summary><div><h4>3 Failed Jobs:</h4><ul><li><a href="https://test-1-39.liferay.com/job/test-portal-acceptance-pullrequest(master)/11454/"><strike>test-portal-acceptance-pullrequest(master)</strike></a></li><li>playwright-js-tomcat90-mysql57-jdk8<ul><li><a href="https://test-1-2.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/426925/">playwright-js-tomcat90-mysql57-jdk8/0/0</a></li><li><a href="https://test-1-9.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/448484/">playwright-js-tomcat90-mysql57-jdk8/1/0</a></li><li><a href="https://test-1-6.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/434819/">playwright-js-tomcat90-mysql57-jdk8/2/0</a></li><li><a href="https://test-1-5.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/372751/">playwright-js-tomcat90-mysql57-jdk8/3/0</a></li><li><a href="https://test-1-9.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/448483/"><strike>playwright-js-tomcat90-mysql57-jdk8/4/0</strike></a></li><li><a href="https://test-1-7.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/381300/">playwright-js-tomcat90-mysql57-jdk8/5/0</a></li><li><a href="https://test-1-8.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/477424/">playwright-js-tomcat90-mysql57-jdk8/6/0</a></li><li><a href="https://test-1-2.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/426924/">playwright-js-tomcat90-mysql57-jdk8/7/0</a></li><li><a href="https://test-1-7.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/381298/"><strike>playwright-js-tomcat90-mysql57-jdk8/8/0</strike></a></li><li><a href="https://test-1-7.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/381299/">playwright-js-tomcat90-mysql57-jdk8/9/0</a></li><li><a href="https://test-1-8.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/477423/">playwright-js-tomcat90-mysql57-jdk8/10/0</a></li></ul></li></ul></div><details><summary><strong>9 Successful Jobs:</strong></summary><ul/></details></details><h5>For more details click <a href="https://test-1-39.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/11454/jenkins-report.html">here</a>.</h5><hr/><h4>This pull contains no unique failures.</h4><hr/><details><summary><strong>Failures in common with <a href="https://test-1-40.liferay.com/job/test-portal-acceptance-upstream-dxp(master)">acceptance upstream results</a> at 9ff1f1dca89f6c26d2481cb4cc0da2f41bfb81f0:</strong></summary><ol><li><div><a href="https://test-1-9.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/448483//consoleText">playwright-js-tomcat90-mysql57-jdk8/4/0</a> - <a href="https://testray.liferay.com/reports/production/logs/2024-10/test-1-39/test-portal-acceptance-pullrequest(master)/11454/playwright-js-tomcat90-mysql57-jdk8/4/0/playwright-report/index.html">Playwright Report</a><ol><li><details><summary><a href="https://test-1-9.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/448483/testReport/content-dashboard-web_content-performance.spec/ts">content-dashboard-web/content-performance.spec.ts</a></summary><div><ol><li><a href="https://test-1-9.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/448483//testReport/content-dashboard-web_content-performance.spec/ts/Displays_empty_state_when_Analytics_Cloud_is_not_connected">Displays empty state when Analytics Cloud is not connected</a></li><li><a href="https://test-1-9.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/448483//testReport/content-dashboard-web_content-performance.spec/ts/Displays_empty_state_when_asset_belongs_to_an_asset_library_with_no_site_connected">Displays empty state when asset belongs to an asset library with no site connected</a></li><li><a href="https://test-1-9.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/448483//testReport/content-dashboard-web_content-performance.spec/ts/Displays_empty_state_when_site_is_not_synced_to_Analytics_Cloud">Displays empty state when site is not synced to Analytics Cloud</a></li></ol></div></details></li></ol></div></li><li><div><a href="https://test-1-7.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/381298//consoleText">playwright-js-tomcat90-mysql57-jdk8/8/0</a> - <a href="https://testray.liferay.com/reports/production/logs/2024-10/test-1-39/test-portal-acceptance-pullrequest(master)/11454/playwright-js-tomcat90-mysql57-jdk8/8/0/playwright-report/index.html">Playwright Report</a><ol><li><details><summary><a href="https://test-1-7.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/381298/testReport/journal-web_journalArticle.spec/ts">journal-web/journalArticle.spec.ts</a></summary><div><ol><li><a href="https://test-1-7.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/381298//testReport/journal-web_journalArticle.spec/ts/Check_alert_message_of_duplicated_friendly_URL_in_french">Check alert message of duplicated friendly URL in french</a></li></ol></div></details></li><li><details><summary><a href="https://test-1-7.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/381298/testReport/journal-web_journalArticleAutosave.spec/ts">journal-web/journalArticleAutosave.spec.ts</a></summary><div><ol><li><a href="https://test-1-7.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/381298//testReport/journal-web_journalArticleAutosave.spec/ts/Empty_option_restores_in_Select_from_List_when_using_undo_redo">Empty option restores in Select from List when using undo/redo</a></li><li><a href="https://test-1-7.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/381298//testReport/journal-web_journalArticleAutosave.spec/ts/Translation_is_removed_when_using_Undo_and_restored_when_using_Redo">Translation is removed when using Undo and restored when using Redo</a></li><li><a href="https://test-1-7.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/381298//testReport/journal-web_journalArticleAutosave.spec/ts/Undo_Redo_buttons_work_with_metadata_fields">Undo/Redo buttons work with metadata fields</a></li><li><a href="https://test-1-7.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/381298//testReport/journal-web_journalArticleAutosave.spec/ts/Web_Content_version__status_and_ID_are_shown_and_updated_after_auto_save">Web Content version, status and ID are shown and updated after auto save</a></li></ol></div></details></li></ol></div></li></ol></details></detai [...]

2024-10-08 16:43 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-39.liferay.com/job/test-portal-acceptance-pullrequest(master)/11454/">test-portal-acceptance-pullrequest(master)#11454</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-39.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/11454/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>content-management-playwright<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-content-management/liferay-portal/pull/5962">liferay-content-management#5962</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/#/project/35392/routines/45357">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/#/project/35392/routines/45357/build/35475990">[master] ci:test:content-management-playwright - gergelyszalay &gt; liferay-content-management - PR#5962 - 2024-10-08[08:11:56]</a><br/></div><div><strong>Testray Build ID:</strong><span></span>35475990<br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-39.liferay.com/job/publish-testray-report/24670/">publish-testray-report#24670</a><br/></div></div>

2024-10-09 12:40 UTC, adolfopa commented
ci:reevaluate:1397401_11454

2024-10-09 12:40 UTC, liferay-continuous-integration commented
CI is reevaluating the build with build ID: `1397401_11454` against the latest valid upstream results.

2024-10-09 12:43 UTC, liferay-continuous-integration commented
<html><p>Previous <code>ci:test:content-management-playwright</code><a href="https://test-1-39.liferay.com/job/test-portal-acceptance-pullrequest(master)/11454">build</a> was unsuccessfully <a href="https://test-1-38.liferay.com/job/test-portal-evaluate-pullrequest/303/">reevaluated</a> against more recent upstream results.</p><h3>:x: ci:test:content-management-playwright - 9 out of 12 jobs passed in 1 hour 29 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/c3335394d64c7dca5cacf6024672e858a71f07b7">c3335394d64c7dca5cacf6024672e858a71f07b7</a></p><h4>Upstream Comparison:</h4><p>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/c3335394d64c7dca5cacf6024672e858a71f07b7">c3335394d64c7dca5cacf6024672e858a71f07b7</a><br/>Jenkins Build URL: <a href="https://testray.liferay.com/#/project/35392/routines/590307/build/35618644">EE Development Acceptance (master) - 898 - 2024-10-08[08:39:59]</a></p><details><summary><strong>ci:test:content-management-playwright - 9 out of 12 jobs PASSED</strong></summary><div><h4>3 Failed Jobs:</h4><ul><li><a href="https://test-1-39.liferay.com/job/test-portal-acceptance-pullrequest(master)/11454"><strike>test-portal-acceptance-pullrequest(master)</strike></a></li><li>playwright-js-tomcat90-mysql57-jdk8<ul><li><a href="https://test-1-2.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/426925/">playwright-js-tomcat90-mysql57-jdk8/0/0</a></li><li><a href="https://test-1-9.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/448484/">playwright-js-tomcat90-mysql57-jdk8/1/0</a></li><li><a href="https://test-1-6.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/434819/">playwright-js-tomcat90-mysql57-jdk8/2/0</a></li><li><a href="https://test-1-5.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/372751/">playwright-js-tomcat90-mysql57-jdk8/3/0</a></li><li><a href="https://test-1-9.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/448483/"><strike>playwright-js-tomcat90-mysql57-jdk8/4/0</strike></a></li><li><a href="https://test-1-7.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/381300/">playwright-js-tomcat90-mysql57-jdk8/5/0</a></li><li><a href="https://test-1-8.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/477424/">playwright-js-tomcat90-mysql57-jdk8/6/0</a></li><li><a href="https://test-1-2.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/426924/">playwright-js-tomcat90-mysql57-jdk8/7/0</a></li><li><a href="https://test-1-7.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/381298/"><strike>playwright-js-tomcat90-mysql57-jdk8/8/0</strike></a></li><li><a href="https://test-1-7.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/381299/">playwright-js-tomcat90-mysql57-jdk8/9/0</a></li><li><a href="https://test-1-8.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/477423/">playwright-js-tomcat90-mysql57-jdk8/10/0</a></li></ul></li></ul></div><details><summary><strong>9 Successful Jobs:</strong></summary><ul/></details></details><h5>For more details click <a href="https://test-1-39.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/11454/jenkins-report.html">here</a>.</h5><hr/><h4>This pull contains no unique failures.</h4><hr/><details><summary><strong>Failures in common with <a href="https://test-1-40.liferay.com/job/test-portal-acceptance-upstream-dxp(master)">acceptance upstream results</a> at c3335394d64c7dca5cacf6024672e858a71f07b7:</strong></summary><ol><li><div><a href="https://test-1-9.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/448483//consoleText">playwright-js-tomcat90-mysql57-jdk8/4/0</a> - <a href="https://testray.liferay.com/reports/production/logs/2024-10/test-1-39/test-portal-acceptance-pullrequest(master)/11454/playwright-js-tomcat90-mysql57-jdk8/4/0/playwright-report/index.html">Playwright Report</a><ol><li><details><summary><a href="https://test-1-9.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/448483/testReport/content-dashboard-web_content-performance.spec/ts">content-dashboard-web/content-performance.spec.ts</a></summary><div><ol><li><a href="https://test-1-9.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/448483//testReport/content-dashboard-web_content-performance.spec/ts/Displays_empty_state_when_Analytics_Cloud_is_not_connected">Displays empty state when Analytics Cloud is not connected</a></li><li><a href="https://test-1-9.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/448483//testReport/content-dashboard-web_content-performance.spec/ts/Displays_empty_state_when_asset_belongs_to_an_asset_library_with_no_site_connected">Displays empty state when asset belongs to an asset library with no site connected</a></li><li><a href="https://test-1-9.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/448483//testReport/content-dashboard-web_content-performance.spec/ts/Displays_empty_state_when_site_is_not_synced_to_Analytics_Cloud">Displays empty state when site is not synced to Analytics Cloud</a></li></ol></div></details></li></ol></div></li><li><div><a href="https://test-1-7.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/381298//consoleText">playwright-js-tomcat90-mysql57-jdk8/8/0</a> - <a href="https://testray.liferay.com/reports/production/logs/2024-10/test-1-39/test-portal-acceptance-pullrequest(master)/11454/playwright-js-tomcat90-mysql57-jdk8/8/0/playwright-report/index.html">Playwright Report</a><ol><li><details><summary><a href="https://test-1-7.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/381298/testReport/journal-web_journalArticle.spec/ts">journal-web/journalArticle.spec.ts</a></summary><div><ol><li><a href="https://test-1-7.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/381298//testReport/journal-web_journalArticle.spec/ts/Check_alert_message_of_duplicated_friendly_URL_in_french">Check alert message of duplicated friendly URL in french</a></li></ol></div></details></li><li><details><summary><a href="https://test-1-7.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/381298/testReport/journal-web_journalArticleAutosave.spec/ts">journal-web/journalArticleAutosave.spec.ts</a></summary><div><ol><li><a href="https://test-1-7.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/381298//testReport/journal-web_journalArticleAutosave.spec/ts/Empty_option_restores_in_Select_from_List_when_using_undo_redo">Empty option restores in Select from List when using undo/redo</a></li><li><a href="https://test-1-7.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/381298//testReport/journal-web_journalArticleAutosave.spec/ts/Translation_is_removed_when_using_Undo_and_restored_when_using_Redo">Translation is removed when using Undo and restored when using Redo</a></li><li><a href="https://test-1-7.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/381298//testReport/journal-web_journalArticleAutosave.spec/ts/Undo_Redo_buttons_work_with_metadata_fields">Undo/Redo buttons work with metadata fields</a></li><li><a href="https://test-1-7.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/381298//testReport/journal-web_journalArticleAutosave.spec/ts/Web_Content_version__status_and_ID_are_shown_and_updated_after_auto_save">Web Content version, status and ID are shown and updated after auto save</a></li></ol></div></details></li></ol></div></li></ol></details></details></html>

2024-10-11 11:43 UTC, ambrinchaudhary requested changes

2024-10-11 11:43 UTC, ambrinchaudhary commented on modules/test/playwright/tests/journal-web/journalArticle.spec.ts
> +		await journalEditArticlePage.titleInput.fill(title);
I think `fillAndClickOutside` will reduce possible flakiness, just like you did in https://github.com/liferay-content-management/liferay-portal/pull/5965/files

2024-10-11 11:43 UTC, ambrinchaudhary commented on modules/test/playwright/tests/journal-web/journalArticle.spec.ts
> +		await journalEditArticlePage.publishButton.click();
I would move all this above steps (from L657) to a function in JournalEditArticlePage, something like `createArticleWithDuplicateField` 🤔 . So the test is more clear.

2024-10-11 11:43 UTC, ambrinchaudhary commented on modules/test/playwright/tests/journal-web/journalArticle.spec.ts
> +		expect(count).toBe(2);
Just `await expect(duplicateFields.count()).toBe(2)`.

2024-10-14 09:27 UTC, gergelyszalay commented
ci:test:sf

2024-10-14 09:27 UTC, gergelyszalay commented
ci:test:content-management-playwright

2024-10-14 09:28 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-32.liferay.com/job/test-portal-source-format/9148/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-32.liferay.com/userContent/jobs/test-portal-source-format/builds/9148/jenkins-report.html">here</a>.</b></p>

2024-10-14 09:31 UTC, liferay-continuous-integration commented
<html><h3>:x: ci:test:sf - 0 out of 1 jobs passed in 4 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/7e00840bb192c75ad3fb9a3be09a6abc8b1bbd42">7e00840bb192c75ad3fb9a3be09a6abc8b1bbd42</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/gergelyszalay/liferay-portal/tree/LPD-38758-master">LPD-38758-master</a><br/>Branch GIT ID: <a href="https://github.com/gergelyszalay/liferay-portal/commit/8c5a37aa95f305f4f7150775cf751bb11bf3414b">8c5a37aa95f305f4f7150775cf751bb11bf3414b</a></p>0 out of 1jobs PASSED<div><h4>1 Failed Jobs:</h4><ul><li><a href="https://test-1-32.liferay.com/job/test-portal-source-format/9148/"><strike>test-portal-source-format</strike></a></li></ul></div><h5>For more details click <a href="https://test-1-32.liferay.com/userContent/jobs/test-portal-source-format/builds/9148/jenkins-report.html">here</a>.</h5><pre>format-source-files:
     [java] java.lang.Exception: Found formatting issue in SHA 8c5a37aa95f305f4f7150775cf751bb11bf3414b
     [java] The commit message is missing a reference to a required JIRA project: BLADE, CLDSVCS, COMMERCE, FACES, IDE, ISSD, ISSITES, LCD, LHC, LOOP, LPD, LPS, LRAC, LRCI, LRDOCS, LRIS, LRQA, LRSD, OAUTH2, POSHI, RELEASE, SYNC, TR. Please verify that the JIRA project keys are specifiedin source-formatter.properties in the liferay-portal repository.
     [java]   at com.liferay.source.formatter.util.JIRAUtil.validateJIRAProjectNames(JIRAUtil.java:62)
     [java]   at com.liferay.source.formatter.SourceFormatter._validateCommitMessages(SourceFormatter.java:1321)
     [java]   at com.liferay.source.formatter.SourceFormatter.format(SourceFormatter.java:338)
     [java]   at com.liferay.source.formatter.SourceFormatter.main(SourceFormatter.java:302)
[stopwatch] [run.batch.test.action: 1:36.129 sec]
     [echo] The following error occurred while executing this line:
     [echo] /opt/dev/projects/github/liferay-portal/portal-impl/build.xml:497: The following error occurred while executing this line:
     [echo] /opt/dev/projects/github/liferay-portal/portal-impl/build.xml:650: Java returned: 1
      [get] Getting: http://test-1-32/job/test-portal-source-format/9148//consoleText
      [get] To: /opt/dev/projects/github/liferay-portal/20241014023052964.txt
   [delete] Deleting: /opt/dev/projects/github/liferay-portal/20241014023052964.txt
  [typedef] Could not load definitions from resource org/apache/maven/artifact/ant/antlib.xml. It could not be found.
  [taskdef] Could not load definitions from resource org/jacoco/ant/antlib.xml. It could not be found.
   [delete] Deleting: /opt/dev/projects/github/liferay-portal/null424370693.properties

merge-test-results:
    [mkdir] Created dir: /opt/dev/projects/github/liferay-portal/test-results
[beanshell] Truncating errors in /opt/dev/projects/github/liferay-portal/portal-impl/test-results/TEST-JenkinsLogAssertTest.xml
[junitreport] Processing /opt/dev/projects/github/liferay-portal/test-results/TESTS-TestSuites.xml to /tmp/null1983655056
[junitreport] Loading stylesheet ile:/opt/java/ant/lib/ant-junit.jar!/org/apache/tools/ant/taskdefs/optional/junit/xsl/junit-frames.xsl
[junitreport] Transform time: 168ms
[junitreport] Deleting: /tmp/null1983655056
     [echo] A report with all the test results can be found at test-results/html/index.html.</pre></details></html>

2024-10-14 09:36 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-32.liferay.com/job/test-portal-source-format/9148/">test-portal-source-format#9148</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-32.liferay.com/userContent/jobs/test-portal-source-format/builds/9148/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-content-management/liferay-portal/pull/5962">liferay-content-management#5962</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/#/project/35392/routines/45357">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/#/project/35392/routines/45357/build/40320976">[master] ci:test:sf - gergelyszalay &gt; liferay-content-management - PR#5962 - 2024-10-14[02:27:43]</a><br/></div><div><strong>Testray Build ID:</strong><span></span>40320976<br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-32.liferay.com/job/publish-testray-report/34486/">publish-testray-report#34486</a><br/></div></div>

2024-10-14 09:41 UTC, ambrinchaudhary approved these changes

2024-10-14 10:30 UTC, gergelyszalay commented
ci:test:sf

2024-10-14 10:32 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-40.liferay.com/job/test-portal-source-format/6428/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-40.liferay.com/userContent/jobs/test-portal-source-format/builds/6428/jenkins-report.html">here</a>.</b></p>

2024-10-14 10:33 UTC, liferay-continuous-integration commented
<html><h3>:x: ci:test:content-management-playwright - 9 out of 12 jobs passed in 1 hour 5 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/7e00840bb192c75ad3fb9a3be09a6abc8b1bbd42">7e00840bb192c75ad3fb9a3be09a6abc8b1bbd42</a></p><h4>Upstream Comparison:</h4><p>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/7e00840bb192c75ad3fb9a3be09a6abc8b1bbd42">7e00840bb192c75ad3fb9a3be09a6abc8b1bbd42</a><br/>Jenkins Build URL: <a href="https://testray.liferay.com/#/project/35392/routines/590307/build/40174165">EE Development Acceptance (master) - 913 - 2024-10-13[16:38:17]</a></p><details><summary><strong>ci:test:content-management-playwright - 9 out of 12 jobs PASSED</strong></summary><div><h4>3 Failed Jobs:</h4><ul><li><a href="https://test-1-37.liferay.com/job/test-portal-acceptance-pullrequest(master)/18221/"><strike>test-portal-acceptance-pullrequest(master)</strike></a></li><li>playwright-js-tomcat90-mysql57<ul><li><a href="https://test-1-37.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1228652/">playwright-js-tomcat90-mysql57/0/0</a></li><li><a href="https://test-1-33.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/939095/">playwright-js-tomcat90-mysql57/1/0</a></li><li><a href="https://test-1-27.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1101524/">playwright-js-tomcat90-mysql57/2/0</a></li><li><a href="https://test-1-28.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/998650/">playwright-js-tomcat90-mysql57/3/0</a></li><li><a href="https://test-1-27.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1101523/"><strike>playwright-js-tomcat90-mysql57/4/0</strike></a></li><li><a href="https://test-1-28.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/998651/">playwright-js-tomcat90-mysql57/5/0</a></li><li><a href="https://test-1-39.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1004850/">playwright-js-tomcat90-mysql57/6/0</a></li><li><a href="https://test-1-32.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1113289/">playwright-js-tomcat90-mysql57/7/0</a></li><li><a href="https://test-1-40.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/760444/"><strike>playwright-js-tomcat90-mysql57/8/0</strike></a></li><li><a href="https://test-1-27.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1101522/">playwright-js-tomcat90-mysql57/9/0</a></li><li><a href="https://test-1-32.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1113290/">playwright-js-tomcat90-mysql57/10/0</a></li></ul></li></ul></div><details><summary><strong>9 Successful Jobs:</strong></summary><ul/></details></details><h5>For more details click <a href="https://test-1-37.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/18221/jenkins-report.html">here</a>.</h5><hr/><h4>This pull contains no unique failures.</h4><hr/><details><summary><strong>Failures in common with <a href="https://test-1-40.liferay.com/job/test-portal-acceptance-upstream-dxp(master)">acceptance upstream results</a> at 7e00840bb192c75ad3fb9a3be09a6abc8b1bbd42:</strong></summary><ol><li><div><a href="https://test-1-27.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1101523//consoleText">playwright-js-tomcat90-mysql57/4/0</a> - <a href="https://testray.liferay.com/reports/production/logs/2024-10/test-1-37/test-portal-acceptance-pullrequest(master)/18221/playwright-js-tomcat90-mysql57/4/0/playwright-report/index.html">Playwright Report</a><ol><li><details><summary><a href="https://test-1-27.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1101523/testReport/content-dashboard-web_content-performance.spec/ts">content-dashboard-web/content-performance.spec.ts</a></summary><div><ol><li><a href="https://test-1-27.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1101523//testReport/content-dashboard-web_content-performance.spec/ts/Displays_empty_state_when_Analytics_Cloud_is_not_connected">Displays empty state when Analytics Cloud is not connected</a></li><li><a href="https://test-1-27.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1101523//testReport/content-dashboard-web_content-performance.spec/ts/Displays_empty_state_when_asset_belongs_to_an_asset_library_with_no_site_connected">Displays empty state when asset belongs to an asset library with no site connected</a></li><li><a href="https://test-1-27.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1101523//testReport/content-dashboard-web_content-performance.spec/ts/Displays_empty_state_when_site_is_not_synced_to_Analytics_Cloud">Displays empty state when site is not synced to Analytics Cloud</a></li></ol></div></details></li></ol></div></li><li><div><a href="https://test-1-40.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/760444//consoleText">playwright-js-tomcat90-mysql57/8/0</a> - <a href="https://testray.liferay.com/reports/production/logs/2024-10/test-1-37/test-portal-acceptance-pullrequest(master)/18221/playwright-js-tomcat90-mysql57/8/0/playwright-report/index.html">Playwright Report</a><ol><li><details><summary><a href="https://test-1-40.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/760444/testReport/journal-web_journalArticle.spec/ts">journal-web/journalArticle.spec.ts</a></summary><div><ol><li><a href="https://test-1-40.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/760444//testReport/journal-web_journalArticle.spec/ts/Check_alert_message_of_duplicated_friendly_URL_in_french">Check alert message of duplicated friendly URL in french</a></li></ol></div></details></li><li><details><summary><a href="https://test-1-40.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/760444/testReport/journal-web_journalArticleAutosave.spec/ts">journal-web/journalArticleAutosave.spec.ts</a></summary><div><ol><li><a href="https://test-1-40.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/760444//testReport/journal-web_journalArticleAutosave.spec/ts/Empty_option_restores_in_Select_from_List_when_using_undo_redo">Empty option restores in Select from List when using undo/redo</a></li><li><a href="https://test-1-40.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/760444//testReport/journal-web_journalArticleAutosave.spec/ts/Translation_is_removed_when_using_Undo_and_restored_when_using_Redo">Translation is removed when using Undo and restored when using Redo</a></li><li><a href="https://test-1-40.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/760444//testReport/journal-web_journalArticleAutosave.spec/ts/Undo_Redo_buttons_work_with_metadata_fields">Undo/Redo buttons work with metadata fields</a></li></ol></div></details></li></ol></div></li></ol></details></details></html>

2024-10-14 10:34 UTC, gergelyszalay commented
ci:test:content-management-playwright

2024-10-14 10:35 UTC, liferay-continuous-integration commented
<html><h3>:x: ci:test:sf - 0 out of 1 jobs passed in 4 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/7e00840bb192c75ad3fb9a3be09a6abc8b1bbd42">7e00840bb192c75ad3fb9a3be09a6abc8b1bbd42</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/gergelyszalay/liferay-portal/tree/LPD-38758-master">LPD-38758-master</a><br/>Branch GIT ID: <a href="https://github.com/gergelyszalay/liferay-portal/commit/9482f9d72f8d9a3d525ce8b193e1bc28671903af">9482f9d72f8d9a3d525ce8b193e1bc28671903af</a></p>0 out of 1jobs PASSED<div><h4>1 Failed Jobs:</h4><ul><li><a href="https://test-1-40.liferay.com/job/test-portal-source-format/6428/"><strike>test-portal-source-format</strike></a></li></ul></div><h5>For more details click <a href="https://test-1-40.liferay.com/userContent/jobs/test-portal-source-format/builds/6428/jenkins-report.html">here</a>.</h5><pre>     [exec] &gt; Task :packageRunCheckFormat
     [exec] yarn run v1.13.0
     [exec] \$ node-scripts check:ci
     [exec] 
     [exec] ⚙️ Running preflight checks...
     [exec] 
     [exec] ⚙️ Checking outdated tsconfig.json files ...
     [exec] 
     [exec] ⚙️ Running TypeScript checks on modified files...
     [exec] ℹ️ A total of 12 CPUs were detected: launching tsc using 12 workers
     [exec] 
     [exec] ⚙️ Running format checks on modified files...
     [exec] 
     [exec]    /opt/dev/projects/github/liferay-portal/modules/test/playwright/tests/journal-web/journalArticle.spec.ts
     [exec]      1:1  error  File has format errors.  (format check)
     [exec]    
     [exec]    ✖ 1 problem (1 error, 0 warnings)
     [exec]    
     [exec]    
     [exec] ❌ CI checks failed.
     [exec] error Command failed with exit code 1.
     [exec] info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
     [exec] 
     [exec] &gt; Task :packageRunCheckFormat FAILED
     [exec] Gradle build finished at 2024-10-14 10:35:11.374.
     [exec] 
     [exec] FAILURE: Build failed with an exception.
     [exec] 
     [exec] * What went wrong:
     [exec] Execution failed for task ':packageRunCheckFormat'.
     [exec] &gt; Process 'command '/opt/dev/projects/github/liferay-portal/build/node/bin/node'' finished with non-zero exit value 1
     [exec] 
     [exec] * Try:
     [exec] &gt; Run with --info or --debug option to get more log output.
     [exec] &gt; Run with --scan to get full insights.
     [exec] &gt; Get more help at https://help.gradle.org.
     [exec] 
     [exec] * Exception is:
     [exec] org.gradle.api.tasks.TaskExecutionException: Execution failed for task ':packageRunCheckFormat'.
     [exec]   at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.lambda\$executeIfValid\$1(ExecuteActionsTaskExecuter.java:148)
     [exec]   at org.gradle.internal.Try\$Failure.ifSuccessfulOrElse(Try.java:282)
     [exec]   at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeIfValid(ExecuteActionsTaskExecuter.java:146)
     [exec]   at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.execute(ExecuteActionsTaskExecuter.java:134)
     [exec]   at org.gradle.api.internal.tasks.execution.FinalizePropertiesTaskExecuter.execute(FinalizePropertiesTaskExecuter.java:46)
     [exec]   at org.gradle.api.internal.tasks.execution.ResolveTaskExecutionModeExecuter.execute(ResolveTaskExecutionModeExecuter.java:51)</pre></details></html>

2024-10-14 10:35 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>content-management-playwright</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-37.liferay.com/job/test-portal-acceptance-pullrequest(master)/18222/">test-portal-acceptance-pullrequest(master)</a></p><p><b>For more details click <a href="https://test-1-37.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/18222/jenkins-report.html">here</a>.</b></p>

2024-10-14 10:36 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-37.liferay.com/job/test-portal-acceptance-pullrequest(master)/18221/">test-portal-acceptance-pullrequest(master)#18221</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-37.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/18221/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>content-management-playwright<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-content-management/liferay-portal/pull/5962">liferay-content-management#5962</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/#/project/35392/routines/45357">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/#/project/35392/routines/45357/build/40386210">[master] ci:test:content-management-playwright - gergelyszalay &gt; liferay-content-management - PR#5962 - 2024-10-14[02:28:06]</a><br/></div><div><strong>Testray Build ID:</strong><span></span>40386210<br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-37.liferay.com/job/publish-testray-report/39463/">publish-testray-report#39463</a><br/></div></div>

2024-10-14 10:37 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-40.liferay.com/job/test-portal-source-format/6428/">test-portal-source-format#6428</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-40.liferay.com/userContent/jobs/test-portal-source-format/builds/6428/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-content-management/liferay-portal/pull/5962">liferay-content-management#5962</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/#/project/35392/routines/45357">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/#/project/35392/routines/45357/build/40386220">[master] ci:test:sf - gergelyszalay &gt; liferay-content-management - PR#5962 - 2024-10-14[03:31:06]</a><br/></div><div><strong>Testray Build ID:</strong><span></span>40386220<br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-40.liferay.com/job/publish-testray-report/24579/">publish-testray-report#24579</a><br/></div></div>

2024-10-14 10:47 UTC, gergelyszalay commented
ci:test:sf

2024-10-14 10:48 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-37.liferay.com/job/test-portal-source-format/10339/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-37.liferay.com/userContent/jobs/test-portal-source-format/builds/10339/jenkins-report.html">here</a>.</b></p>

2024-10-14 10:54 UTC, liferay-continuous-integration commented
<html><h3>:heavy_check_mark: ci:test:sf - 1 out of 1 jobs passed in 7 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/7e00840bb192c75ad3fb9a3be09a6abc8b1bbd42">7e00840bb192c75ad3fb9a3be09a6abc8b1bbd42</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/gergelyszalay/liferay-portal/tree/LPD-38758-master">LPD-38758-master</a><br/>Branch GIT ID: <a href="https://github.com/gergelyszalay/liferay-portal/commit/91c32d67d48ed08deca6407f01ec5c1d892e27d1">91c32d67d48ed08deca6407f01ec5c1d892e27d1</a></p>1 out of 1jobs PASSED<details><summary><strong>1 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-37.liferay.com/job/test-portal-source-format/10339/">test-portal-source-format</a></li></ul></details><h5>For more details click <a href="https://test-1-37.liferay.com/userContent/jobs/test-portal-source-format/builds/10339/jenkins-report.html">here</a>.</h5></details></html>

2024-10-14 10:56 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-37.liferay.com/job/test-portal-source-format/10339/">test-portal-source-format#10339</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-37.liferay.com/userContent/jobs/test-portal-source-format/builds/10339/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-content-management/liferay-portal/pull/5962">liferay-content-management#5962</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/#/project/35392/routines/45357">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/#/project/35392/routines/45357/build/40390726">[master] ci:test:sf - gergelyszalay &gt; liferay-content-management - PR#5962 - 2024-10-14[03:47:22]</a><br/></div><div><strong>Testray Build ID:</strong><span></span>40390726<br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-37.liferay.com/job/publish-testray-report/39465/">publish-testray-report#39465</a><br/></div></div>

2024-10-14 11:02 UTC, gergelyszalay commented
ci:test:content-management-playwright

2024-10-14 11:03 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>content-management-playwright</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-28.liferay.com/job/test-portal-acceptance-pullrequest(master)/11370/">test-portal-acceptance-pullrequest(master)</a></p><p><b>For more details click <a href="https://test-1-28.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/11370/jenkins-report.html">here</a>.</b></p>

2024-10-14 11:47 UTC, liferay-continuous-integration commented
<html><h3>:x: ci:test:content-management-playwright - 9 out of 12 jobs passed in 1 hour 12 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/7e00840bb192c75ad3fb9a3be09a6abc8b1bbd42">7e00840bb192c75ad3fb9a3be09a6abc8b1bbd42</a></p><h4>Upstream Comparison:</h4><p>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/7e00840bb192c75ad3fb9a3be09a6abc8b1bbd42">7e00840bb192c75ad3fb9a3be09a6abc8b1bbd42</a><br/>Jenkins Build URL: <a href="https://testray.liferay.com/#/project/35392/routines/590307/build/40174165">EE Development Acceptance (master) - 913 - 2024-10-13[16:38:17]</a></p><details><summary><strong>ci:test:content-management-playwright - 9 out of 12 jobs PASSED</strong></summary><div><h4>3 Failed Jobs:</h4><ul><li><a href="https://test-1-37.liferay.com/job/test-portal-acceptance-pullrequest(master)/18222/"><strike>test-portal-acceptance-pullrequest(master)</strike></a></li><li>playwright-js-tomcat90-mysql57<ul><li><a href="https://test-1-39.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1004901/">playwright-js-tomcat90-mysql57/0/0</a></li><li><a href="https://test-1-40.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/760506/">playwright-js-tomcat90-mysql57/1/0</a></li><li><a href="https://test-1-37.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1228705/">playwright-js-tomcat90-mysql57/2/0</a></li><li><a href="https://test-1-28.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/998709/">playwright-js-tomcat90-mysql57/3/0</a></li><li><a href="https://test-1-28.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/998708/"><strike>playwright-js-tomcat90-mysql57/4/0</strike></a></li><li><a href="https://test-1-28.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/998711/">playwright-js-tomcat90-mysql57/5/0</a></li><li><a href="https://test-1-37.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1228706/">playwright-js-tomcat90-mysql57/6/0</a></li><li><a href="https://test-1-40.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/760507/">playwright-js-tomcat90-mysql57/7/0</a></li><li><a href="https://test-1-28.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/998710/"><strike>playwright-js-tomcat90-mysql57/8/0</strike></a></li><li><a href="https://test-1-27.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1101574/">playwright-js-tomcat90-mysql57/9/0</a></li><li><a href="https://test-1-32.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1113343/">playwright-js-tomcat90-mysql57/10/0</a></li></ul></li></ul></div><details><summary><strong>9 Successful Jobs:</strong></summary><ul/></details></details><h5>For more details click <a href="https://test-1-37.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/18222/jenkins-report.html">here</a>.</h5><hr/><h4>This pull contains no unique failures.</h4><hr/><details><summary><strong>Failures in common with <a href="https://test-1-40.liferay.com/job/test-portal-acceptance-upstream-dxp(master)">acceptance upstream results</a> at 7e00840bb192c75ad3fb9a3be09a6abc8b1bbd42:</strong></summary><ol><li><div><a href="https://test-1-28.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/998708//consoleText">playwright-js-tomcat90-mysql57/4/0</a> - <a href="https://testray.liferay.com/reports/production/logs/2024-10/test-1-37/test-portal-acceptance-pullrequest(master)/18222/playwright-js-tomcat90-mysql57/4/0/playwright-report/index.html">Playwright Report</a><ol><li><details><summary><a href="https://test-1-28.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/998708/testReport/content-dashboard-web_content-performance.spec/ts">content-dashboard-web/content-performance.spec.ts</a></summary><div><ol><li><a href="https://test-1-28.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/998708//testReport/content-dashboard-web_content-performance.spec/ts/Displays_empty_state_when_Analytics_Cloud_is_not_connected">Displays empty state when Analytics Cloud is not connected</a></li><li><a href="https://test-1-28.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/998708//testReport/content-dashboard-web_content-performance.spec/ts/Displays_empty_state_when_asset_belongs_to_an_asset_library_with_no_site_connected">Displays empty state when asset belongs to an asset library with no site connected</a></li><li><a href="https://test-1-28.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/998708//testReport/content-dashboard-web_content-performance.spec/ts/Displays_empty_state_when_site_is_not_synced_to_Analytics_Cloud">Displays empty state when site is not synced to Analytics Cloud</a></li></ol></div></details></li></ol></div></li><li><div><a href="https://test-1-28.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/998710//consoleText">playwright-js-tomcat90-mysql57/8/0</a> - <a href="https://testray.liferay.com/reports/production/logs/2024-10/test-1-37/test-portal-acceptance-pullrequest(master)/18222/playwright-js-tomcat90-mysql57/8/0/playwright-report/index.html">Playwright Report</a><ol><li><details><summary><a href="https://test-1-28.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/998710/testReport/journal-web_journalArticle.spec/ts">journal-web/journalArticle.spec.ts</a></summary><div><ol><li><a href="https://test-1-28.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/998710//testReport/journal-web_journalArticle.spec/ts/Check_alert_message_of_duplicated_friendly_URL_in_french">Check alert message of duplicated friendly URL in french</a></li></ol></div></details></li><li><details><summary><a href="https://test-1-28.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/998710/testReport/journal-web_journalArticleAutosave.spec/ts">journal-web/journalArticleAutosave.spec.ts</a></summary><div><ol><li><a href="https://test-1-28.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/998710//testReport/journal-web_journalArticleAutosave.spec/ts/Empty_option_restores_in_Select_from_List_when_using_undo_redo">Empty option restores in Select from List when using undo/redo</a></li><li><a href="https://test-1-28.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/998710//testReport/journal-web_journalArticleAutosave.spec/ts/Translation_is_removed_when_using_Undo_and_restored_when_using_Redo">Translation is removed when using Undo and restored when using Redo</a></li><li><a href="https://test-1-28.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/998710//testReport/journal-web_journalArticleAutosave.spec/ts/Undo_Redo_buttons_work_with_metadata_fields">Undo/Redo buttons work with metadata fields</a></li></ol></div></details></li></ol></div></li></ol></details></details></html>

2024-10-14 11:50 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-37.liferay.com/job/test-portal-acceptance-pullrequest(master)/18222/">test-portal-acceptance-pullrequest(master)#18222</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-37.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/18222/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>content-management-playwright<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-content-management/liferay-portal/pull/5962">liferay-content-management#5962</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/#/project/35392/routines/45357">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/#/project/35392/routines/45357/build/40400121">[master] ci:test:content-management-playwright - gergelyszalay &gt; liferay-content-management - PR#5962 - 2024-10-14[03:35:05]</a><br/></div><div><strong>Testray Build ID:</strong><span></span>40400121<br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-37.liferay.com/job/publish-testray-report/39467/">publish-testray-report#39467</a><br/></div></div>

2024-10-14 12:07 UTC, liferay-continuous-integration commented
<html><h3>:x: ci:test:content-management-playwright - 9 out of 12 jobs passed in 1 hour 5 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/7e00840bb192c75ad3fb9a3be09a6abc8b1bbd42">7e00840bb192c75ad3fb9a3be09a6abc8b1bbd42</a></p><h4>Upstream Comparison:</h4><p>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/7e00840bb192c75ad3fb9a3be09a6abc8b1bbd42">7e00840bb192c75ad3fb9a3be09a6abc8b1bbd42</a><br/>Jenkins Build URL: <a href="https://testray.liferay.com/#/project/35392/routines/590307/build/40174165">EE Development Acceptance (master) - 913 - 2024-10-13[16:38:17]</a></p><details><summary><strong>ci:test:content-management-playwright - 9 out of 12 jobs PASSED</strong></summary><div><h4>3 Failed Jobs:</h4><ul><li><a href="https://test-1-28.liferay.com/job/test-portal-acceptance-pullrequest(master)/11370/"><strike>test-portal-acceptance-pullrequest(master)</strike></a></li><li>playwright-js-tomcat90-mysql57<ul><li><a href="https://test-1-40.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/760542/">playwright-js-tomcat90-mysql57/0/0</a></li><li><a href="https://test-1-32.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1113373/">playwright-js-tomcat90-mysql57/1/0</a></li><li><a href="https://test-1-28.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/998738/">playwright-js-tomcat90-mysql57/2/0</a></li><li><a href="https://test-1-39.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1004929/">playwright-js-tomcat90-mysql57/3/0</a></li><li><a href="https://test-1-33.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/939168/"><strike>playwright-js-tomcat90-mysql57/4/0</strike></a></li><li><a href="https://test-1-37.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1228735/">playwright-js-tomcat90-mysql57/5/0</a></li><li><a href="https://test-1-34.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1023792/">playwright-js-tomcat90-mysql57/6/0</a></li><li><a href="https://test-1-33.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/939169/">playwright-js-tomcat90-mysql57/7/0</a></li><li><a href="https://test-1-40.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/760541/"><strike>playwright-js-tomcat90-mysql57/8/0</strike></a></li><li><a href="https://test-1-27.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1101601/">playwright-js-tomcat90-mysql57/9/0</a></li><li><a href="https://test-1-28.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/998739/">playwright-js-tomcat90-mysql57/10/0</a></li></ul></li></ul></div><details><summary><strong>9 Successful Jobs:</strong></summary><ul/></details></details><h5>For more details click <a href="https://test-1-28.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/11370/jenkins-report.html">here</a>.</h5><hr/><h4>This pull contains no unique failures.</h4><hr/><details><summary><strong>Failures in common with <a href="https://test-1-40.liferay.com/job/test-portal-acceptance-upstream-dxp(master)">acceptance upstream results</a> at 7e00840bb192c75ad3fb9a3be09a6abc8b1bbd42:</strong></summary><ol><li><div><a href="https://test-1-33.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/939168//consoleText">playwright-js-tomcat90-mysql57/4/0</a> - <a href="https://testray.liferay.com/reports/production/logs/2024-10/test-1-28/test-portal-acceptance-pullrequest(master)/11370/playwright-js-tomcat90-mysql57/4/0/playwright-report/index.html">Playwright Report</a><ol><li><details><summary><a href="https://test-1-33.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/939168/testReport/content-dashboard-web_content-performance.spec/ts">content-dashboard-web/content-performance.spec.ts</a></summary><div><ol><li><a href="https://test-1-33.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/939168//testReport/content-dashboard-web_content-performance.spec/ts/Displays_empty_state_when_Analytics_Cloud_is_not_connected">Displays empty state when Analytics Cloud is not connected</a></li><li><a href="https://test-1-33.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/939168//testReport/content-dashboard-web_content-performance.spec/ts/Displays_empty_state_when_asset_belongs_to_an_asset_library_with_no_site_connected">Displays empty state when asset belongs to an asset library with no site connected</a></li><li><a href="https://test-1-33.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/939168//testReport/content-dashboard-web_content-performance.spec/ts/Displays_empty_state_when_site_is_not_synced_to_Analytics_Cloud">Displays empty state when site is not synced to Analytics Cloud</a></li></ol></div></details></li></ol></div></li><li><div><a href="https://test-1-40.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/760541//consoleText">playwright-js-tomcat90-mysql57/8/0</a> - <a href="https://testray.liferay.com/reports/production/logs/2024-10/test-1-28/test-portal-acceptance-pullrequest(master)/11370/playwright-js-tomcat90-mysql57/8/0/playwright-report/index.html">Playwright Report</a><ol><li><details><summary><a href="https://test-1-40.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/760541/testReport/journal-web_journalArticle.spec/ts">journal-web/journalArticle.spec.ts</a></summary><div><ol><li><a href="https://test-1-40.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/760541//testReport/journal-web_journalArticle.spec/ts/Check_alert_message_of_duplicated_friendly_URL_in_french">Check alert message of duplicated friendly URL in french</a></li></ol></div></details></li><li><details><summary><a href="https://test-1-40.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/760541/testReport/journal-web_journalArticleAutosave.spec/ts">journal-web/journalArticleAutosave.spec.ts</a></summary><div><ol><li><a href="https://test-1-40.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/760541//testReport/journal-web_journalArticleAutosave.spec/ts/Empty_option_restores_in_Select_from_List_when_using_undo_redo">Empty option restores in Select from List when using undo/redo</a></li><li><a href="https://test-1-40.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/760541//testReport/journal-web_journalArticleAutosave.spec/ts/Translation_is_removed_when_using_Undo_and_restored_when_using_Redo">Translation is removed when using Undo and restored when using Redo</a></li><li><a href="https://test-1-40.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/760541//testReport/journal-web_journalArticleAutosave.spec/ts/Undo_Redo_buttons_work_with_metadata_fields">Undo/Redo buttons work with metadata fields</a></li></ol></div></details></li></ol></div></li></ol></details></details></html>

2024-10-14 12:10 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-28.liferay.com/job/test-portal-acceptance-pullrequest(master)/11370/">test-portal-acceptance-pullrequest(master)#11370</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-28.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/11370/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>content-management-playwright<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-content-management/liferay-portal/pull/5962">liferay-content-management#5962</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/#/project/35392/routines/45357">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/#/project/35392/routines/45357/build/40408323">[master] ci:test:content-management-playwright - gergelyszalay &gt; liferay-content-management - PR#5962 - 2024-10-14[04:02:42]</a><br/></div><div><strong>Testray Build ID:</strong><span></span>40408323<br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-28.liferay.com/job/publish-testray-report/24899/">publish-testray-report#24899</a><br/></div></div>

2024-10-14 12:13 UTC, liferay-continuous-integration commented
CI is automatically triggering the following test suites:
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**relevant**
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**sf**
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**stable**

The pull request will automatically be forwarded to the user `brianchandotcom` If the following test suites pass:
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**relevant**
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**sf**
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**stable**

2024-10-14 12:13 UTC, liferay-continuous-integration commented
Skipping previously passed test suites:
- `ci:test:relevant`
- `ci:test:sf`
- `ci:test:stable`

2024-10-14 12:14 UTC, liferay-continuous-integration commented
All required test suite(s) passed.
Forwarding pull request to `brianchandotcom`.
[Console](https://test-1-33.liferay.com/job/forward-pullrequest/792//consoleFull)

2024-10-14 12:15 UTC, closed without merging