LPD-38760 Cannot display image added through the item selector to a blogs entry
liferay-content-management/liferay-portal pull request #5979
Opened 2024-10-10 13:55 UTC by marcogalluzzi

# What is this trying to solve?

https://liferay.atlassian.net/browse/LPD-38760

An image inserted into a Blog entry from the URL tab of the image selector is not visible.

# How am I fixing it?

Removing an entry added to the CSS when this bug was fixed: 

* Jira issue: [Copy and pasted images appear twice in blogs entry alloy editor](https://liferay.atlassian.net/browse/LPS-195447) 
* PR: [LPS-195447 Remove image added by ckeditor](https://github.com/liferay-frontend/liferay-portal/pull/3680/commits/77826f3b24e5f52a4c8a2d6270f5b6fdf7dc9e9a)

I've manually checked that reverting this change didn't make the old bug to reproduce.

# How can you verify that it works?

Run POSHI test:
`ant -f build-test.xml run-selenium-test -Dtest.class=ItemSelector#CanAddBlogsImageViaURL`

2024-10-10 13:55 UTC, liferay-continuous-integration commented
CI is automatically triggering the following test suites:
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**sf**

2024-10-10 13:57 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-35.liferay.com/job/test-portal-source-format/3102/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-35.liferay.com/userContent/jobs/test-portal-source-format/builds/3102/jenkins-report.html">here</a>.</b></p>

2024-10-11 11:36 UTC, boton requested changes
Sadly this solution reopens the [Copy and pasted images appear twice in blogs entry alloy editor](https://liferay.atlassian.net/browse/LPS-195447) issue.

![image](https://github.com/user-attachments/assets/56f865d0-793b-48a4-9cce-86136ff5557e)

https://github.com/user-attachments/assets/f5747d9b-084a-4423-8fec-ac56da989e0e

2024-10-11 12:02 UTC, marcogalluzzi commented
Closing this PR because the fix reopens another bug :disappointed: [Copy and pasted images appear twice in blogs entry alloy editor](https://liferay.atlassian.net/browse/LPS-195447)

2024-10-11 12:02 UTC, closed without merging