LPD-42067 , LPD-41947 | Migration of tags.testcases
liferay-content-management/liferay-portal pull request #6114
Opened 2024-11-20 13:07 UTC by NemethNorbert

# What is this trying to solve?
[LPD-42067](https://liferay.atlassian.net/browse/LPD-42067)
[LPD-41947](https://liferay.atlassian.net/browse/LPD-41947)

Migration of poshi testcases from [Tags.testcase](https://github.com/liferay-content-management/liferay-portal/blob/master/portal-web/test/functional/com/liferay/portalweb/tests/enduser/wem/asset/tags/Tags.testcase)

# Motivation

Reduce the number of functional tests to the minimum, while maintaining maximum test coverage. There are other testcases that will end up as backend unit tests, while some will be discarded. The removal of Tags.testcase will be included in the final pull of the migration.

# How can you verify that it works?

Run the tests

2024-11-20 13:14 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-10.liferay.com/job/test-portal-source-format/5790/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-10.liferay.com/userContent/jobs/test-portal-source-format/builds/5790/jenkins-report.html">here</a>.</b></p>

2024-11-20 13:23 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-10.liferay.com/job/test-portal-source-format/5790/">test-portal-source-format#5790</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-10.liferay.com/userContent/jobs/test-portal-source-format/builds/5790/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-content-management/liferay-portal/pull/6114">liferay-content-management#6114</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/#/project/35392/routines/45357">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/#/project/35392/routines/45357/build/73189256">[master] ci:test:sf - NemethNorbert &gt; liferay-content-management - PR#6114 - 2024-11-20[05:12:52]</a><br/></div><div><strong>Testray Build ID:</strong><span></span>73189256<br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-10.liferay.com/job/publish-testray-report/6383/">publish-testray-report#6383</a><br/></div></div>

2024-11-20 17:01 UTC, boton commented
ci:test:content-management-playwright

2024-11-20 17:01 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>content-management-playwright</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-38.liferay.com/job/test-portal-acceptance-pullrequest(master)/11459/">test-portal-acceptance-pullrequest(master)</a></p><p><b>For more details click <a href="https://test-1-38.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/11459/jenkins-report.html">here</a>.</b></p>

2024-11-20 17:23 UTC, boton requested changes
## Tested on local (a couple of times)
Nice job with the first two but the third one fails on my local
![image](https://github.com/user-attachments/assets/26fe5058-5521-4010-8448-a2adcf3290a9)



I leave small comments asking for changes (one for myself)

2024-11-20 17:23 UTC, boton commented on modules/test/playwright/tests/asset-tags-admin-web/pages/TagsEditPage.ts
> +	}
I know I wrote this, but now I think it's better to use the add button to navigate to edit. 
Of course, I take care of it.

2024-11-20 17:23 UTC, boton commented on modules/test/playwright/tests/asset-tags-admin-web/tags.spec.ts
> +test('The user can Merge tags', async ({
It's only a small detail but 'User can Merge tags' sounds better to me like the previous tests.

2024-11-20 17:23 UTC, boton commented on modules/test/playwright/tests/asset-tags-admin-web/tags.spec.ts
> +	});
We can wrap this in a step https://playwright.dev/docs/api/class-test#test-step instead of adding the comment. 
I think it adds value to the test.

2024-11-20 17:23 UTC, boton commented on modules/test/playwright/tests/asset-tags-admin-web/pages/TagsAdminPage.ts
> +			.getByRole('row', {name: 'Select ' + title + ' 0 Show Actions'})
Can we simplify this? Is it not working just with the title? .getByRole('row', {name: title})

2024-11-20 17:23 UTC, boton commented on modules/test/playwright/tests/asset-tags-admin-web/pages/TagsAdminPage.ts
> +		await this.page.getByRole('menuitem', {name: 'Edit'}).click();
Can we use `clickAndExpectToBeVisible` to avoid flakiness?

2024-11-20 17:23 UTC, boton commented on modules/test/playwright/tests/asset-tags-admin-web/pages/TagsAdminPage.ts
> +		await this.page.getByRole('menuitem', {name: 'Merge'}).click();
Can we use `clickAndExpectToBeVisible` to avoid flakiness?

2024-11-20 17:23 UTC, boton commented on modules/test/playwright/tests/asset-tags-admin-web/pages/TagsAdminPage.ts
> +		await this.page.getByRole('menuitem', {name: 'Delete'}).click();
Can we use `clickAndExpectToBeVisible` to avoid flakiness?

2024-11-20 18:15 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-38.liferay.com/job/test-portal-acceptance-pullrequest(master)/11459/">test-portal-acceptance-pullrequest(master)#11459</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-38.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/11459/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>content-management-playwright<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-content-management/liferay-portal/pull/6114">liferay-content-management#6114</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/#/project/35392/routines/45357">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/#/project/35392/routines/45357/build/73474019">[master] ci:test:content-management-playwright - NemethNorbert &gt; liferay-content-management - PR#6114 - 2024-11-20[09:01:21]</a><br/></div><div><strong>Testray Build ID:</strong><span></span>73474019<br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-38.liferay.com/job/publish-testray-report/23666/">publish-testray-report#23666</a><br/></div></div>

2024-11-21 12:30 UTC, boton commented
I pushed [this commit](https://github.com/liferay-content-management/liferay-portal/pull/6114/commits/a97f9a36e44bf3f550810bb2afc047ab968c1359) to resolve https://github.com/liferay-content-management/liferay-portal/pull/6114#discussion_r1850697792

## The test is working in local
![image](https://github.com/user-attachments/assets/b78e80a5-380d-4265-b3d4-54ddff6b1772)

2024-11-21 13:42 UTC, NemethNorbert commented
Hey @boton ,

I pushed up the requested changes and modified the flaky test.

<img width="912" alt="Screenshot 2024-11-21 at 14 39 12" src="https://github.com/user-attachments/assets/6fe66586-8fa4-47bf-af12-d712e8947e75">

2024-11-21 17:56 UTC, boton commented
ci:test:content-management-playwright

2024-11-21 17:56 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>content-management-playwright</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-26.liferay.com/job/test-portal-acceptance-pullrequest(master)/14210/">test-portal-acceptance-pullrequest(master)</a></p><p><b>For more details click <a href="https://test-1-26.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/14210/jenkins-report.html">here</a>.</b></p>

2024-11-21 18:58 UTC, liferay-continuous-integration commented
<html><h3>:heavy_check_mark: ci:test:content-management-playwright - 15 out of 15 jobs passed in 1 hour 2 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/88f5c1e61324636dcb345e3358adef5e7589a5e8">88f5c1e61324636dcb345e3358adef5e7589a5e8</a></p><h4>Upstream Comparison:</h4><p>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/38b3c3240bb57be3dbac5cedd723d103302f4ae9">38b3c3240bb57be3dbac5cedd723d103302f4ae9</a><br/>Jenkins Build URL: <a href="https://testray.liferay.com/#/project/35392/routines/590307/build/73880898">EE Development Acceptance (master) - 1033 - 2024-11-20[16:42:00]</a></p><details><summary><strong>ci:test:content-management-playwright - 15 out of 15 jobs PASSED</strong></summary><details><summary><strong>15 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-26.liferay.com/job/test-portal-acceptance-pullrequest(master)/14210/">test-portal-acceptance-pullrequest(master)</a></li><li>playwright-js-tomcat90-mysql57<ul><li><a href="https://test-1-32.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1141999/">playwright-js-tomcat90-mysql57/0/0</a></li><li><a href="https://test-1-27.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1129965/">playwright-js-tomcat90-mysql57/1/0</a></li><li><a href="https://test-1-39.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1033311/">playwright-js-tomcat90-mysql57/2/0</a></li><li><a href="https://test-1-40.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/790328/">playwright-js-tomcat90-mysql57/3/0</a></li><li><a href="https://test-1-27.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1129964/">playwright-js-tomcat90-mysql57/4/0</a></li><li><a href="https://test-1-9.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/464368/">playwright-js-tomcat90-mysql57/5/0</a></li><li><a href="https://test-1-10.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/445599/">playwright-js-tomcat90-mysql57/6/0</a></li><li><a href="https://test-1-29.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1028346/">playwright-js-tomcat90-mysql57/7/0</a></li><li><a href="https://test-1-33.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/963504/">playwright-js-tomcat90-mysql57/8/0</a></li><li><a href="https://test-1-37.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1261261/">playwright-js-tomcat90-mysql57/9/0</a></li><li><a href="https://test-1-28.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1027634/">playwright-js-tomcat90-mysql57/10/0</a></li><li><a href="https://test-1-38.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/983885/">playwright-js-tomcat90-mysql57/11/0</a></li><li><a href="https://test-1-35.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/979218/">playwright-js-tomcat90-mysql57/12/0</a></li><li><a href="https://test-1-34.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1046256/">playwright-js-tomcat90-mysql57/13/0</a></li></ul></li></ul></details></details><h5>For more details click <a href="https://test-1-26.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/14210/jenkins-report.html">here</a>.</h5></details></html>

2024-11-21 19:01 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-26.liferay.com/job/test-portal-acceptance-pullrequest(master)/14210/">test-portal-acceptance-pullrequest(master)#14210</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-26.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/14210/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>content-management-playwright<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-content-management/liferay-portal/pull/6114">liferay-content-management#6114</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/#/project/35392/routines/45357">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/#/project/35392/routines/45357/build/74471843">[master] ci:test:content-management-playwright - NemethNorbert &gt; liferay-content-management - PR#6114 - 2024-11-21[09:56:27]</a><br/></div><div><strong>Testray Build ID:</strong><span></span>74471843<br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-26.liferay.com/job/publish-testray-report/33074/">publish-testray-report#33074</a><br/></div></div>

2024-11-22 13:05 UTC, boton requested changes
LGTM but little details like I need to change the project config name :D

2024-11-22 13:40 UTC, boton approved these changes
I fixed my previous comments 

## Tested locally
![image](https://github.com/user-attachments/assets/113b61ea-ea0b-4632-bc19-1da85c6387b6)

2024-11-22 13:40 UTC, boton commented
ci:test:content-management-playwright

2024-11-22 13:41 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>content-management-playwright</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-40.liferay.com/job/test-portal-acceptance-pullrequest(master)/11878/">test-portal-acceptance-pullrequest(master)</a></p><p><b>For more details click <a href="https://test-1-40.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/11878/jenkins-report.html">here</a>.</b></p>

2024-11-22 13:48 UTC, liferay-continuous-integration commented
<html><h3>:x: ci:test:content-management-playwright - 0 out of 1 jobs passed in 8 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/38072c8dd20cb75551606707642c4b7d77a3ca5a">38072c8dd20cb75551606707642c4b7d77a3ca5a</a></p><h4>Upstream Comparison:</h4><p>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/98457fab147b2d80667dfea44b015932e0ea67f3">98457fab147b2d80667dfea44b015932e0ea67f3</a><br/>Jenkins Build URL: <a href="https://testray.liferay.com/#/project/35392/routines/590307/build/74699032">EE Development Acceptance (master) - 1035 - 2024-11-21[12:42:29]</a></p><details><summary><strong>ci:test:content-management-playwright - 0 out of 1 jobs PASSED</strong></summary><div><h4>1 Failed Jobs:</h4><ul><li><a href="https://test-1-40.liferay.com/job/test-portal-acceptance-pullrequest(master)/11878/"><strike>test-portal-acceptance-pullrequest(master)</strike></a></li></ul></div></details><h5>For more details click <a href="https://test-1-40.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/11878/jenkins-report.html">here</a>.</h5><hr/><h4>Failures unique to this pull:</h4><ol><li><div><h5><a href="https://test-1-40.liferay.com/job/test-portal-acceptance-pullrequest(master)/11878/">test-portal-acceptance-pullrequest(master)</a></h5><div><h6>Job Results:</h6><p>0 Jobs Passed.<br/>1 Job Failed.</p></div><pre>Started by remote host 172.16.168.126
Running as SYSTEM
[EnvInject] - Loading node environment variables.
Building remotely on test-1-40-67 (slave-1) in workspace /opt/dev/projects/github/liferay-jenkins-ee
[liferay-jenkins-ee] \$ /bin/bash -e -x /tmp/jenkins9974940350465003475.sh
+ echo 'Initialize Jenkins slave node.'
Initialize Jenkins slave node.
+ cd /opt/dev/projects/github/liferay-jenkins-ee
+ curl -o ./_common.sh http://mirrors-no-cache.lax.liferay.com/github.com/liferay/liferay-jenkins-ee/_common.sh
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100 19663  100 19663    0     0  2530k      0 --:--:-- --:--:-- --:--:-- 2743k
+ source ./_common.sh
++ MAX_THREADS=1
++ [[ test-1-40-67.lax.liferay.com =~ cloud-.* ]]
++ [[ test-1-40-67 slave-1 =~ .*win.* ]]
++ ROOT_DIR=
++ GIT_REPOSITORIES_ROOT_DIR=/opt/dev/projects/github
++ JENKINS_REPO_PATH=/opt/dev/projects/github/liferay-jenkins-ee
+++ cat /opt/dev/projects/github/liferay-jenkins-ee/git-directories.json
++ GIT_DIRECTORIES_JSON_CONTENT='[
  \{
    "branch": "master",
    "name": "alloy-ui",
    "repository": "alloy-ui",
    "type": "mounted"
  \},
  \{
    "branch": "7.0.x",
    "name": "com-liferay-osb-asah-private",
    "repository": "com-liferay-osb-asah-private",
    "type": "mounted"
  \},
  \{
    "branch": "master",
    "name": "liferay-binaries-cache-2017",
    "repository": "liferay-binaries-cache-2017",
    "type": "shared-mounted"
  \},
  \{
    "branch": "master",
    "name": "liferay-binaries-cache-2020",
    "repository": "liferay-binaries-cache-2020",
    "type": "shared-mounted"
  \},
  \{
    "branch": "master",
    "name": "liferay-blade-samples",
    "repository": "liferay-blade-samples",
    "type": "mounted"
  \},
  \{
    "branch": "master",
    "name": "liferay-docker",
    "repository": "liferay-docker",
    "type": "mounted"
  \},
  \{
    "branch": "master",
    "name": "liferay-faces-alloy",
    "repository": "liferay-faces-alloy",
    "type": "mounted"
  \},
  \{
    "branch": "master",
    "name": "liferay-faces-bridge-impl",
    "repository": "liferay-faces-bridge-impl",
    "type": "mounted"
  \},
  \{
    "branch": "master",
    "name": "liferay-faces-portal",
    "repository": "liferay-faces-portal",
    "type": "mounted"
  \},
  \{
    "branch": "master",
    "name": "liferay-faces-showcase",
    "repository": "liferay-faces-showcase",
    "type": "mounted"
  \},
  \{
    "branch": "master",</pre></div></li></ol><h4>For upstream results, click <a href="https://test-1-40.liferay.com/job/test-portal-acceptance-upstream-dxp(master)">here</a>.</h4></details></html>

2024-11-25 12:55 UTC, NemethNorbert commented
ci:test:content-management-playwright

2024-11-25 12:55 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>content-management-playwright</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-38.liferay.com/job/test-portal-acceptance-pullrequest(master)/11483/">test-portal-acceptance-pullrequest(master)</a></p><p><b>For more details click <a href="https://test-1-38.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/11483/jenkins-report.html">here</a>.</b></p>

2024-11-25 13:58 UTC, liferay-continuous-integration commented
<html><h3>:x: ci:test:content-management-playwright - 13 out of 15 jobs passed in 1 hour 3 minutes</h3><details><summary>Click here for more details.</summary><br/><p>This pull is eligible for <a href="https://grow.liferay.com/share/CI+liferay-continuous-integration+GitHub+Commands#General-Commands">reevaluation</a>. When this <a href="https://test-1-40.liferay.com/job/test-portal-acceptance-upstream-dxp(master)/1039">upstream build</a> has completed, using the following CI command will compare this pull request result against a more recent upstream result:<pre>ci:reevaluate:1387401_11483</pre></p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/1e5c8feef2f04064dd757ede41a1c1a0e3352f43">1e5c8feef2f04064dd757ede41a1c1a0e3352f43</a></p><h4>Upstream Comparison:</h4><p>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/19205cad1dc8c046c1e7da61e2700069e2ee7cff">19205cad1dc8c046c1e7da61e2700069e2ee7cff</a><br/>Jenkins Build URL: <a href="https://testray.liferay.com/#/project/35392/routines/590307/build/75923041">EE Development Acceptance (master) - 1038 - 2024-11-23[12:36:39]</a></p><details><summary><strong>ci:test:content-management-playwright - 13 out of 15 jobs PASSED</strong></summary><div><h4>2 Failed Jobs:</h4><ul><li><a href="https://test-1-38.liferay.com/job/test-portal-acceptance-pullrequest(master)/11483/"><strike>test-portal-acceptance-pullrequest(master)</strike></a></li><li>playwright-js-tomcat90-mysql57<ul><li><a href="https://test-1-31.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1147021/">playwright-js-tomcat90-mysql57/0/0</a></li><li><a href="https://test-1-27.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1131285/">playwright-js-tomcat90-mysql57/1/0</a></li><li><a href="https://test-1-40.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/791752/">playwright-js-tomcat90-mysql57/2/0</a></li><li><a href="https://test-1-29.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1029376/">playwright-js-tomcat90-mysql57/3/0</a></li><li><a href="https://test-1-27.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1131284/">playwright-js-tomcat90-mysql57/4/0</a></li><li><a href="https://test-1-40.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/791753/">playwright-js-tomcat90-mysql57/5/0</a></li><li><a href="https://test-1-31.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1147020/">playwright-js-tomcat90-mysql57/6/0</a></li><li><a href="https://test-1-32.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1143159/">playwright-js-tomcat90-mysql57/7/0</a></li><li><a href="https://test-1-29.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1029377/"><strike>playwright-js-tomcat90-mysql57/8/0</strike></a></li><li><a href="https://test-1-33.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/964356/">playwright-js-tomcat90-mysql57/9/0</a></li><li><a href="https://test-1-29.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1029375/">playwright-js-tomcat90-mysql57/10/0</a></li><li><a href="https://test-1-32.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1143160/">playwright-js-tomcat90-mysql57/11/0</a></li><li><a href="https://test-1-38.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/985092/">playwright-js-tomcat90-mysql57/12/0</a></li><li><a href="https://test-1-27.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1131286/">playwright-js-tomcat90-mysql57/13/0</a></li></ul></li></ul></div><details><summary><strong>13 Successful Jobs:</strong></summary><ul/></details></details><h5>For more details click <a href="https://test-1-38.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/11483/jenkins-report.html">here</a>.</h5><hr/><h4>Failures unique to this pull:</h4><ol><li><div><a href="https://test-1-29.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1029377//consoleText">playwright-js-tomcat90-mysql57/8/0</a> - <a href="https://storage.cloud.google.com/testray-results/2024-11/test-1-38/test-portal-acceptance-pullrequest(master)/11483/playwright-js-tomcat90-mysql57/8/0/playwright-report/index.html">Playwright Report</a><ol><li><details><summary><a href="https://test-1-29.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1029377/testReport/knowledge-base-web_knowledge-base-web.spec/ts">knowledge-base-web/knowledge-base-web.spec.ts</a></summary><div><ol><li><a href="https://test-1-29.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1029377//testReport/knowledge-base-web_knowledge-base-web.spec/ts/LPD_23801_error_message_is_shown_when_an_admin_user_tries_to_publish_an_article_that_an_admin_is_currently_editing">LPD-23801 error message is shown when an admin user tries to publish an article that an admin is currently editing</a></li></ol></div></details></li></ol></div></li></ol><h4>For upstream results, click <a href="https://test-1-40.liferay.com/job/test-portal-acceptance-upstream-dxp(master)">here</a>.</h4></details></html>

2024-11-25 14:00 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-38.liferay.com/job/test-portal-acceptance-pullrequest(master)/11483/">test-portal-acceptance-pullrequest(master)#11483</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-38.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/11483/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>content-management-playwright<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-content-management/liferay-portal/pull/6114">liferay-content-management#6114</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/#/project/35392/routines/45357">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/#/project/35392/routines/45357/build/76473971">[master] ci:test:content-management-playwright - NemethNorbert &gt; liferay-content-management - PR#6114 - 2024-11-25[04:55:26]</a><br/></div><div><strong>Testray Build ID:</strong><span></span>76473971<br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-38.liferay.com/job/publish-testray-report/23733/">publish-testray-report#23733</a><br/></div></div>

2024-11-25 14:12 UTC, NemethNorbert commented
ci:reevaluate:1387401_11483

2024-11-25 14:12 UTC, liferay-continuous-integration commented
CI is reevaluating the build with build ID: `1387401_11483` against the latest valid upstream results.

2024-11-25 14:13 UTC, liferay-continuous-integration commented
<p>Unable to <a href="https://test-1-27.liferay.com/job/test-portal-evaluate-pullrequest/252/">reevaluate</a> previous pull request result. Please wait for this <a href="https://test-1-40.liferay.com/job/test-portal-acceptance-upstream-dxp(master)/1039">acceptance upstream build</a> to complete, and attempt reevaluation again with the CI command:
<pre>ci:reevaluate:1387401_11483</pre></p>

2024-11-26 11:22 UTC, NemethNorbert commented
ci:reevaluate:1387401_11483

2024-11-26 11:22 UTC, liferay-continuous-integration commented
CI is reevaluating the build with build ID: `1387401_11483` against the latest valid upstream results.

2024-11-26 11:24 UTC, liferay-continuous-integration commented
<html><p>Previous <code>ci:test:content-management-playwright</code><a href="https://test-1-38.liferay.com/job/test-portal-acceptance-pullrequest(master)/11483">build</a> was unsuccessfully <a href="https://test-1-40.liferay.com/job/test-portal-evaluate-pullrequest/124/">reevaluated</a> against more recent upstream results.</p><h3>:x: ci:test:content-management-playwright - 13 out of 15 jobs passed in 1 hour 3 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/1e5c8feef2f04064dd757ede41a1c1a0e3352f43">1e5c8feef2f04064dd757ede41a1c1a0e3352f43</a></p><h4>Upstream Comparison:</h4><p>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/1e5c8feef2f04064dd757ede41a1c1a0e3352f43">1e5c8feef2f04064dd757ede41a1c1a0e3352f43</a><br/>Jenkins Build URL: <a href="https://testray.liferay.com/#/project/35392/routines/590307/build/76715285">EE Development Acceptance (master) - 1039 - 2024-11-25[04:37:16]</a></p><details><summary><strong>ci:test:content-management-playwright - 13 out of 15 jobs PASSED</strong></summary><div><h4>2 Failed Jobs:</h4><ul><li><a href="https://test-1-38.liferay.com/job/test-portal-acceptance-pullrequest(master)/11483"><strike>test-portal-acceptance-pullrequest(master)</strike></a></li><li>playwright-js-tomcat90-mysql57<ul><li><a href="https://test-1-31.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1147021/">playwright-js-tomcat90-mysql57/0/0</a></li><li><a href="https://test-1-27.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1131285/">playwright-js-tomcat90-mysql57/1/0</a></li><li><a href="https://test-1-40.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/791752/">playwright-js-tomcat90-mysql57/2/0</a></li><li><a href="https://test-1-29.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1029376/">playwright-js-tomcat90-mysql57/3/0</a></li><li><a href="https://test-1-27.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1131284/">playwright-js-tomcat90-mysql57/4/0</a></li><li><a href="https://test-1-40.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/791753/">playwright-js-tomcat90-mysql57/5/0</a></li><li><a href="https://test-1-31.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1147020/">playwright-js-tomcat90-mysql57/6/0</a></li><li><a href="https://test-1-32.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1143159/">playwright-js-tomcat90-mysql57/7/0</a></li><li><a href="https://test-1-29.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1029377/"><strike>playwright-js-tomcat90-mysql57/8/0</strike></a></li><li><a href="https://test-1-33.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/964356/">playwright-js-tomcat90-mysql57/9/0</a></li><li><a href="https://test-1-29.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1029375/">playwright-js-tomcat90-mysql57/10/0</a></li><li><a href="https://test-1-32.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1143160/">playwright-js-tomcat90-mysql57/11/0</a></li><li><a href="https://test-1-38.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/985092/">playwright-js-tomcat90-mysql57/12/0</a></li><li><a href="https://test-1-27.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1131286/">playwright-js-tomcat90-mysql57/13/0</a></li></ul></li></ul></div><details><summary><strong>13 Successful Jobs:</strong></summary><ul/></details></details><h5>For more details click <a href="https://test-1-38.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/11483/jenkins-report.html">here</a>.</h5><hr/><h4>Failures unique to this pull:</h4><ol><li><div><a href="https://test-1-29.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1029377//consoleText">playwright-js-tomcat90-mysql57/8/0</a> - <a href="https://storage.cloud.google.com/testray-results/2024-11/test-1-38/test-portal-acceptance-pullrequest(master)/11483/playwright-js-tomcat90-mysql57/8/0/playwright-report/index.html">Playwright Report</a><ol><li><details><summary><a href="https://test-1-29.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1029377/testReport/knowledge-base-web_knowledge-base-web.spec/ts">knowledge-base-web/knowledge-base-web.spec.ts</a></summary><div><ol><li><a href="https://test-1-29.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1029377//testReport/knowledge-base-web_knowledge-base-web.spec/ts/LPD_23801_error_message_is_shown_when_an_admin_user_tries_to_publish_an_article_that_an_admin_is_currently_editing">LPD-23801 error message is shown when an admin user tries to publish an article that an admin is currently editing</a></li></ol></div></details></li></ol></div></li></ol><h4>For upstream results, click <a href="https://test-1-40.liferay.com/job/test-portal-acceptance-upstream-dxp(master)">here</a>.</h4></details></html>

2024-11-26 15:43 UTC, NemethNorbert commented
The failing test is irrelevant as it is not the one I added.

2024-11-26 16:10 UTC, NemethNorbert commented on modules/test/playwright/tests/asset-tags-admin-web/pages/TagsAdminPage.ts
> +		await clickAndExpectToBeVisible({
I simplified Delete and Merge

2024-11-26 16:10 UTC, NemethNorbert commented
ci:test:content-management-playwright

2024-11-26 16:11 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>content-management-playwright</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-38.liferay.com/job/test-portal-acceptance-pullrequest(master)/11504/">test-portal-acceptance-pullrequest(master)</a></p><p><b>For more details click <a href="https://test-1-38.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/11504/jenkins-report.html">here</a>.</b></p>

2024-11-26 16:11 UTC, DiegoHu97 approved these changes
LGTM!

2024-11-26 17:08 UTC, liferay-continuous-integration commented
<html><h3>:heavy_check_mark: ci:test:content-management-playwright - 15 out of 15 jobs passed in 57 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/80ec2855f6e41bb82ba0125a7b7bef558743dfcf">80ec2855f6e41bb82ba0125a7b7bef558743dfcf</a></p><h4>Upstream Comparison:</h4><p>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/145785fc889b041bcf1e01243caba466377f14b4">145785fc889b041bcf1e01243caba466377f14b4</a><br/>Jenkins Build URL: <a href="https://testray.liferay.com/#/project/35392/routines/590307/build/77344626">EE Development Acceptance (master) - 1042 - 2024-11-25[16:36:34]</a></p><details><summary><strong>ci:test:content-management-playwright - 15 out of 15 jobs PASSED</strong></summary><details><summary><strong>15 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-38.liferay.com/job/test-portal-acceptance-pullrequest(master)/11504/">test-portal-acceptance-pullrequest(master)</a></li><li>playwright-js-tomcat90-mysql57<ul><li><a href="https://test-1-32.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1144392/">playwright-js-tomcat90-mysql57/0/0</a></li><li><a href="https://test-1-33.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/965411/">playwright-js-tomcat90-mysql57/1/0</a></li><li><a href="https://test-1-10.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/446523/">playwright-js-tomcat90-mysql57/2/0</a></li><li><a href="https://test-1-33.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/965410/">playwright-js-tomcat90-mysql57/3/0</a></li><li><a href="https://test-1-33.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/965409/">playwright-js-tomcat90-mysql57/4/0</a></li><li><a href="https://test-1-27.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1132650/">playwright-js-tomcat90-mysql57/5/0</a></li><li><a href="https://test-1-31.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1148163/">playwright-js-tomcat90-mysql57/6/0</a></li><li><a href="https://test-1-40.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/793115/">playwright-js-tomcat90-mysql57/7/0</a></li><li><a href="https://test-1-32.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1144391/">playwright-js-tomcat90-mysql57/8/0</a></li><li><a href="https://test-1-33.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/965412/">playwright-js-tomcat90-mysql57/9/0</a></li><li><a href="https://test-1-30.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1095406/">playwright-js-tomcat90-mysql57/10/0</a></li><li><a href="https://test-1-40.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/793116/">playwright-js-tomcat90-mysql57/11/0</a></li><li><a href="https://test-1-28.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1030240/">playwright-js-tomcat90-mysql57/12/0</a></li><li><a href="https://test-1-6.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/450609/">playwright-js-tomcat90-mysql57/13/0</a></li></ul></li></ul></details></details><h5>For more details click <a href="https://test-1-38.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/11504/jenkins-report.html">here</a>.</h5></details></html>

2024-11-26 17:14 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-38.liferay.com/job/test-portal-acceptance-pullrequest(master)/11504/">test-portal-acceptance-pullrequest(master)#11504</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-38.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/11504/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>content-management-playwright<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-content-management/liferay-portal/pull/6114">liferay-content-management#6114</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/#/project/35392/routines/45357">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/#/project/35392/routines/45357/build/77825568">[master] ci:test:content-management-playwright - NemethNorbert &gt; liferay-content-management - PR#6114 - 2024-11-26[08:11:09]</a><br/></div><div><strong>Testray Build ID:</strong><span></span>77825568<br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-38.liferay.com/job/publish-testray-report/23778/">publish-testray-report#23778</a><br/></div></div>

2024-11-26 17:22 UTC, NemethNorbert commented
ci:forward

2024-11-26 17:23 UTC, liferay-continuous-integration commented
CI is automatically triggering the following test suites:
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**relevant**
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**sf**
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**stable**

The pull request will automatically be forwarded to the user `brianchandotcom` If the following test suites pass:
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**relevant**
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**sf**
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**stable**

2024-11-26 17:24 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-3.liferay.com/job/test-portal-source-format/8309/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-3.liferay.com/userContent/jobs/test-portal-source-format/builds/8309/jenkins-report.html">here</a>.</b></p>

2024-11-26 17:29 UTC, liferay-continuous-integration commented
<html><h3>:x: ci:test:sf - 0 out of 1 jobs passed in 6 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/80ec2855f6e41bb82ba0125a7b7bef558743dfcf">80ec2855f6e41bb82ba0125a7b7bef558743dfcf</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/NemethNorbert/liferay-portal/tree/boton-LPD-42067_TEST_PW_add-new-tags-playwright-project">boton-LPD-42067_TEST_PW_add-new-tags-playwright-project</a><br/>Branch GIT ID: <a href="https://github.com/NemethNorbert/liferay-portal/commit/be67b2b8868c7f9ba57442259c8bf4ca2d25a4c5">be67b2b8868c7f9ba57442259c8bf4ca2d25a4c5</a></p>0 out of 1jobs PASSED<div><h4>1 Failed Jobs:</h4><ul><li><a href="https://test-1-3.liferay.com/job/test-portal-source-format/8309/"><strike>test-portal-source-format</strike></a></li></ul></div><h5>For more details click <a href="https://test-1-3.liferay.com/userContent/jobs/test-portal-source-format/builds/8309/jenkins-report.html">here</a>.</h5><pre>     [exec] &gt; Task :packageRunCheckFormat
     [exec] yarn run v1.13.0
     [exec] \$ node-scripts check:ci
     [exec] 
     [exec] ?????? Running preflight checks...
     [exec] 
     [exec] ?????? Checking outdated tsconfig.json files ...
     [exec] 
     [exec] ?????? Running TypeScript checks on modified files...
     [exec] ?????? A total of 8 CPUs were detected: launching tsc using 8 workers
     [exec] 
     [exec] ?????? Running format checks on modified files...
     [exec]    /opt/dev/projects/github/liferay-portal/modules/test/playwright/tests/asset-tags-admin-web/pages/TagsAdminPage.ts
     [exec]      1:1  error  File has format errors.  (format check)
     [exec]    
     [exec]    ??? 1 problem (1 error, 0 warnings)
     [exec]    
     [exec]    
     [exec] ??? CI checks failed.
     [exec] error Command failed with exit code 1.
     [exec] info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
     [exec] 
     [exec] &gt; Task :packageRunCheckFormat FAILED
     [exec] 
     [exec] 
     [exec] FAILURE: Build failed with an exception.
     [exec] Gradle build finished at 2024-11-26 17:28:30.285.
     [exec] 
     [exec] * What went wrong:
     [exec] Execution failed for task ':packageRunCheckFormat'.
     [exec] &gt; Process 'command '/opt/dev/projects/github/liferay-portal/build/node/bin/node'' finished with non-zero exit value 1
     [exec] 
     [exec] * Try:
     [exec] &gt; Run with --info or --debug option to get more log output.
     [exec] &gt; Run with --scan to get full insights.
     [exec] &gt; Get more help at https://help.gradle.org.
     [exec] 
     [exec] * Exception is:
     [exec] org.gradle.api.tasks.TaskExecutionException: Execution failed for task ':packageRunCheckFormat'.
     [exec]   at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.lambda\$executeIfValid\$1(ExecuteActionsTaskExecuter.java:148)
     [exec]   at org.gradle.internal.Try\$Failure.ifSuccessfulOrElse(Try.java:282)
     [exec]   at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeIfValid(ExecuteActionsTaskExecuter.java:146)
     [exec]   at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.execute(ExecuteActionsTaskExecuter.java:134)
     [exec]   at org.gradle.api.internal.tasks.execution.FinalizePropertiesTaskExecuter.execute(FinalizePropertiesTaskExecuter.java:46)</pre></details></html>

2024-11-26 17:31 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-3.liferay.com/job/test-portal-source-format/8309/">test-portal-source-format#8309</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-3.liferay.com/userContent/jobs/test-portal-source-format/builds/8309/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-content-management/liferay-portal/pull/6114">liferay-content-management#6114</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/#/project/35392/routines/45357">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/#/project/35392/routines/45357/build/77835397">[master] ci:test:sf - NemethNorbert &gt; liferay-content-management - PR#6114 - 2024-11-26[09:23:25]</a><br/></div><div><strong>Testray Build ID:</strong><span></span>77835397<br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-3.liferay.com/job/publish-testray-report/4683/">publish-testray-report#4683</a><br/></div></div>

2024-11-26 17:34 UTC, NemethNorbert commented
ci:forward

2024-11-26 17:39 UTC, liferay-continuous-integration commented
<html><h3>:heavy_check_mark: ci:test:sf - 1 out of 1 jobs passed in 5 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/80ec2855f6e41bb82ba0125a7b7bef558743dfcf">80ec2855f6e41bb82ba0125a7b7bef558743dfcf</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/NemethNorbert/liferay-portal/tree/boton-LPD-42067_TEST_PW_add-new-tags-playwright-project">boton-LPD-42067_TEST_PW_add-new-tags-playwright-project</a><br/>Branch GIT ID: <a href="https://github.com/NemethNorbert/liferay-portal/commit/a8ab5be9c799282feb5df527ae0701c9f178c6ca">a8ab5be9c799282feb5df527ae0701c9f178c6ca</a></p>1 out of 1jobs PASSED<details><summary><strong>1 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-40.liferay.com/job/test-portal-source-format/6821/">test-portal-source-format</a></li></ul></details><h5>For more details click <a href="https://test-1-40.liferay.com/userContent/jobs/test-portal-source-format/builds/6821/jenkins-report.html">here</a>.</h5></details></html>

2024-11-26 17:40 UTC, closed without merging

2024-11-26 17:40 UTC, liferay-continuous-integration commented
Pull request has been successfully forwarded to  https://github.com/brianchandotcom/liferay-portal/pull/156466
[Console](https://test-1-40.liferay.com/job/test-portal-source-format/6821//consoleFull)

2024-11-26 17:45 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-40.liferay.com/job/test-portal-source-format/6821/">test-portal-source-format#6821</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-40.liferay.com/userContent/jobs/test-portal-source-format/builds/6821/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-content-management/liferay-portal/pull/6114">liferay-content-management#6114</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/#/project/35392/routines/45357">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/#/project/35392/routines/45357/build/77840676">[master] ci:test:sf - NemethNorbert &gt; liferay-content-management - PR#6114 - 2024-11-26[09:34:20]</a><br/></div><div><strong>Testray Build ID:</strong><span></span>77840676<br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-40.liferay.com/job/publish-testray-report/26025/">publish-testray-report#26025</a><br/></div></div>

2024-11-26 17:52 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>relevant</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-40.liferay.com/job/test-portal-acceptance-pullrequest(master)/11947/">test-portal-acceptance-pullrequest(master)</a></p><p><b>For more details click <a href="https://test-1-40.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/11947/jenkins-report.html">here</a>.</b></p>

2024-11-26 17:54 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>relevant</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-28.liferay.com/job/test-portal-acceptance-pullrequest(master)/11839/">test-portal-acceptance-pullrequest(master)</a></p><p><b>For more details click <a href="https://test-1-28.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/11839/jenkins-report.html">here</a>.</b></p>

2024-11-26 17:56 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-40.liferay.com/job/test-portal-acceptance-pullrequest(master)/11947/">test-portal-acceptance-pullrequest(master)#11947</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-40.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/11947/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>relevant<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-content-management/liferay-portal/pull/6114">liferay-content-management#6114</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/#/project/35392/routines/45357">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/#/project/35392/routines/45357/build/77851438">[master] ci:test:relevant - NemethNorbert &gt; liferay-content-management - PR#6114 - 2024-11-26[09:51:41]</a><br/></div><div><strong>Testray Build ID:</strong><span></span>77851438<br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-40.liferay.com/job/publish-testray-report/26026/">publish-testray-report#26026</a><br/></div></div>

2024-11-26 17:58 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-28.liferay.com/job/test-portal-acceptance-pullrequest(master)/11839/">test-portal-acceptance-pullrequest(master)#11839</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-28.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/11839/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>relevant<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-content-management/liferay-portal/pull/6114">liferay-content-management#6114</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/#/project/35392/routines/45357">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/#/project/35392/routines/45357/build/77852002">[master] ci:test:relevant - NemethNorbert &gt; liferay-content-management - PR#6114 - 2024-11-26[09:53:38]</a><br/></div><div><strong>Testray Build ID:</strong><span></span>77852002<br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-28.liferay.com/job/publish-testray-report/25930/">publish-testray-report#25930</a><br/></div></div>