LPD-42569 Create playwright asset-categories-admin-web project
liferay-content-management/liferay-portal pull request #6125
Opened 2024-11-25 19:35 UTC by DiegoHu97

# What is this trying to solve?

[Link to ticket]()

# How am I fixing it?

# How can I test it?

2024-11-25 19:35 UTC, liferay-continuous-integration commented
CI is automatically triggering the following test suites:
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**sf**

2024-11-25 19:36 UTC, DiegoHu97 commented
ci:test:content-management-playwright

2024-11-25 19:36 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>content-management-playwright</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-37.liferay.com/job/test-portal-acceptance-pullrequest(master)/18837/">test-portal-acceptance-pullrequest(master)</a></p><p><b>For more details click <a href="https://test-1-37.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/18837/jenkins-report.html">here</a>.</b></p>

2024-11-25 19:37 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-35.liferay.com/job/test-portal-source-format/3146/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-35.liferay.com/userContent/jobs/test-portal-source-format/builds/3146/jenkins-report.html">here</a>.</b></p>

2024-11-25 19:40 UTC, liferay-continuous-integration commented
<html><h3>:x: ci:test:sf - 0 out of 1 jobs passed in 4 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/bd8371069d06f7c3738f40f1d92732529e6a4692">bd8371069d06f7c3738f40f1d92732529e6a4692</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/DiegoHu97/liferay-portal/tree/LPD-42569_categories_tests">LPD-42569_categories_tests</a><br/>Branch GIT ID: <a href="https://github.com/DiegoHu97/liferay-portal/commit/5a3c0300bcb98aa9355dd75e6749bb03d7fe924d">5a3c0300bcb98aa9355dd75e6749bb03d7fe924d</a></p>0 out of 1jobs PASSED<div><h4>1 Failed Jobs:</h4><ul><li><a href="https://test-1-35.liferay.com/job/test-portal-source-format/3146/"><strike>test-portal-source-format</strike></a></li></ul></div><h5>For more details click <a href="https://test-1-35.liferay.com/userContent/jobs/test-portal-source-format/builds/3146/jenkins-report.html">here</a>.</h5><pre>     [exec] &gt; Task :packageRunCheckFormat
     [exec] yarn run v1.13.0
     [exec] \$ node-scripts check:ci
     [exec] 
     [exec] ⚙️ Running preflight checks...
     [exec] 
     [exec] ⚙️ Checking outdated tsconfig.json files ...
     [exec] 
     [exec] ⚙️ Running TypeScript checks on modified files...
     [exec] ℹ️ A total of 12 CPUs were detected: launching tsc using 12 workers
     [exec] 
     [exec] ⚙️ Running format checks on modified files...
     [exec]    /opt/dev/projects/github/liferay-portal/modules/test/playwright/tests/asset-categories-admin-web/categoriesAdmin.spec.ts
     [exec]      10:9  error  'clickAndExpectToBeVisible' is defined but never used. Allowed unused vars must match /^_/u.  @typescript-eslint/no-unused-vars
     [exec]      11:8  error  'getRandomString' is defined but never used. Allowed unused vars must match /^_/u.  @typescript-eslint/no-unused-vars
     [exec]    
     [exec]    ✖ 2 problems (2 errors, 0 warnings)
     [exec]    
     [exec]    /opt/dev/projects/github/liferay-portal/modules/test/playwright/tests/asset-categories-admin-web/fixtures/assetCategoriesAdminPagesTest.ts
     [exec]      1:1  error  File has format errors.  (format check)
     [exec]    
     [exec]    ✖ 1 problem (1 error, 0 warnings)
     [exec]    
     [exec]    /opt/dev/projects/github/liferay-portal/modules/test/playwright/tests/asset-categories-admin-web/pages/VocabulariesEditPage.ts
     [exec]      8:9  error  'clickAndExpectToBeVisible' is defined but never used. Allowed unused vars must match /^_/u.  @typescript-eslint/no-unused-vars
     [exec]      10:9  error  'AssetCategoriesAdminPage' is defined but never used. Allowed unused vars must match /^_/u.  @typescript-eslint/no-unused-vars
     [exec]    
     [exec]    ✖ 2 problems (2 errors, 0 warnings)
     [exec]    
     [exec]    
     [exec] ❌ CI checks failed.
     [exec] error Command failed with exit code 1.
     [exec] info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
     [exec] 
     [exec] &gt; Task :packageRunCheckFormat FAILED
     [exec] Gradle build finished at 2024-11-25 19:39:55.543.
     [exec] 
     [exec] 
     [exec] FAILURE: Build failed with an exception.
     [exec] 
     [exec] * What went wrong:
     [exec] Execution failed for task ':packageRunCheckFormat'.
     [exec] &gt; Process 'command '/opt/dev/projects/github/liferay-portal/build/node/bin/node'' finished with non-zero exit value 1
     [exec] 
     [exec] * Try:</pre></details></html>

2024-11-25 19:41 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-35.liferay.com/job/test-portal-source-format/3146/">test-portal-source-format#3146</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-35.liferay.com/userContent/jobs/test-portal-source-format/builds/3146/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-content-management/liferay-portal/pull/6125">liferay-content-management#6125</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/#/project/35392/routines/45357">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/#/project/35392/routines/45357/build/76845438">[master] ci:test:sf - DiegoHu97 &gt; liferay-content-management - PR#6125 - 2024-11-25[11:35:45]</a><br/></div><div><strong>Testray Build ID:</strong><span></span>76845438<br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-35.liferay.com/job/publish-testray-report/14031/">publish-testray-report#14031</a><br/></div></div>

2024-11-25 19:46 UTC, DiegoHu97 commented
ci:test:sf

2024-11-25 19:51 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-29.liferay.com/job/test-portal-source-format/6020/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-29.liferay.com/userContent/jobs/test-portal-source-format/builds/6020/jenkins-report.html">here</a>.</b></p>

2024-11-25 19:55 UTC, liferay-continuous-integration commented
<html><h3>:heavy_check_mark: ci:test:sf - 1 out of 1 jobs passed in 5 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/bd8371069d06f7c3738f40f1d92732529e6a4692">bd8371069d06f7c3738f40f1d92732529e6a4692</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/DiegoHu97/liferay-portal/tree/LPD-42569_categories_tests">LPD-42569_categories_tests</a><br/>Branch GIT ID: <a href="https://github.com/DiegoHu97/liferay-portal/commit/ba3d11b2c8ab606b568ba604c25a1bcf0ce9e653">ba3d11b2c8ab606b568ba604c25a1bcf0ce9e653</a></p>1 out of 1jobs PASSED<details><summary><strong>1 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-29.liferay.com/job/test-portal-source-format/6020/">test-portal-source-format</a></li></ul></details><h5>For more details click <a href="https://test-1-29.liferay.com/userContent/jobs/test-portal-source-format/builds/6020/jenkins-report.html">here</a>.</h5></details></html>

2024-11-25 19:57 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-29.liferay.com/job/test-portal-source-format/6020/">test-portal-source-format#6020</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-29.liferay.com/userContent/jobs/test-portal-source-format/builds/6020/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-content-management/liferay-portal/pull/6125">liferay-content-management#6125</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/#/project/35392/routines/45357">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/#/project/35392/routines/45357/build/76860322">[master] ci:test:sf - DiegoHu97 &gt; liferay-content-management - PR#6125 - 2024-11-25[11:50:17]</a><br/></div><div><strong>Testray Build ID:</strong><span></span>76860322<br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-29.liferay.com/job/publish-testray-report/23839/">publish-testray-report#23839</a><br/></div></div>

2024-11-25 20:55 UTC, liferay-continuous-integration commented
<html><h3>:heavy_check_mark: ci:test:content-management-playwright - 14 out of 14 jobs passed in 1 hour 19 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/bd8371069d06f7c3738f40f1d92732529e6a4692">bd8371069d06f7c3738f40f1d92732529e6a4692</a></p><h4>Upstream Comparison:</h4><p>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/87c6985160fac31ac94e95ea4b9fc4f2add2775f">87c6985160fac31ac94e95ea4b9fc4f2add2775f</a><br/>Jenkins Build URL: <a href="https://testray.liferay.com/#/project/35392/routines/590307/build/76851059">EE Development Acceptance (master) - 1040 - 2024-11-25[08:36:33]</a></p><details><summary><strong>ci:test:content-management-playwright - 14 out of 14 jobs PASSED</strong></summary><details><summary><strong>14 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-37.liferay.com/job/test-portal-acceptance-pullrequest(master)/18837/">test-portal-acceptance-pullrequest(master)</a></li><li>playwright-js-tomcat90-mysql57<ul><li><a href="https://test-1-37.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1263039/">playwright-js-tomcat90-mysql57/0/0</a></li><li><a href="https://test-1-29.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1029708/">playwright-js-tomcat90-mysql57/1/0</a></li><li><a href="https://test-1-40.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/792210/">playwright-js-tomcat90-mysql57/2/0</a></li><li><a href="https://test-1-32.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1143531/">playwright-js-tomcat90-mysql57/3/0</a></li><li><a href="https://test-1-29.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1029707/">playwright-js-tomcat90-mysql57/4/0</a></li><li><a href="https://test-1-29.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1029709/">playwright-js-tomcat90-mysql57/5/0</a></li><li><a href="https://test-1-32.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1143533/">playwright-js-tomcat90-mysql57/6/0</a></li><li><a href="https://test-1-40.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/792211/">playwright-js-tomcat90-mysql57/7/0</a></li><li><a href="https://test-1-32.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1143532/">playwright-js-tomcat90-mysql57/8/0</a></li><li><a href="https://test-1-36.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1069937/">playwright-js-tomcat90-mysql57/9/0</a></li><li><a href="https://test-1-40.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/792212/">playwright-js-tomcat90-mysql57/10/0</a></li><li><a href="https://test-1-40.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/792213/">playwright-js-tomcat90-mysql57/11/0</a></li><li><a href="https://test-1-7.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/395035/">playwright-js-tomcat90-mysql57/12/0</a></li></ul></li></ul></details></details><h5>For more details click <a href="https://test-1-37.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/18837/jenkins-report.html">here</a>.</h5></details></html>

2024-11-25 20:58 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-37.liferay.com/job/test-portal-acceptance-pullrequest(master)/18837/">test-portal-acceptance-pullrequest(master)#18837</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-37.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/18837/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>content-management-playwright<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-content-management/liferay-portal/pull/6125">liferay-content-management#6125</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/#/project/35392/routines/45357">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/#/project/35392/routines/45357/build/76926640">[master] ci:test:content-management-playwright - DiegoHu97 &gt; liferay-content-management - PR#6125 - 2024-11-25[11:36:21]</a><br/></div><div><strong>Testray Build ID:</strong><span></span>76926640<br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-37.liferay.com/job/publish-testray-report/40746/">publish-testray-report#40746</a><br/></div></div>

2024-11-27 12:28 UTC, boton commented
ci:test:content-management-playwright

2024-11-27 12:28 UTC, boton commented
ci:stop

2024-11-27 13:46 UTC, liferay-continuous-integration commented
<html><h3>:heavy_check_mark: ci:test:content-management-playwright - 15 out of 15 jobs passed in 1 hour</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/d1f383ebee9055db957044f08bc289bd8a8131d7">d1f383ebee9055db957044f08bc289bd8a8131d7</a></p><h4>Upstream Comparison:</h4><p>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/255d7b8d9e411a51a994b1adc4d1d415d47518ec">255d7b8d9e411a51a994b1adc4d1d415d47518ec</a><br/>Jenkins Build URL: <a href="https://testray.liferay.com/#/project/35392/routines/590307/build/78687707">EE Development Acceptance (master) - 1046 - 2024-11-26[20:44:21]</a></p><details><summary><strong>ci:test:content-management-playwright - 15 out of 15 jobs PASSED</strong></summary><details><summary><strong>15 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-34.liferay.com/job/test-portal-acceptance-pullrequest(master)/6956/">test-portal-acceptance-pullrequest(master)</a></li><li>playwright-js-tomcat90-mysql57<ul><li><a href="https://test-1-29.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1031083/">playwright-js-tomcat90-mysql57/0/0</a></li><li><a href="https://test-1-37.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1264719/">playwright-js-tomcat90-mysql57/1/0</a></li><li><a href="https://test-1-34.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1048302/">playwright-js-tomcat90-mysql57/2/0</a></li><li><a href="https://test-1-29.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1031084/">playwright-js-tomcat90-mysql57/3/0</a></li><li><a href="https://test-1-26.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1241406/">playwright-js-tomcat90-mysql57/4/0</a></li><li><a href="https://test-1-37.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1264720/">playwright-js-tomcat90-mysql57/5/0</a></li><li><a href="https://test-1-32.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1144990/">playwright-js-tomcat90-mysql57/6/0</a></li><li><a href="https://test-1-35.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/981537/">playwright-js-tomcat90-mysql57/7/0</a></li><li><a href="https://test-1-40.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/793810/">playwright-js-tomcat90-mysql57/8/0</a></li><li><a href="https://test-1-28.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1030848/">playwright-js-tomcat90-mysql57/9/0</a></li><li><a href="https://test-1-31.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1148666/">playwright-js-tomcat90-mysql57/10/0</a></li><li><a href="https://test-1-37.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1264722/">playwright-js-tomcat90-mysql57/11/0</a></li><li><a href="https://test-1-25.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/724246/">playwright-js-tomcat90-mysql57/12/0</a></li><li><a href="https://test-1-37.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1264721/">playwright-js-tomcat90-mysql57/13/0</a></li></ul></li></ul></details></details><h5>For more details click <a href="https://test-1-34.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/6956/jenkins-report.html">here</a>.</h5></details></html>

2024-11-27 13:48 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-34.liferay.com/job/test-portal-acceptance-pullrequest(master)/6956/">test-portal-acceptance-pullrequest(master)#6956</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-34.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/6956/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>content-management-playwright<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-content-management/liferay-portal/pull/6125">liferay-content-management#6125</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/#/project/35392/routines/45357">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/#/project/35392/routines/45357/build/78926940">[master] ci:test:content-management-playwright - DiegoHu97 &gt; liferay-content-management - PR#6125 - 2024-11-27[04:45:18]</a><br/></div><div><strong>Testray Build ID:</strong><span></span>78926940<br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-34.liferay.com/job/publish-testray-report/25617/">publish-testray-report#25617</a><br/></div></div>

2024-11-27 14:06 UTC, boton requested changes
Nice work here @DiegoHu97 

I left some comments and I realized that we are not adding the project to the CI

https://liferay.atlassian.net/wiki/spaces/ENGLIMA/pages/3365044312/WIP+How+to+Add+a+New+Playwright+Module
![image](https://github.com/user-attachments/assets/8b3d0418-eecb-4a2f-ab99-b7147ae953cb)

2024-11-27 16:12 UTC, DiegoHu97 commented
Hey @boton Thanks for the review, i've just updated the PR 
![image](https://github.com/user-attachments/assets/c55d00e0-a589-462e-a1a6-072e7fc126c5)

2024-11-27 16:12 UTC, DiegoHu97 commented
ci:test:sf

2024-11-27 16:13 UTC, DiegoHu97 commented
ci:test:content-management-playwright

2024-11-27 16:13 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>content-management-playwright</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-29.liferay.com/job/test-portal-acceptance-pullrequest(master)/10759/">test-portal-acceptance-pullrequest(master)</a></p><p><b>For more details click <a href="https://test-1-29.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/10759/jenkins-report.html">here</a>.</b></p>

2024-11-27 16:14 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-29.liferay.com/job/test-portal-source-format/6026/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-29.liferay.com/userContent/jobs/test-portal-source-format/builds/6026/jenkins-report.html">here</a>.</b></p>

2024-11-27 16:17 UTC, liferay-continuous-integration commented
<html><h3>:heavy_check_mark: ci:test:sf - 1 out of 1 jobs passed in 5 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/f3bb3de3dbd03fc0211539a9b993df5515a5bef2">f3bb3de3dbd03fc0211539a9b993df5515a5bef2</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/DiegoHu97/liferay-portal/tree/LPD-42569_categories_tests">LPD-42569_categories_tests</a><br/>Branch GIT ID: <a href="https://github.com/DiegoHu97/liferay-portal/commit/7cd4e145f4dc057585d2c0b6363e96184ad0226c">7cd4e145f4dc057585d2c0b6363e96184ad0226c</a></p>1 out of 1jobs PASSED<details><summary><strong>1 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-29.liferay.com/job/test-portal-source-format/6026/">test-portal-source-format</a></li></ul></details><h5>For more details click <a href="https://test-1-29.liferay.com/userContent/jobs/test-portal-source-format/builds/6026/jenkins-report.html">here</a>.</h5></details></html>

2024-11-27 17:05 UTC, liferay-continuous-integration commented
<html><h3>:heavy_check_mark: ci:test:content-management-playwright - 16 out of 16 jobs passed in 52 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/f3bb3de3dbd03fc0211539a9b993df5515a5bef2">f3bb3de3dbd03fc0211539a9b993df5515a5bef2</a></p><h4>Upstream Comparison:</h4><p>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/d1f383ebee9055db957044f08bc289bd8a8131d7">d1f383ebee9055db957044f08bc289bd8a8131d7</a><br/>Jenkins Build URL: <a href="https://testray.liferay.com/#/project/35392/routines/590307/build/79052481">EE Development Acceptance (master) - 1047 - 2024-11-27[04:41:51]</a></p><details><summary><strong>ci:test:content-management-playwright - 16 out of 16 jobs PASSED</strong></summary><details><summary><strong>16 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-29.liferay.com/job/test-portal-acceptance-pullrequest(master)/10759/">test-portal-acceptance-pullrequest(master)</a></li><li>playwright-js-tomcat90-mysql57<ul><li><a href="https://test-1-33.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/966143/">playwright-js-tomcat90-mysql57/0/0</a></li><li><a href="https://test-1-37.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1264920/">playwright-js-tomcat90-mysql57/1/0</a></li><li><a href="https://test-1-27.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1133464/">playwright-js-tomcat90-mysql57/2/0</a></li><li><a href="https://test-1-9.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/465914/">playwright-js-tomcat90-mysql57/3/0</a></li><li><a href="https://test-1-9.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/465912/">playwright-js-tomcat90-mysql57/4/0</a></li><li><a href="https://test-1-27.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1133465/">playwright-js-tomcat90-mysql57/5/0</a></li><li><a href="https://test-1-37.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1264921/">playwright-js-tomcat90-mysql57/6/0</a></li><li><a href="https://test-1-36.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1071390/">playwright-js-tomcat90-mysql57/7/0</a></li><li><a href="https://test-1-9.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/465913/">playwright-js-tomcat90-mysql57/8/0</a></li><li><a href="https://test-1-28.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1031015/">playwright-js-tomcat90-mysql57/9/0</a></li><li><a href="https://test-1-39.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1036685/">playwright-js-tomcat90-mysql57/10/0</a></li><li><a href="https://test-1-30.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1096148/">playwright-js-tomcat90-mysql57/11/0</a></li><li><a href="https://test-1-34.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1048439/">playwright-js-tomcat90-mysql57/12/0</a></li><li><a href="https://test-1-9.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/465915/">playwright-js-tomcat90-mysql57/13/0</a></li><li><a href="https://test-1-29.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1031237/">playwright-js-tomcat90-mysql57/14/0</a></li></ul></li></ul></details></details><h5>For more details click <a href="https://test-1-29.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/10759/jenkins-report.html">here</a>.</h5></details></html>

2024-11-27 17:09 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-29.liferay.com/job/test-portal-acceptance-pullrequest(master)/10759/">test-portal-acceptance-pullrequest(master)#10759</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-29.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/10759/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>content-management-playwright<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-content-management/liferay-portal/pull/6125">liferay-content-management#6125</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/#/project/35392/routines/45357">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/#/project/35392/routines/45357/build/79245431">[master] ci:test:content-management-playwright - DiegoHu97 &gt; liferay-content-management - PR#6125 - 2024-11-27[08:13:11]</a><br/></div><div><strong>Testray Build ID:</strong><span></span>79245431<br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-29.liferay.com/job/publish-testray-report/23864/">publish-testray-report#23864</a><br/></div></div>

2024-11-28 09:15 UTC, boton approved these changes
LGTM!

Only I left a small change can you please sort the configs projects array

2024-11-28 09:15 UTC, boton commented on modules/test/playwright/playwright.config.ts
> +		assetCategoriesAdminWebConfig,
Sort this, move `assetCategoriesAdminWebConfig` between

```js
		assetPublisherWebConfig,
		assetTagsAdminWebConfig,
```

2024-11-28 10:45 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-40.liferay.com/job/test-portal-source-format/6855/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-40.liferay.com/userContent/jobs/test-portal-source-format/builds/6855/jenkins-report.html">here</a>.</b></p>

2024-11-28 10:49 UTC, liferay-continuous-integration commented
<html><h3>:heavy_check_mark: ci:test:sf - 1 out of 1 jobs passed in 4 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/d71b1f9b8213c734d0eca46f7ca2f0c6e6ecbc45">d71b1f9b8213c734d0eca46f7ca2f0c6e6ecbc45</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/DiegoHu97/liferay-portal/tree/LPD-42569_categories_tests">LPD-42569_categories_tests</a><br/>Branch GIT ID: <a href="https://github.com/DiegoHu97/liferay-portal/commit/5c0ca59257368027f63e18425f5aa85aaf7e876e">5c0ca59257368027f63e18425f5aa85aaf7e876e</a></p>1 out of 1jobs PASSED<details><summary><strong>1 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-40.liferay.com/job/test-portal-source-format/6855/">test-portal-source-format</a></li></ul></details><h5>For more details click <a href="https://test-1-40.liferay.com/userContent/jobs/test-portal-source-format/builds/6855/jenkins-report.html">here</a>.</h5></details></html>

2024-11-28 10:50 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-40.liferay.com/job/test-portal-source-format/6855/">test-portal-source-format#6855</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-40.liferay.com/userContent/jobs/test-portal-source-format/builds/6855/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-content-management/liferay-portal/pull/6125">liferay-content-management#6125</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/#/project/35392/routines/45357">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/#/project/35392/routines/45357/build/79910173">[master] ci:test:sf - DiegoHu97 &gt; liferay-content-management - PR#6125 - 2024-11-28[02:44:35]</a><br/></div><div><strong>Testray Build ID:</strong><span></span>79910173<br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-40.liferay.com/job/publish-testray-report/26113/">publish-testray-report#26113</a><br/></div></div>

2024-11-28 10:52 UTC, boton commented
ci:forward

2024-11-28 10:52 UTC, liferay-continuous-integration commented
Skipping previously passed test suites:
- `ci:test:sf`

2024-11-28 10:52 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>relevant</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-27.liferay.com/job/test-portal-acceptance-pullrequest(master)/13164/">test-portal-acceptance-pullrequest(master)</a></p><p><b>For more details click <a href="https://test-1-27.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/13164/jenkins-report.html">here</a>.</b></p>

2024-11-28 11:48 UTC, liferay-continuous-integration commented
All required test suite(s) passed.
Forwarding pull request to `brianchandotcom`.
[Console](https://test-1-27.liferay.com/job/test-portal-acceptance-pullrequest(master)/13164//consoleFull)

2024-11-28 11:48 UTC, closed without merging

2024-11-28 11:48 UTC, liferay-continuous-integration commented
Pull request has been successfully forwarded to  https://github.com/brianchandotcom/liferay-portal/pull/156551
[Console](https://test-1-27.liferay.com/job/test-portal-acceptance-pullrequest(master)/13164//consoleFull)

2024-11-28 11:58 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-27.liferay.com/job/test-portal-acceptance-pullrequest(master)/13164/">test-portal-acceptance-pullrequest(master)#13164</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-27.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/13164/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>relevant<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-content-management/liferay-portal/pull/6125">liferay-content-management#6125</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/#/project/35392/routines/45357">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/#/project/35392/routines/45357/build/79941308">[master] ci:test:relevant - DiegoHu97 &gt; liferay-content-management - PR#6125 - 2024-11-28[02:52:18]</a><br/></div><div><strong>Testray Build ID:</strong><span></span>79941308<br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-27.liferay.com/job/publish-testray-report/28786/">publish-testray-report#28786</a><br/></div></div>