LPD-44601 Move test move subcategories admin to another category
liferay-content-management/liferay-portal pull request #6190
Opened 2024-12-18 09:47 UTC by boton

# What is this trying to solve?

https://liferay.atlassian.net/browse/LPD-44601

Move another test in the poshi migration, move a sucategory to anmother category

# How am I fixing it?

Move POSHI test as a test step in the new playwgih test

# How can you verify that it works?
Run the test
```sh
npm run playwright -- test -g 'User can move a category and subcategory'
```

# tested locally (10 times)
![image](https://github.com/user-attachments/assets/5f39f744-d2b4-438e-bf5f-82ec3a7d5253)

2024-12-18 09:47 UTC, liferay-continuous-integration commented
CI is automatically triggering the following test suites:
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**sf**

2024-12-18 09:49 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-2.liferay.com/job/test-portal-source-format/2646/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-2.liferay.com/userContent/jobs/test-portal-source-format/builds/2646/jenkins-report.html">here</a>.</b></p>

2024-12-18 09:53 UTC, liferay-continuous-integration commented
<html><h3>:heavy_check_mark: ci:test:sf - 1 out of 1 jobs passed in 6 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/1d1009bc5a1f8b027c53e140f147d9a272f71af8">1d1009bc5a1f8b027c53e140f147d9a272f71af8</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/boton/liferay-portal/tree/LPD-44601-PW-add-test-categories-move-subcategory">LPD-44601-PW-add-test-categories-move-subcategory</a><br/>Branch GIT ID: <a href="https://github.com/boton/liferay-portal/commit/ea8c216a97f732c92e5de42bd63f6ebace69ee75">ea8c216a97f732c92e5de42bd63f6ebace69ee75</a></p>1 out of 1jobs PASSED<details><summary><strong>1 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-2.liferay.com/job/test-portal-source-format/2646/">test-portal-source-format</a></li></ul></details><h5>For more details click <a href="https://test-1-2.liferay.com/userContent/jobs/test-portal-source-format/builds/2646/jenkins-report.html">here</a>.</h5></details></html>

2024-12-18 09:55 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-2.liferay.com/job/test-portal-source-format/2646/">test-portal-source-format#2646</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-2.liferay.com/userContent/jobs/test-portal-source-format/builds/2646/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-content-management/liferay-portal/pull/6190">liferay-content-management#6190</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/#/project/35392/routines/45357">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/#/project/35392/routines/45357/build/94804736">[master] ci:test:sf - boton &gt; liferay-content-management - PR#6190 - 2024-12-18[01:47:42]</a><br/></div><div><strong>Testray Build ID:</strong><span></span>94804736<br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-2.liferay.com/job/publish-testray-report/5171/">publish-testray-report#5171</a><br/></div></div>

2024-12-18 11:07 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>content-management-playwright</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-27.liferay.com/job/test-portal-acceptance-pullrequest(master)/13392/">test-portal-acceptance-pullrequest(master)</a></p><p><b>For more details click <a href="https://test-1-27.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/13392/jenkins-report.html">here</a>.</b></p>

2024-12-18 12:08 UTC, liferay-continuous-integration commented
<html><h3>:x: ci:test:content-management-playwright - 10 out of 16 jobs passed in 1 hour 1 minute</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/1d1009bc5a1f8b027c53e140f147d9a272f71af8">1d1009bc5a1f8b027c53e140f147d9a272f71af8</a></p><h4>Upstream Comparison:</h4><p>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/1d1009bc5a1f8b027c53e140f147d9a272f71af8">1d1009bc5a1f8b027c53e140f147d9a272f71af8</a><br/>Jenkins Build URL: <a href="https://testray.liferay.com/#/project/35392/routines/590307/build/94477290">EE Development Acceptance (master) - 1088 - 2024-12-17[12:49:06]</a></p><details><summary><strong>ci:test:content-management-playwright - 10 out of 16 jobs PASSED</strong></summary><div><h4>6 Failed Jobs:</h4><ul><li><a href="https://test-1-27.liferay.com/job/test-portal-acceptance-pullrequest(master)/13392/"><strike>test-portal-acceptance-pullrequest(master)</strike></a></li><li>playwright-js-tomcat90-mysql57<ul><li><a href="https://test-1-29.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1040634/">playwright-js-tomcat90-mysql57/0/0</a></li><li><a href="https://test-1-38.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/998571/">playwright-js-tomcat90-mysql57/1/0</a></li><li><a href="https://test-1-40.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/807132/">playwright-js-tomcat90-mysql57/2/0</a></li><li><a href="https://test-1-27.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1145775/"><strike>playwright-js-tomcat90-mysql57/3/0</strike></a></li><li><a href="https://test-1-38.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/998570/">playwright-js-tomcat90-mysql57/4/0</a></li><li><a href="https://test-1-25.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/733397/"><strike>playwright-js-tomcat90-mysql57/5/0</strike></a></li><li><a href="https://test-1-8.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/501095/">playwright-js-tomcat90-mysql57/6/0</a></li><li><a href="https://test-1-26.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1251106/"><strike>playwright-js-tomcat90-mysql57/7/0</strike></a></li><li><a href="https://test-1-34.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1057601/">playwright-js-tomcat90-mysql57/8/0</a></li><li><a href="https://test-1-27.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1145776/">playwright-js-tomcat90-mysql57/9/0</a></li><li><a href="https://test-1-40.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/807133/">playwright-js-tomcat90-mysql57/10/0</a></li><li><a href="https://test-1-38.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/998572/">playwright-js-tomcat90-mysql57/11/0</a></li><li><a href="https://test-1-2.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/446840/">playwright-js-tomcat90-mysql57/12/0</a></li><li><a href="https://test-1-37.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1278611/"><strike>playwright-js-tomcat90-mysql57/13/0</strike></a></li><li><a href="https://test-1-30.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1107190/"><strike>playwright-js-tomcat90-mysql57/14/0</strike></a></li></ul></li></ul></div><details><summary><strong>10 Successful Jobs:</strong></summary><ul/></details></details><h5>For more details click <a href="https://test-1-27.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/13392/jenkins-report.html">here</a>.</h5><hr/><h4>Failures unique to this pull:</h4><ol><li><div><a href="https://test-1-30.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1107190//consoleText">playwright-js-tomcat90-mysql57/14/0</a> - <a href="https://storage.cloud.google.com/testray-results/2024-12/test-1-27/test-portal-acceptance-pullrequest(master)/13392/playwright-js-tomcat90-mysql57/14/0/playwright-report/index.html">Playwright Report</a><ol><li><details><summary><a href="https://test-1-30.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1107190/testReport/document-library-web_fileEntry.spec/ts">document-library-web/fileEntry.spec.ts</a></summary><div><ol><li><a href="https://test-1-30.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1107190//testReport/document-library-web_fileEntry.spec/ts/Show_icon_in_the_DL_item_selector">Show icon in the DL item selector</a></li></ol></div></details></li></ol></div></li></ol><hr/><details><summary><strong>Failures in common with <a href="https://test-1-40.liferay.com/job/test-portal-acceptance-upstream-dxp(master)">acceptance upstream results</a> at 1d1009bc5a1f8b027c53e140f147d9a272f71af8:</strong></summary><ol><li><div><a href="https://test-1-27.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1145775//consoleText">playwright-js-tomcat90-mysql57/3/0</a> - <a href="https://storage.cloud.google.com/testray-results/2024-12/test-1-27/test-portal-acceptance-pullrequest(master)/13392/playwright-js-tomcat90-mysql57/3/0/playwright-report/index.html">Playwright Report</a><ol><li><details><summary><a href="https://test-1-27.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1145775/testReport/blogs-web_blogEntry.spec/ts">blogs-web/blogEntry.spec.ts</a></summary><div><ol><li><a href="https://test-1-27.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1145775//testReport/blogs-web_blogEntry.spec/ts/Categories_with_blank_spaces_in_friendly_URL">Categories with blank spaces in friendly URL</a></li><li><a href="https://test-1-27.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1145775//testReport/blogs-web_blogEntry.spec/ts/Only_blogs_entry_categories_in_the_friendly_URL">Only blogs entry categories in the friendly URL</a></li><li><a href="https://test-1-27.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1145775//testReport/blogs-web_blogEntry.spec/ts/Reorder_categories_in_the_friendly_URL">Reorder categories in the friendly URL</a></li><li><a href="https://test-1-27.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1145775//testReport/blogs-web_blogEntry.spec/ts/Select_categories_for_the_custom_friendly_URL">Select categories for the custom friendly URL</a></li><li><a href="https://test-1-27.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1145775//testReport/blogs-web_blogEntry.spec/ts/The_URL_changes_when_a_category_is_modified">The URL changes when a category is modified</a></li><li>...</li></ol></div></details></li></ol></div></li><li><div><a href="https://test-1-25.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/733397//consoleText">playwright-js-tomcat90-mysql57/5/0</a> - <a href="https://storage.cloud.google.com/testray-results/2024-12/test-1-27/test-portal-acceptance-pullrequest(master)/13392/playwright-js-tomcat90-mysql57/5/0/playwright-report/index.html">Playwright Report</a><ol><li><details><summary><a href="https://test-1-25.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/733397/testReport/journal-web_journalArticle.spec/ts">journal-web/journalArticle.spec.ts</a></summary><div><ol><li><a href="https://test-1-25.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/733397//testReport/journal-web_journalArticle.spec/ts/Add_error_message_in_Translation_for_concurrent_users">Add error message in Translation for concurrent users</a></li><li><a href="https://test-1-25.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/733397//testReport/journal-web_journalArticle.spec/ts/Check_alert_message_of_duplicated_friendly_UR [...]

2024-12-19 09:16 UTC, boton commented
The test is passing in CI failures are unrelated

<img width="1481" alt="image" src="https://github.com/user-attachments/assets/71111c38-c159-4f0c-aaa4-76ee2930c971" />

2024-12-19 09:48 UTC, DiegoHu97 requested changes
LGTM! Only one little doubt that I have :smile:

2024-12-19 09:48 UTC, DiegoHu97 commented on modules/test/playwright/helpers/HeadlessAdminTaxonomyApiHelper.ts
> +	async postTaxonomyCategoryTaxonomyCategory({
A little doubt here, this shouldn't be post...Subcategory instead of post...Category?

2024-12-19 16:06 UTC, DiegoHu97 approved these changes

2024-12-19 16:06 UTC, DiegoHu97 commented
ci:forward

2024-12-19 16:06 UTC, liferay-continuous-integration commented
Skipping previously passed test suites:
- `ci:test:relevant`
- `ci:test:sf`
- `ci:test:stable`

2024-12-19 16:07 UTC, liferay-continuous-integration commented
All required test suite(s) passed.
Forwarding pull request to `brianchandotcom`.
[Console](https://test-1-39.liferay.com/job/forward-pullrequest/1548//consoleFull)

2024-12-19 16:07 UTC, closed without merging