LPD-41946
liferay-content-management/liferay-portal pull request #6216
Opened 2024-12-31 09:44 UTC by NemethNorbert

[LPD-41946](https://liferay.atlassian.net/browse/LPD-41946)

Migrated the TagsUsecases poshi tests based on https://liferay.atlassian.net/wiki/spaces/ENGLIMA/pages/3399516288/TagsUseCase.testcase

I combined the tests that I decided to migrate into 3 tests.

# How can you verify that it works?

Run the tests
<img width="907" alt="Screenshot 2024-12-30 at 19 34 14" src="https://github.com/user-attachments/assets/704cb96d-f361-48a3-9c00-b63a8c9b64ec" />
<img width="916" alt="Screenshot 2024-12-30 at 19 31 05" src="https://github.com/user-attachments/assets/8975c728-67a8-4cc2-b8b0-c200b72004d6" />
<img width="924" alt="Screenshot 2024-12-30 at 18 08 49" src="https://github.com/user-attachments/assets/47765540-5f33-4956-9669-8ca756acf679" />

2024-12-31 09:44 UTC, liferay-continuous-integration commented
CI is automatically triggering the following test suites:
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**sf**

2024-12-31 09:46 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-28.liferay.com/job/test-portal-source-format/7134/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-28.liferay.com/userContent/jobs/test-portal-source-format/builds/7134/jenkins-report.html">here</a>.</b></p>

2024-12-31 09:49 UTC, liferay-continuous-integration commented
<html><h3>:heavy_check_mark: ci:test:sf - 1 out of 1 jobs passed in 5 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/53aca607f467049e5509550f60b21643895fd7ba">53aca607f467049e5509550f60b21643895fd7ba</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/NemethNorbert/liferay-portal/tree/LPD-41946">LPD-41946</a><br/>Branch GIT ID: <a href="https://github.com/NemethNorbert/liferay-portal/commit/6077bea8d3e1920a7321182d4718286395f88098">6077bea8d3e1920a7321182d4718286395f88098</a></p>1 out of 1jobs PASSED<details><summary><strong>1 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-28.liferay.com/job/test-portal-source-format/7134/">test-portal-source-format</a></li></ul></details><h5>For more details click <a href="https://test-1-28.liferay.com/userContent/jobs/test-portal-source-format/builds/7134/jenkins-report.html">here</a>.</h5></details></html>

2024-12-31 09:51 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-28.liferay.com/job/test-portal-source-format/7134/">test-portal-source-format#7134</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-28.liferay.com/userContent/jobs/test-portal-source-format/builds/7134/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-content-management/liferay-portal/pull/6216">liferay-content-management#6216</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/#/project/35392/routines/45357">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/#/project/35392/routines/45357/build/101949765">[master] ci:test:sf - NemethNorbert &gt; liferay-content-management - PR#6216 - 2024-12-31[01:44:56]</a><br/></div><div><strong>Testray Build ID:</strong><span></span>101949765<br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-28.liferay.com/job/publish-testray-report/26378/">publish-testray-report#26378</a><br/></div></div>

2025-01-10 10:55 UTC, boton requested changes
Overall LGTM but I have some questions/suggestions that I left on inline comments

2025-01-10 10:55 UTC, boton commented on modules/test/playwright/tests/asset-tags-admin-web/tagsUseCases.spec.ts
> +		await page.getByLabel('Remove first').click();
Isn't it better to delete the middle ('second') option and then check that the deletion is correct `getByText('first third')`?

2025-01-13 08:53 UTC, NemethNorbert commented on modules/test/playwright/tests/asset-tags-admin-web/tagsUseCases.spec.ts
> +			.evaluate((element: HTMLElement) => element.click());
It does the same, however as the element is only clickable if we hover over it, I had to use evaluate to be able to click the edit entry button. Without it, I received failing tests.

2025-01-13 08:56 UTC, NemethNorbert commented on modules/test/playwright/tests/asset-tags-admin-web/tagsUseCases.spec.ts
> +		await page.getByLabel('Remove first').click();
Why it's worst to remove the first? The expect() block is there to make sure we load the modal in before we try to remove the tag.. Without it the test was flaky

2025-01-13 09:37 UTC, boton commented on modules/test/playwright/tests/asset-tags-admin-web/tagsUseCases.spec.ts
> +		await page.getByRole('button', {name: 'Publish'}).click({delay: 1000});
Can we use `clickAndExpectToBeHidden` here instead?

2025-01-13 10:41 UTC, boton commented
We will try to work on https://github.com/liferay-content-management/liferay-portal/pull/6216#discussion_r1907513318 when @NemethNorbert has the branch ready :D

2025-01-14 14:22 UTC, boton commented on modules/test/playwright/tests/asset-tags-admin-web/tagsUseCases.spec.ts
> +			.evaluate((element: HTMLElement) => element.click());
I'm working to avoid this evaluate

2025-01-15 08:43 UTC, boton commented
ci:test:sf

2025-01-15 08:45 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-30.liferay.com/job/test-portal-source-format/6556/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-30.liferay.com/userContent/jobs/test-portal-source-format/builds/6556/jenkins-report.html">here</a>.</b></p>

2025-01-15 08:48 UTC, liferay-continuous-integration commented
<html><h3>:x: ci:test:sf - 0 out of 1 jobs passed in 4 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/89df9067788c65d4ac8974b2fa730f28d482d766">89df9067788c65d4ac8974b2fa730f28d482d766</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/NemethNorbert/liferay-portal/tree/LPD-41946">LPD-41946</a><br/>Branch GIT ID: <a href="https://github.com/NemethNorbert/liferay-portal/commit/bb1608d4e85b66196a275fee4577844270b4e289">bb1608d4e85b66196a275fee4577844270b4e289</a></p>0 out of 1jobs PASSED<div><h4>1 Failed Jobs:</h4><ul><li><a href="https://test-1-30.liferay.com/job/test-portal-source-format/6556/"><strike>test-portal-source-format</strike></a></li></ul></div><h5>For more details click <a href="https://test-1-30.liferay.com/userContent/jobs/test-portal-source-format/builds/6556/jenkins-report.html">here</a>.</h5><pre>     [exec] &gt; Task :packageRunCheckFormat
     [exec] yarn run v1.13.0
     [exec] \$ node-scripts check:ci
     [exec] 
     [exec] ⚙️ Running preflight checks...
     [exec] 
     [exec] ⚙️ Checking outdated tsconfig.json files ...
     [exec] 
     [exec] ⚙️ Running TypeScript checks on modified files...
     [exec] ℹ️ A total of 12 CPUs were detected: launching tsc using 12 workers
     [exec] 
     [exec] ⚙️ Running format checks on modified files...
     [exec]    /opt/dev/projects/github/liferay-portal/modules/test/playwright/tests/asset-tags-admin-web/tagsUseCases.spec.ts
     [exec]      1:1  error  File has format errors.  (format check)
     [exec]    
     [exec]    ✖ 1 problem (1 error, 0 warnings)
     [exec]    
     [exec]    
     [exec] ❌ CI checks failed.
     [exec] error Command failed with exit code 1.
     [exec] info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
     [exec] 
     [exec] &gt; Task :packageRunCheckFormat FAILED
     [exec] Gradle build finished at 2025-01-15 08:47:59.811.
     [exec] 
     [exec] 
     [exec] FAILURE: Build failed with an exception.
     [exec] 
     [exec] * What went wrong:
     [exec] Execution failed for task ':packageRunCheckFormat'.
     [exec] &gt; Process 'command '/opt/dev/projects/github/liferay-portal/build/node/bin/node'' finished with non-zero exit value 1
     [exec] 
     [exec] * Try:
     [exec] &gt; Run with --info or --debug option to get more log output.
     [exec] &gt; Run with --scan to get full insights.
     [exec] &gt; Get more help at https://help.gradle.org.
     [exec] 
     [exec] * Exception is:
     [exec] org.gradle.api.tasks.TaskExecutionException: Execution failed for task ':packageRunCheckFormat'.
     [exec]   at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.lambda\$executeIfValid\$1(ExecuteActionsTaskExecuter.java:148)
     [exec]   at org.gradle.internal.Try\$Failure.ifSuccessfulOrElse(Try.java:282)
     [exec]   at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeIfValid(ExecuteActionsTaskExecuter.java:146)
     [exec]   at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.execute(ExecuteActionsTaskExecuter.java:134)
     [exec]   at org.gradle.api.internal.tasks.execution.FinalizePropertiesTaskExecuter.execute(FinalizePropertiesTaskExecuter.java:46)
     [exec]   at org.gradle.api.internal.tasks.execution.ResolveTaskExecutionModeExecuter.execute(ResolveTaskExecutionModeExecuter.java:51)</pre></details></html>

2025-01-15 08:50 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-30.liferay.com/job/test-portal-source-format/6556/">test-portal-source-format#6556</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-30.liferay.com/userContent/jobs/test-portal-source-format/builds/6556/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-content-management/liferay-portal/pull/6216">liferay-content-management#6216</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/#/project/35392/routines/45357">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/#/project/35392/routines/45357/build/109018044">[master] ci:test:sf - NemethNorbert &gt; liferay-content-management - PR#6216 - 2025-01-15[00:43:57]</a><br/></div><div><strong>Testray Build ID:</strong><span></span>109018044<br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-30.liferay.com/job/publish-testray-report/25482/">publish-testray-report#25482</a><br/></div></div>

2025-01-15 10:35 UTC, boton commented
It works fine locally only login errors
![image](https://github.com/user-attachments/assets/249a3ef9-153d-48aa-9b37-6feda0eb4a9a)

2025-01-15 10:41 UTC, boton commented
We missed deleting the current Poshi tests.
I am working on it.

ty @ealonso!

2025-01-15 10:41 UTC, boton commented
ci:test:sf

2025-01-15 10:41 UTC, boton commented
ci:test:content-management-playwright

2025-01-15 10:42 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>content-management-playwright</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-39.liferay.com/job/test-portal-acceptance-pullrequest(master)/12292/">test-portal-acceptance-pullrequest(master)</a></p><p><b>For more details click <a href="https://test-1-39.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/12292/jenkins-report.html">here</a>.</b></p>

2025-01-15 10:46 UTC, liferay-continuous-integration commented
<html><h3>:x: ci:test:sf - 0 out of 1 jobs passed in 5 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/89df9067788c65d4ac8974b2fa730f28d482d766">89df9067788c65d4ac8974b2fa730f28d482d766</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/NemethNorbert/liferay-portal/tree/LPD-41946">LPD-41946</a><br/>Branch GIT ID: <a href="https://github.com/NemethNorbert/liferay-portal/commit/1c5fd1c452ad0dcaf4bcfad7941bd6c9f8400f21">1c5fd1c452ad0dcaf4bcfad7941bd6c9f8400f21</a></p>0 out of 1jobs PASSED<div><h4>1 Failed Jobs:</h4><ul><li><a href="https://test-1-33.liferay.com/job/test-portal-source-format/3875/"><strike>test-portal-source-format</strike></a></li></ul></div><h5>For more details click <a href="https://test-1-33.liferay.com/userContent/jobs/test-portal-source-format/builds/3875/jenkins-report.html">here</a>.</h5><pre>     [exec] &gt; Task :packageRunCheckFormat
     [exec] yarn run v1.13.0
     [exec] \$ node-scripts check:ci
     [exec] 
     [exec] ⚙️ Running preflight checks...
     [exec] 
     [exec] ⚙️ Checking outdated tsconfig.json files ...
     [exec] 
     [exec] ⚙️ Running TypeScript checks on modified files...
     [exec] ℹ️ A total of 12 CPUs were detected: launching tsc using 12 workers
     [exec] 
     [exec] ⚙️ Running format checks on modified files...
     [exec] Done in 6.41s.
     [exec] 
     [exec] &gt; Task :portalYarnCheckFormat
     [exec] 
     [exec] Gradle build finished at 2025-01-15 10:45:08.997.
     [exec] 
     [exec] BUILD SUCCESSFUL in 20s
     [exec] 3 actionable tasks: 3 executed
     [exec] 
     [exec] See the profiling report at: file:///opt/dev/projects/github/liferay-portal/build/reports/profile/profile-2025-01-15-02-44-51.html
     [exec] A fine-grained performance profile is available: use the --scan option.
[beanshell] Executing Gradle task: packageRunCheckFormat
     [exec] To honour the JVM settings for this build a single-use Daemon process will be forked. For more on this, please refer to https://docs.gradle.org/8.5/userguide/gradle_daemon.html#sec:disabling_the_daemon in the Gradle documentation.
     [exec] Daemon will be stopped at the end of the build 
     [exec] &gt; Task :downloadNode
     [exec] 
     [exec] &gt; Task :npmInstall
     [exec] npm WARN config production Use `--omit=dev` instead.
     [exec] 
     [exec] added 130 packages, and audited 134 packages in 2s
     [exec] 
     [exec] 23 packages are looking for funding
     [exec]   run `npm fund` for details
     [exec] 
     [exec] found 0 vulnerabilities
     [exec] 
     [exec] &gt; Task :packageRunCheckFormat
     [exec] npm WARN config production Use `--omit=dev` instead.
     [exec] 
     [exec] &gt; @liferay/playwright@1.0.0 checkFormat
     [exec] &gt; tsc
     [exec] 
     [exec] tests/commerce/commerce-product-definitions-web/commerceAdminProductConfigurations.spec.ts(41,4): error TS2554: Expected 1 arguments, but got 2.
     [exec] tests/commerce/commerce-product-definitions-web/commerceAdminProductConfigurations.spec.ts(125,4): error TS2554: Expected 1 arguments, but got 2.
     [exec] 
     [exec] &gt; Task :packageRunCheckFormat FAILED
     [exec] Gradle build finished at 2025-01-15 10:45:38.387.
     [exec] 
     [exec] 
     [exec] FAILURE: Build failed with an exception.
     [exec] 
     [exec] * What went wrong:</pre></details></html>

2025-01-15 10:48 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-33.liferay.com/job/test-portal-source-format/3875/">test-portal-source-format#3875</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-33.liferay.com/userContent/jobs/test-portal-source-format/builds/3875/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-content-management/liferay-portal/pull/6216">liferay-content-management#6216</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/#/project/35392/routines/45357">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/#/project/35392/routines/45357/build/109086270">[master] ci:test:sf - NemethNorbert &gt; liferay-content-management - PR#6216 - 2025-01-15[02:41:27]</a><br/></div><div><strong>Testray Build ID:</strong><span></span>109086270<br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-33.liferay.com/job/publish-testray-report/15852/">publish-testray-report#15852</a><br/></div></div>

2025-01-15 11:00 UTC, boton commented
ci:test:sf

2025-01-15 11:01 UTC, boton commented
Rebased and relaunched the SF because of https://github.com/liferay-content-management/liferay-portal/pull/6216#issuecomment-2592293895

```
     [exec] > @liferay/playwright@1.0.0 checkFormat
     [exec] > tsc
     [exec] 
     [exec] tests/commerce/commerce-product-definitions-web/commerceAdminProductConfigurations.spec.ts(41,4): error TS2554: Expected 1 arguments, but got 2.
     [exec] tests/commerce/commerce-product-definitions-web/commerceAdminProductConfigurations.spec.ts(125,4): error TS2554: Expected 1 arguments, but got 2.
     [exec] 
     [exec] > Task :packageRunCheckFormat FAILED
```

2025-01-15 11:05 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-34.liferay.com/job/test-portal-source-format/3844/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-34.liferay.com/userContent/jobs/test-portal-source-format/builds/3844/jenkins-report.html">here</a>.</b></p>

2025-01-15 11:08 UTC, liferay-continuous-integration commented
<html><h3>:x: ci:test:sf - 0 out of 1 jobs passed in 6 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/89df9067788c65d4ac8974b2fa730f28d482d766">89df9067788c65d4ac8974b2fa730f28d482d766</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/NemethNorbert/liferay-portal/tree/LPD-41946">LPD-41946</a><br/>Branch GIT ID: <a href="https://github.com/NemethNorbert/liferay-portal/commit/19bc15bae267e6abed1304a4a69b43fc7e8384c7">19bc15bae267e6abed1304a4a69b43fc7e8384c7</a></p>0 out of 1jobs PASSED<div><h4>1 Failed Jobs:</h4><ul><li><a href="https://test-1-34.liferay.com/job/test-portal-source-format/3844/"><strike>test-portal-source-format</strike></a></li></ul></div><h5>For more details click <a href="https://test-1-34.liferay.com/userContent/jobs/test-portal-source-format/builds/3844/jenkins-report.html">here</a>.</h5><pre>     [exec] &gt; Task :packageRunCheckFormat
     [exec] yarn run v1.13.0
     [exec] \$ node-scripts check:ci
     [exec] 
     [exec] ⚙️ Running preflight checks...
     [exec] 
     [exec] ⚙️ Checking outdated tsconfig.json files ...
     [exec] 
     [exec] ⚙️ Running TypeScript checks on modified files...
     [exec] ℹ️ A total of 12 CPUs were detected: launching tsc using 12 workers
     [exec] 
     [exec] ⚙️ Running format checks on modified files...
     [exec] 
     [exec] Done in 6.10s.
     [exec] 
     [exec] &gt; Task :portalYarnCheckFormat
     [exec] Gradle build finished at 2025-01-15 11:07:57.160.
     [exec] 
     [exec] BUILD SUCCESSFUL in 21s
     [exec] 3 actionable tasks: 3 executed
     [exec] 
     [exec] See the profiling report at: file:///opt/dev/projects/github/liferay-portal/build/reports/profile/profile-2025-01-15-03-07-38.html
     [exec] A fine-grained performance profile is available: use the --scan option.
[beanshell] Executing Gradle task: packageRunCheckFormat
     [exec] To honour the JVM settings for this build a single-use Daemon process will be forked. For more on this, please refer to https://docs.gradle.org/8.5/userguide/gradle_daemon.html#sec:disabling_the_daemon in the Gradle documentation.
     [exec] Daemon will be stopped at the end of the build 
     [exec] &gt; Task :downloadNode
     [exec] 
     [exec] &gt; Task :npmInstall
     [exec] npm WARN config production Use `--omit=dev` instead.
     [exec] 
     [exec] added 130 packages, and audited 134 packages in 2s
     [exec] 
     [exec] 23 packages are looking for funding
     [exec]   run `npm fund` for details
     [exec] 
     [exec] found 0 vulnerabilities
     [exec] 
     [exec] &gt; Task :packageRunCheckFormat
     [exec] npm WARN config production Use `--omit=dev` instead.
     [exec] 
     [exec] &gt; @liferay/playwright@1.0.0 checkFormat
     [exec] &gt; tsc
     [exec] 
     [exec] tests/commerce/commerce-product-definitions-web/commerceAdminProductConfigurations.spec.ts(41,4): error TS2554: Expected 1 arguments, but got 2.
     [exec] tests/commerce/commerce-product-definitions-web/commerceAdminProductConfigurations.spec.ts(125,4): error TS2554: Expected 1 arguments, but got 2.
     [exec] 
     [exec] 
     [exec] FAILURE: Build failed with an exception.
     [exec] 
     [exec] * What went wrong:
     [exec] Execution failed for task ':packageRunCheckFormat'.</pre></details></html>

2025-01-15 11:21 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-34.liferay.com/job/test-portal-source-format/3844/">test-portal-source-format#3844</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-34.liferay.com/userContent/jobs/test-portal-source-format/builds/3844/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-content-management/liferay-portal/pull/6216">liferay-content-management#6216</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/#/project/35392/routines/45357">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/#/project/35392/routines/45357/build/109104068">[master] ci:test:sf - NemethNorbert &gt; liferay-content-management - PR#6216 - 2025-01-15[03:02:55]</a><br/></div><div><strong>Testray Build ID:</strong><span></span>109104068<br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-34.liferay.com/job/publish-testray-report/25829/">publish-testray-report#25829</a><br/></div></div>

2025-01-15 12:22 UTC, liferay-continuous-integration commented
<html><h3>:x: ci:test:content-management-playwright - 13 out of 16 jobs passed in 1 hour 40 minutes</h3><details><summary>Click here for more details.</summary><br/><p>This pull is eligible for <a href="https://grow.liferay.com/share/CI+liferay-continuous-integration+GitHub+Commands#General-Commands">reevaluation</a>. When this <a href="https://test-1-40.liferay.com/job/test-portal-acceptance-upstream-dxp(master)/1121">upstream build</a> has completed, using the following CI command will compare this pull request result against a more recent upstream result:<pre>ci:reevaluate:1397401_12292</pre></p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/89df9067788c65d4ac8974b2fa730f28d482d766">89df9067788c65d4ac8974b2fa730f28d482d766</a></p><h4>Upstream Comparison:</h4><p>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/ca4c6aaf494430703ef7a971a663855e331de0b8">ca4c6aaf494430703ef7a971a663855e331de0b8</a><br/>Jenkins Build URL: <a href="https://testray.liferay.com/#/project/35392/routines/590307/build/108030031">EE Development Acceptance (master) - 1120 - 2025-01-13[20:36:58]</a></p><details><summary><strong>ci:test:content-management-playwright - 13 out of 16 jobs PASSED</strong></summary><div><h4>3 Failed Jobs:</h4><ul><li><a href="https://test-1-39.liferay.com/job/test-portal-acceptance-pullrequest(master)/12292/"><strike>test-portal-acceptance-pullrequest(master)</strike></a></li><li>playwright-js-tomcat90-mysql57<ul><li><a href="https://test-1-25.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/742863/">playwright-js-tomcat90-mysql57/0/0</a></li><li><a href="https://test-1-25.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/742860/">playwright-js-tomcat90-mysql57/1/0</a></li><li><a href="https://test-1-34.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1064611/">playwright-js-tomcat90-mysql57/2/0</a></li><li><a href="https://test-1-34.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1064610/">playwright-js-tomcat90-mysql57/3/0</a></li><li><a href="https://test-1-34.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1064609/">playwright-js-tomcat90-mysql57/4/0</a></li><li><a href="https://test-1-36.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1090665/"><strike>playwright-js-tomcat90-mysql57/5/0</strike></a></li><li><a href="https://test-1-34.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1064613/">playwright-js-tomcat90-mysql57/6/0</a></li><li><a href="https://test-1-25.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/742861/">playwright-js-tomcat90-mysql57/7/0</a></li><li><a href="https://test-1-34.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1064612/">playwright-js-tomcat90-mysql57/8/0</a></li><li><a href="https://test-1-36.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1090666/">playwright-js-tomcat90-mysql57/9/0</a></li><li><a href="https://test-1-1.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/390234/">playwright-js-tomcat90-mysql57/10/0</a></li><li><a href="https://test-1-36.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1090667/">playwright-js-tomcat90-mysql57/11/0</a></li><li><a href="https://test-1-26.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1260285/">playwright-js-tomcat90-mysql57/12/0</a></li><li><a href="https://test-1-34.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1064614/">playwright-js-tomcat90-mysql57/13/0</a></li><li><a href="https://test-1-25.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/742862/"><strike>playwright-js-tomcat90-mysql57/14/0</strike></a></li></ul></li></ul></div><details><summary><strong>13 Successful Jobs:</strong></summary><ul/></details></details><h5>For more details click <a href="https://test-1-39.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/12292/jenkins-report.html">here</a>.</h5><hr/><h4>This pull contains no unique failures.</h4><hr/><details><summary><strong>Failures in common with <a href="https://test-1-40.liferay.com/job/test-portal-acceptance-upstream-dxp(master)">acceptance upstream results</a> at ca4c6aaf494430703ef7a971a663855e331de0b8:</strong></summary><ol><li><div><a href="https://test-1-36.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1090665//consoleText">playwright-js-tomcat90-mysql57/5/0</a> - <a href="https://storage.cloud.google.com/testray-results/2025-01/test-1-39/test-portal-acceptance-pullrequest(master)/12292/playwright-js-tomcat90-mysql57/5/0/playwright-report/index.html">Playwright Report</a><ol><li><details><summary><a href="https://test-1-36.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1090665/testReport/journal-web_journalArticle.spec/ts">journal-web/journalArticle.spec.ts</a></summary><div><ol><li><a href="https://test-1-36.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1090665//testReport/journal-web_journalArticle.spec/ts/LPD_17782__This_is_a_test_for_bulk_permissions_of_web_content">LPD-17782: This is a test for bulk permissions of web content</a></li><li><a href="https://test-1-36.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1090665//testReport/journal-web_journalArticle.spec/ts/LPD_6813__Make_prefix_URLs_configurable">LPD-6813: Make prefix URLs configurable</a></li></ol></div></details></li></ol></div></li><li><div><a href="https://test-1-25.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/742862//consoleText">playwright-js-tomcat90-mysql57/14/0</a> - <a href="https://storage.cloud.google.com/testray-results/2025-01/test-1-39/test-portal-acceptance-pullrequest(master)/12292/playwright-js-tomcat90-mysql57/14/0/playwright-report/index.html">Playwright Report</a><ol><li><details><summary><a href="https://test-1-25.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/742862/testReport/document-library-web_fileEntry.spec/ts">document-library-web/fileEntry.spec.ts</a></summary><div><ol><li><a href="https://test-1-25.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/742862//testReport/document-library-web_fileEntry.spec/ts/Show_icon_in_the_DL_item_selector">Show icon in the DL item selector</a></li></ol></div></details></li></ol></div></li></ol></details></details></html>

2025-01-15 12:25 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-39.liferay.com/job/test-portal-acceptance-pullrequest(master)/12292/">test-portal-acceptance-pullrequest(master)#12292</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-39.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/12292/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>content-management-playwright<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-content-management/liferay-portal/pull/6216">liferay-content-management#6216</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/#/project/35392/routines/45357">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/#/project/35392/routines/45357/build/109118708">[master] ci:test:content-management-playwright - NemethNorbert &gt; liferay-content-management - PR#6216 - 2025-01-15[02:41:37]</a><br/></div><div><strong>Testray Build ID:</strong><span></span>109118708<br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-39.liferay.com/job/publish-testray-report/26508/">publish-testray-report#26508</a><br/></div></div>

2025-01-15 15:52 UTC, boton commented
@NemethNorbert I tried to delete the old Poshi "Tags" test in this PR but some of the migration is missing.

I create two new tasks to finish the tag migration:
1. [LPD-46142](https://liferay.atlassian.net/browse/LPD-46142) Migrate last tests Tags.testcase to unit/integration backend
2. [LPD-46144](https://liferay.atlassian.net/browse/LPD-46144) Migrate TagsAdminWithKeyboard.testcase

2025-01-15 15:53 UTC, boton approved these changes

2025-01-15 15:55 UTC, boton commented
@NemethNorbert Check that I'm not doing anything crazy and forward it if you agree or review if you missing somehing

2025-01-15 16:07 UTC, NemethNorbert commented
ci:forward

2025-01-15 16:07 UTC, liferay-continuous-integration commented
CI is automatically triggering the following test suites:
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**relevant**
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**sf**
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**stable**

The pull request will automatically be forwarded to the user `brianchandotcom` If the following test suites pass:
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**relevant**
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**sf**
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**stable**

2025-01-15 16:08 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>relevant</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-38.liferay.com/job/test-portal-acceptance-pullrequest(master)/11767/">test-portal-acceptance-pullrequest(master)</a></p><p><b>For more details click <a href="https://test-1-38.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/11767/jenkins-report.html">here</a>.</b></p>

2025-01-15 16:10 UTC, liferay-continuous-integration commented
<h1>Build completed.</h1><p>Jenkins URL: <a href="https://test-1-38.liferay.com/job/test-portal-acceptance-pullrequest(master)/11767/">test-portal-acceptance-pullrequest(master)</a></p><p>The <code>relevant</code> test suite did not execute tests because all modified files were excluded by the <b>modified.files.global.excludes</b> property in <code>test.properties</code>.</p><p>Please use <code>ci:test:sf</code> and/or <code>ci:forward</code> for this pull request to be forwarded or eligible for forwarding.</p>

2025-01-15 16:17 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-38.liferay.com/job/test-portal-acceptance-pullrequest(master)/11767/">test-portal-acceptance-pullrequest(master)#11767</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-38.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/11767/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>relevant<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-content-management/liferay-portal/pull/6216">liferay-content-management#6216</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/#/project/35392/routines/45357">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/#/project/35392/routines/45357/build/109226455">[master] ci:test:relevant - NemethNorbert &gt; liferay-content-management - PR#6216 - 2025-01-15[08:07:53]</a><br/></div><div><strong>Testray Build ID:</strong><span></span>109226455<br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-38.liferay.com/job/publish-testray-report/24286/">publish-testray-report#24286</a><br/></div></div>

2025-01-15 16:23 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-7.liferay.com/job/test-portal-source-format/6389/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-7.liferay.com/userContent/jobs/test-portal-source-format/builds/6389/jenkins-report.html">here</a>.</b></p>

2025-01-15 16:29 UTC, liferay-continuous-integration commented
<html><h3>:x: ci:test:sf - 0 out of 1 jobs passed in 8 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/89df9067788c65d4ac8974b2fa730f28d482d766">89df9067788c65d4ac8974b2fa730f28d482d766</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/NemethNorbert/liferay-portal/tree/LPD-41946">LPD-41946</a><br/>Branch GIT ID: <a href="https://github.com/NemethNorbert/liferay-portal/commit/d94c7288df9bbf2388cfe37b21d8e69d3a595caa">d94c7288df9bbf2388cfe37b21d8e69d3a595caa</a></p>0 out of 1jobs PASSED<div><h4>1 Failed Jobs:</h4><ul><li><a href="https://test-1-7.liferay.com/job/test-portal-source-format/6389/"><strike>test-portal-source-format</strike></a></li></ul></div><h5>For more details click <a href="https://test-1-7.liferay.com/userContent/jobs/test-portal-source-format/builds/6389/jenkins-report.html">here</a>.</h5><pre>     [exec] &gt; Task :packageRunCheckFormat
     [exec] yarn run v1.13.0
     [exec] \$ node-scripts check:ci
     [exec] 
     [exec] ?????? Running preflight checks...
     [exec] 
     [exec] ?????? Checking outdated tsconfig.json files ...
     [exec] 
     [exec] ?????? Running TypeScript checks on modified files...
     [exec] ?????? A total of 8 CPUs were detected: launching tsc using 8 workers
     [exec] 
     [exec] ?????? Running format checks on modified files...
     [exec] 
     [exec] Done in 9.81s.
     [exec] 
     [exec] &gt; Task :portalYarnCheckFormat
     [exec] Gradle build finished at 2025-01-15 16:28:12.142.
     [exec] 
     [exec] BUILD SUCCESSFUL in 33s
     [exec] 3 actionable tasks: 3 executed
     [exec] 
     [exec] See the profiling report at: file:///opt/dev/projects/github/liferay-portal/build/reports/profile/profile-2025-01-15-08-27-46.html
     [exec] A fine-grained performance profile is available: use the --scan option.
[beanshell] Executing Gradle task: packageRunCheckFormat
     [exec] To honour the JVM settings for this build a single-use Daemon process will be forked. For more on this, please refer to https://docs.gradle.org/8.5/userguide/gradle_daemon.html#sec:disabling_the_daemon in the Gradle documentation.
     [exec] Daemon will be stopped at the end of the build 
     [exec] &gt; Task :downloadNode
     [exec] 
     [exec] &gt; Task :npmInstall
     [exec] npm WARN config production Use `--omit=dev` instead.
     [exec] 
     [exec] added 130 packages, and audited 134 packages in 2s
     [exec] 
     [exec] 23 packages are looking for funding
     [exec]   run `npm fund` for details
     [exec] 
     [exec] found 0 vulnerabilities
     [exec] 
     [exec] &gt; Task :packageRunCheckFormat
     [exec] npm WARN config production Use `--omit=dev` instead.
     [exec] 
     [exec] &gt; @liferay/playwright@1.0.0 checkFormat
     [exec] &gt; tsc
     [exec] 
     [exec] tests/commerce/commerce-product-definitions-web/commerceAdminProductConfigurations.spec.ts(41,4): error TS2554: Expected 1 arguments, but got 2.
     [exec] tests/commerce/commerce-product-definitions-web/commerceAdminProductConfigurations.spec.ts(125,4): error TS2554: Expected 1 arguments, but got 2.
     [exec] 
     [exec] &gt; Task :packageRunCheckFormat FAILED
     [exec] 
     [exec] Gradle build finished at 2025-01-15 16:28:48.946.
     [exec] 
     [exec] FAILURE: Build failed with an exception.
     [exec] 
     [exec] * What went wrong:</pre></details></html>

2025-01-15 16:35 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-7.liferay.com/job/test-portal-source-format/6389/">test-portal-source-format#6389</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-7.liferay.com/userContent/jobs/test-portal-source-format/builds/6389/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-content-management/liferay-portal/pull/6216">liferay-content-management#6216</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/#/project/35392/routines/45357">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/#/project/35392/routines/45357/build/109259053">[master] ci:test:sf - NemethNorbert &gt; liferay-content-management - PR#6216 - 2025-01-15[08:20:52]</a><br/></div><div><strong>Testray Build ID:</strong><span></span>109259053<br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-7.liferay.com/job/publish-testray-report/4275/">publish-testray-report#4275</a><br/></div></div>

2025-01-16 09:00 UTC, NemethNorbert commented
ci:forward

2025-01-16 09:01 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>relevant</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-27.liferay.com/job/test-portal-acceptance-pullrequest(master)/13630/">test-portal-acceptance-pullrequest(master)</a></p><p><b>For more details click <a href="https://test-1-27.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/13630/jenkins-report.html">here</a>.</b></p>

2025-01-16 09:02 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-27.liferay.com/job/test-portal-source-format/7832/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-27.liferay.com/userContent/jobs/test-portal-source-format/builds/7832/jenkins-report.html">here</a>.</b></p>

2025-01-16 09:02 UTC, liferay-continuous-integration commented
<h1>Build completed.</h1><p>Jenkins URL: <a href="https://test-1-27.liferay.com/job/test-portal-acceptance-pullrequest(master)/13630/">test-portal-acceptance-pullrequest(master)</a></p><p>The <code>relevant</code> test suite did not execute tests because all modified files were excluded by the <b>modified.files.global.excludes</b> property in <code>test.properties</code>.</p><p>Please use <code>ci:test:sf</code> and/or <code>ci:forward</code> for this pull request to be forwarded or eligible for forwarding.</p>

2025-01-16 09:04 UTC, boton commented
rebased on top of https://github.com/brianchandotcom/liferay-portal

2025-01-16 09:05 UTC, boton commented
ci:forward

2025-01-16 09:05 UTC, liferay-continuous-integration commented
CI is automatically triggering the following test suites:
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**relevant**
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**sf**
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**stable**

The pull request will automatically be forwarded to the user `brianchandotcom` If the following test suites pass:
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**relevant**
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**sf**
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**stable**

2025-01-16 09:06 UTC, liferay-continuous-integration commented
<html><h3>:heavy_check_mark: ci:test:sf - 1 out of 1 jobs passed in 5 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/89df9067788c65d4ac8974b2fa730f28d482d766">89df9067788c65d4ac8974b2fa730f28d482d766</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/NemethNorbert/liferay-portal/tree/LPD-41946">LPD-41946</a><br/>Branch GIT ID: <a href="https://github.com/NemethNorbert/liferay-portal/commit/bb5cb321252bd348fc56cde029bd6871bb51e583">bb5cb321252bd348fc56cde029bd6871bb51e583</a></p>1 out of 1jobs PASSED<details><summary><strong>1 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-27.liferay.com/job/test-portal-source-format/7832/">test-portal-source-format</a></li></ul></details><h5>For more details click <a href="https://test-1-27.liferay.com/userContent/jobs/test-portal-source-format/builds/7832/jenkins-report.html">here</a>.</h5></details></html>

2025-01-16 09:06 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>relevant</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-30.liferay.com/job/test-portal-acceptance-pullrequest(master)/10766/">test-portal-acceptance-pullrequest(master)</a></p><p><b>For more details click <a href="https://test-1-30.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/10766/jenkins-report.html">here</a>.</b></p>

2025-01-16 09:07 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-37.liferay.com/job/test-portal-source-format/11326/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-37.liferay.com/userContent/jobs/test-portal-source-format/builds/11326/jenkins-report.html">here</a>.</b></p>

2025-01-16 09:07 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-27.liferay.com/job/test-portal-source-format/7832/">test-portal-source-format#7832</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-27.liferay.com/userContent/jobs/test-portal-source-format/builds/7832/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-content-management/liferay-portal/pull/6216">liferay-content-management#6216</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/#/project/35392/routines/45357">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/#/project/35392/routines/45357/build/109834657">[master] ci:test:sf - NemethNorbert &gt; liferay-content-management - PR#6216 - 2025-01-16[01:00:45]</a><br/></div><div><strong>Testray Build ID:</strong><span></span>109834657<br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-27.liferay.com/job/publish-testray-report/29691/">publish-testray-report#29691</a><br/></div></div>

2025-01-16 09:12 UTC, liferay-continuous-integration commented
<html><h3>:x: ci:test:sf - 0 out of 1 jobs passed in 7 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/89df9067788c65d4ac8974b2fa730f28d482d766">89df9067788c65d4ac8974b2fa730f28d482d766</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/NemethNorbert/liferay-portal/tree/LPD-41946">LPD-41946</a><br/>Branch GIT ID: <a href="https://github.com/NemethNorbert/liferay-portal/commit/bb5cb321252bd348fc56cde029bd6871bb51e583">bb5cb321252bd348fc56cde029bd6871bb51e583</a></p>0 out of 1jobs PASSED<div><h4>1 Failed Jobs:</h4><ul><li><a href="https://test-1-37.liferay.com/job/test-portal-source-format/11326/"><strike>test-portal-source-format</strike></a></li></ul></div><h5>For more details click <a href="https://test-1-37.liferay.com/userContent/jobs/test-portal-source-format/builds/11326/jenkins-report.html">here</a>.</h5><pre>format-source-files:
     [java] Loading file:/opt/dev/projects/github/liferay-portal/portal-impl/classes/system.properties
     [java] java.lang.Exception: Found formatting issue in SHA 9361f5a464424befa28614fffab1aa686658e2ee
     [java] The commit message is missing a reference to a required JIRA project: BLADE, CLDSVCS, COMMERCE, FACES, IDE, ISSD, ISSITES, LCD, LHC, LOOP, LPD, LPS, LRAC, LRCI, LRDOCS, LRIS, LRQA, LRSD, OAUTH2, POSHI, RELEASE, SYNC, TR. Please verify that the JIRA project keys are specifiedin source-formatter.properties in the liferay-portal repository.
     [java]   at com.liferay.source.formatter.util.JIRAUtil.validateJIRAProjectNames(JIRAUtil.java:62)
     [java]   at com.liferay.source.formatter.SourceFormatter._validateCommitMessages(SourceFormatter.java:1320)
     [java]   at com.liferay.source.formatter.SourceFormatter.format(SourceFormatter.java:337)
     [java]   at com.liferay.source.formatter.SourceFormatter.main(SourceFormatter.java:301)
[stopwatch] [run.batch.test.action: 4:19.445 sec]
     [echo] The following error occurred while executing this line:
     [echo] /opt/dev/projects/github/liferay-portal/portal-impl/build.xml:449: The following error occurred while executing this line:
     [echo] /opt/dev/projects/github/liferay-portal/portal-impl/build.xml:651: Java returned: 1
   [delete] Deleting: /opt/dev/projects/github/liferay-portal/null2070380680.properties

merge-test-results:
    [mkdir] Created dir: /opt/dev/projects/github/liferay-portal/test-results
[beanshell] Truncating errors in /opt/dev/projects/github/liferay-portal/portal-impl/test-results/TEST-JenkinsLogAssertTest.xml
[junitreport] Processing /opt/dev/projects/github/liferay-portal/test-results/TESTS-TestSuites.xml to /tmp/null1386651884
[junitreport] Loading stylesheet ile:/opt/java/ant/lib/ant-junit.jar!/org/apache/tools/ant/taskdefs/optional/junit/xsl/junit-frames.xsl
[junitreport] Transform time: 223ms
[junitreport] Deleting: /tmp/null1386651884
     [echo] A report with all the test results can be found at test-results/html/index.html.
    [mkdir] Created dir: /opt/dev/projects/github/liferay-jenkins-ee/test-results
     [copy] Copying 1 file to /opt/dev/projects/github/liferay-jenkins-ee/test-results
     [echo] run.batch.test.tear.down.start.timestamp: 01-16-2025 01:12:17:794 PST
[stopwatch] [run.batch.test.tear.down: 0.000 sec]
   [delete] Deleting: /opt/dev/projects/github/liferay-portal/null2070380680.properties

print-gc-logs:
     [echo] </pre></details></html>

2025-01-16 09:15 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-37.liferay.com/job/test-portal-source-format/11326/">test-portal-source-format#11326</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-37.liferay.com/userContent/jobs/test-portal-source-format/builds/11326/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-content-management/liferay-portal/pull/6216">liferay-content-management#6216</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/#/project/35392/routines/45357">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/#/project/35392/routines/45357/build/109835203">[master] ci:test:sf - NemethNorbert &gt; liferay-content-management - PR#6216 - 2025-01-16[01:05:56]</a><br/></div><div><strong>Testray Build ID:</strong><span></span>109835203<br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-37.liferay.com/job/publish-testray-report/42682/">publish-testray-report#42682</a><br/></div></div>

2025-01-16 09:25 UTC, liferay-continuous-integration commented
ci:test:upgrade

Invoking upgrade test suite because an upgrade file has been modified.

2025-01-16 09:26 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>upgrade</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-32.liferay.com/job/test-portal-acceptance-pullrequest(master)/5860/">test-portal-acceptance-pullrequest(master)</a></p><p><b>For more details click <a href="https://test-1-32.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/5860/jenkins-report.html">here</a>.</b></p>

2025-01-16 09:45 UTC, boton commented
ci:test:sf

2025-01-16 09:46 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-31.liferay.com/job/test-portal-source-format/6950/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-31.liferay.com/userContent/jobs/test-portal-source-format/builds/6950/jenkins-report.html">here</a>.</b></p>

2025-01-16 09:53 UTC, liferay-continuous-integration commented
<html><h3>:x: ci:test:sf - 0 out of 1 jobs passed in 8 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/89df9067788c65d4ac8974b2fa730f28d482d766">89df9067788c65d4ac8974b2fa730f28d482d766</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/NemethNorbert/liferay-portal/tree/LPD-41946">LPD-41946</a><br/>Branch GIT ID: <a href="https://github.com/NemethNorbert/liferay-portal/commit/bb5cb321252bd348fc56cde029bd6871bb51e583">bb5cb321252bd348fc56cde029bd6871bb51e583</a></p>0 out of 1jobs PASSED<div><h4>1 Failed Jobs:</h4><ul><li><a href="https://test-1-31.liferay.com/job/test-portal-source-format/6950/"><strike>test-portal-source-format</strike></a></li></ul></div><h5>For more details click <a href="https://test-1-31.liferay.com/userContent/jobs/test-portal-source-format/builds/6950/jenkins-report.html">here</a>.</h5><pre>format-source-files:
     [java] Loading file:/opt/dev/projects/github/liferay-portal/portal-impl/classes/system.properties
     [java] java.lang.Exception: Found formatting issue in SHA 9361f5a464424befa28614fffab1aa686658e2ee
     [java] The commit message is missing a reference to a required JIRA project: BLADE, CLDSVCS, COMMERCE, FACES, IDE, ISSD, ISSITES, LCD, LHC, LOOP, LPD, LPS, LRAC, LRCI, LRDOCS, LRIS, LRQA, LRSD, OAUTH2, POSHI, RELEASE, SYNC, TR. Please verify that the JIRA project keys are specifiedin source-formatter.properties in the liferay-portal repository.
     [java]   at com.liferay.source.formatter.util.JIRAUtil.validateJIRAProjectNames(JIRAUtil.java:62)
     [java]   at com.liferay.source.formatter.SourceFormatter._validateCommitMessages(SourceFormatter.java:1320)
     [java]   at com.liferay.source.formatter.SourceFormatter.format(SourceFormatter.java:337)
     [java]   at com.liferay.source.formatter.SourceFormatter.main(SourceFormatter.java:301)
[stopwatch] [run.batch.test.action: 5:33.749 sec]
     [echo] The following error occurred while executing this line:
     [echo] /opt/dev/projects/github/liferay-portal/portal-impl/build.xml:449: The following error occurred while executing this line:
     [echo] /opt/dev/projects/github/liferay-portal/portal-impl/build.xml:651: Java returned: 1
   [delete] Deleting: /opt/dev/projects/github/liferay-portal/null933329460.properties

merge-test-results:
    [mkdir] Created dir: /opt/dev/projects/github/liferay-portal/test-results
[beanshell] Truncating errors in /opt/dev/projects/github/liferay-portal/portal-impl/test-results/TEST-JenkinsLogAssertTest.xml
[junitreport] Processing /opt/dev/projects/github/liferay-portal/test-results/TESTS-TestSuites.xml to /tmp/null1952871666
[junitreport] Loading stylesheet ile:/opt/java/ant/lib/ant-junit.jar!/org/apache/tools/ant/taskdefs/optional/junit/xsl/junit-frames.xsl
[junitreport] Transform time: 200ms
[junitreport] Deleting: /tmp/null1952871666
     [echo] A report with all the test results can be found at test-results/html/index.html.
    [mkdir] Created dir: /opt/dev/projects/github/liferay-jenkins-ee/test-results
     [copy] Copying 1 file to /opt/dev/projects/github/liferay-jenkins-ee/test-results
     [echo] run.batch.test.tear.down.start.timestamp: 01-16-2025 01:53:09:005 PST
[stopwatch] [run.batch.test.tear.down: 0.000 sec]
   [delete] Deleting: /opt/dev/projects/github/liferay-portal/null933329460.properties

print-gc-logs:
     [echo] </pre></details></html>

2025-01-16 09:57 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-31.liferay.com/job/test-portal-source-format/6950/">test-portal-source-format#6950</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-31.liferay.com/userContent/jobs/test-portal-source-format/builds/6950/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-content-management/liferay-portal/pull/6216">liferay-content-management#6216</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/#/project/35392/routines/45357">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/#/project/35392/routines/45357/build/109857931">[master] ci:test:sf - NemethNorbert &gt; liferay-content-management - PR#6216 - 2025-01-16[01:45:34]</a><br/></div><div><strong>Testray Build ID:</strong><span></span>109857931<br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-31.liferay.com/job/publish-testray-report/27257/">publish-testray-report#27257</a><br/></div></div>

2025-01-16 11:06 UTC, liferay-continuous-integration commented
<html><h3>:x: ci:test:upgrade - 379 out of 391 jobs passed in 1 hour 41 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/89df9067788c65d4ac8974b2fa730f28d482d766">89df9067788c65d4ac8974b2fa730f28d482d766</a></p><h4>Upstream Comparison:</h4><p>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/89df9067788c65d4ac8974b2fa730f28d482d766">89df9067788c65d4ac8974b2fa730f28d482d766</a><br/>Jenkins Build URL: <a href="https://testray.liferay.com/#/project/35392/routines/590307/build/109118094">EE Development Acceptance (master) - 1121 - 2025-01-15[00:36:25]</a></p><details><summary><strong>ci:test:upgrade - 379 out of 391 jobs PASSED</strong></summary><div><h4>12 Failed Jobs:</h4><ul><li><a href="https://test-1-32.liferay.com/job/test-portal-acceptance-pullrequest(master)/5860/"><strike>test-portal-acceptance-pullrequest(master)</strike></a></li><li>functional-tomcat90-db2111<ul><li><a href="https://test-1-33.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/988422/">functional-tomcat90-db2111/0/0</a></li><li><a href="https://test-1-29.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1050316/">functional-tomcat90-db2111/1/0</a></li><li><a href="https://test-1-39.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1062474/">functional-tomcat90-db2111/1/1</a></li><li><a href="https://test-1-37.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1294450/">functional-tomcat90-db2111/1/2</a></li><li><a href="https://test-1-1.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/390558/">functional-tomcat90-db2111/1/3</a></li></ul></li><li>functional-tomcat90-mariadb102<ul><li><a href="https://test-1-33.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/988423/">functional-tomcat90-mariadb102/0/0</a></li><li><a href="https://test-1-8.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/506430/">functional-tomcat90-mariadb102/1/0</a></li><li><a href="https://test-1-5.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/394657/">functional-tomcat90-mariadb102/1/1</a></li><li><a href="https://test-1-6.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/460594/">functional-tomcat90-mariadb102/1/2</a></li><li><a href="https://test-1-7.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/403009/">functional-tomcat90-mariadb102/1/3</a></li></ul></li><li>functional-tomcat90-mysql57<ul><li><a href="https://test-1-32.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1168884/">functional-tomcat90-mysql57/0/0</a></li><li><a href="https://test-1-32.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1168885/">functional-tomcat90-mysql57/0/1</a></li><li><a href="https://test-1-38.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1007262/">functional-tomcat90-mysql57/0/2</a></li><li><a href="https://test-1-1.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/390540/">functional-tomcat90-mysql57/1/0</a></li><li><a href="https://test-1-10.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/454849/"><strike>functional-tomcat90-mysql57/1/1</strike></a></li><li><a href="https://test-1-6.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/460582/">functional-tomcat90-mysql57/1/2</a></li><li><a href="https://test-1-5.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/394647/">functional-tomcat90-mysql57/1/3</a></li><li><a href="https://test-1-8.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/506416/">functional-tomcat90-mysql57/1/4</a></li><li><a href="https://test-1-6.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/460581/">functional-tomcat90-mysql57/1/5</a></li><li><a href="https://test-1-5.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/394645/">functional-tomcat90-mysql57/1/6</a></li><li><a href="https://test-1-6.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/460580/">functional-tomcat90-mysql57/1/7</a></li><li><a href="https://test-1-5.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/394646/">functional-tomcat90-mysql57/1/8</a></li><li><a href="https://test-1-8.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/506417/">functional-tomcat90-mysql57/1/9</a></li><li><a href="https://test-1-2.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/451014/">functional-tomcat90-mysql57/1/10</a></li><li><a href="https://test-1-9.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/476992/">functional-tomcat90-mysql57/1/11</a></li><li><a href="https://test-1-3.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/502581/">functional-tomcat90-mysql57/1/12</a></li><li><a href="https://test-1-1.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/390545/">functional-tomcat90-mysql57/1/13</a></li></ul></li><li>functional-tomcat90-mysql80<ul><li><a href="https://test-1-27.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1160136/">functional-tomcat90-mysql80/0/0</a></li><li><a href="https://test-1-30.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1119845/">functional-tomcat90-mysql80/0/1</a></li><li><a href="https://test-1-34.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1065075/">functional-tomcat90-mysql80/0/2</a></li><li><a href="https://test-1-26.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1260963/">functional-tomcat90-mysql80/1/0</a></li><li><a href="https://test-1-25.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/743514/">functional-tomcat90-mysql80/1/1</a></li><li><a href="https://test-1-2.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/451012/">functional-tomcat90-mysql80/1/2</a></li><li><a href="https://test-1-7.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/402999/">functional-tomcat90-mysql80/1/3</a></li><li><a href="https://test-1-3.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/502580/">functional-tomcat90-mysql80/1/4</a></li><li><a href="https://test-1-9.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/476991/">functional-tomcat90-mysql80/1/5</a></li><li><a href="https://test-1-1.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/390544/">functional-tomcat90-mysql80/1/6</a></li><li><a href="https://test-1-34.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1065074/">functional-tomcat90-mysql80/1/7</a></li><li><a href="https://test-1-37.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1294444/">functional-tomcat90-mysql80/1/8</a></li><li><a href="https://test-1-6.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/460585/">functional-tomcat90-mysql80/1/9</a></li><li><a href="https://test-1-8.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/506437/">functional-tomcat90-mysql80/1/10</a></li><li><a href="https://test-1-37.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1294447/">functional-tomcat90-mysql80/1/11</a></li><li><a href="https://test-1-32.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1168894/">functional-tomcat90-mysql80/1/12</a></li></ul></li><li>functional-tomcat90-oracle193<ul><li><a href="https://test-1-25.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/743517/">functional-tomcat90-oracle193/0/0</a></li><li><a href="https://test-1-39.liferay.com/job/test-portal-acceptance-pullreq [...]

2025-01-16 11:11 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-32.liferay.com/job/test-portal-acceptance-pullrequest(master)/5860/">test-portal-acceptance-pullrequest(master)#5860</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-32.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/5860/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>upgrade<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-content-management/liferay-portal/pull/6216">liferay-content-management#6216</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/#/project/35392/routines/45357">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/#/project/35392/routines/45357/build/109905598">[master] ci:test:upgrade - NemethNorbert &gt; liferay-content-management - PR#6216 - 2025-01-16[01:25:53]</a><br/></div><div><strong>Testray Build ID:</strong><span></span>109905598<br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-32.liferay.com/job/publish-testray-report/35772/">publish-testray-report#35772</a><br/></div></div>

2025-01-16 12:10 UTC, liferay-continuous-integration commented
<html><h3>:x: ci:test:stable - 26 out of 27 jobs passed</h3><h3>:x: ci:test:relevant - 155 out of 224 jobs passed in 2 hours 40 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/89df9067788c65d4ac8974b2fa730f28d482d766">89df9067788c65d4ac8974b2fa730f28d482d766</a></p><h4>Upstream Comparison:</h4><p>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/89df9067788c65d4ac8974b2fa730f28d482d766">89df9067788c65d4ac8974b2fa730f28d482d766</a><br/>Jenkins Build URL: <a href="https://testray.liferay.com/#/project/35392/routines/590307/build/109118094">EE Development Acceptance (master) - 1121 - 2025-01-15[00:36:25]</a></p><details><summary><strong>ci:test:stable - 26 out of 27 jobs PASSED</strong></summary><div><h4>1 Failed Jobs:</h4><ul><li>central-requirements<ul><li><a href="https://test-1-10.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/454818/">central-requirements/0/0</a></li></ul></li><li>functional-smoke-tomcat90-mysql57_stable<ul><li><a href="https://test-1-25.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/743499/">functional-smoke-tomcat90-mysql57_stable/0/0</a></li></ul></li><li>functional-upgrade-tomcat90-mysql57_stable<ul><li><a href="https://test-1-10.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/454843/">functional-upgrade-tomcat90-mysql57_stable/0/0</a></li><li><a href="https://test-1-9.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/476975/">functional-upgrade-tomcat90-mysql57_stable/0/1</a></li><li><a href="https://test-1-7.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/402990/">functional-upgrade-tomcat90-mysql57_stable/0/2</a></li></ul></li><li>js-unit<ul><li><a href="https://test-1-10.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/454819/">js-unit/0/0</a></li><li><a href="https://test-1-2.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/450974/"><strike>js-unit/1/0</strike></a></li></ul></li><li>modules-compile<ul><li><a href="https://test-1-5.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/394641/">modules-compile/0/0</a></li><li><a href="https://test-1-37.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1294427/">modules-compile/0/1</a></li><li><a href="https://test-1-10.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/454846/">modules-compile/0/2</a></li><li><a href="https://test-1-38.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1007253/">modules-compile/0/3</a></li><li><a href="https://test-1-3.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/502570/">modules-compile/0/4</a></li><li><a href="https://test-1-29.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1050294/">modules-compile/0/5</a></li><li><a href="https://test-1-6.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/460575/">modules-compile/0/6</a></li><li><a href="https://test-1-5.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/394640/">modules-compile/0/7</a></li><li><a href="https://test-1-33.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/988408/">modules-compile/0/8</a></li><li><a href="https://test-1-36.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1091247/">modules-compile/0/9</a></li><li><a href="https://test-1-10.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/454841/">modules-compile/0/10</a></li><li><a href="https://test-1-2.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/450998/">modules-compile/0/11</a></li><li><a href="https://test-1-8.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/506409/">modules-compile/0/12</a></li></ul></li><li>modules-integration-mysql57_stable<ul><li><a href="https://test-1-32.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1168874/">modules-integration-mysql57_stable/0/0</a></li></ul></li><li>modules-unit_stable<ul><li><a href="https://test-1-33.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/988407/">modules-unit_stable/0/0</a></li></ul></li><li>playwright-js-tomcat90-mysql57_stable<ul><li><a href="https://test-1-31.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1167175/">playwright-js-tomcat90-mysql57_stable/0/0</a></li></ul></li><li>rest-builder<ul><li><a href="https://test-1-36.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1091200/">rest-builder/0/0</a></li></ul></li><li>service-builder<ul><li><a href="https://test-1-5.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/394614/">service-builder/0/0</a></li></ul></li><li>unit_stable<ul><li><a href="https://test-1-2.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/451002/">unit_stable/0/0</a></li></ul></li><li>workspaces-compile<ul><li><a href="https://test-1-3.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/502544/">workspaces-compile/0/0</a></li></ul></li></ul></div><details><summary><strong>26 Successful Jobs:</strong></summary><ul/></details></details><details><summary><strong>ci:test:relevant - 155 out of 224 jobs PASSED</strong></summary><div><h4>69 Failed Jobs:</h4><ul><li><a href="https://test-1-30.liferay.com/job/test-portal-acceptance-pullrequest(master)/10766/"><strike>test-portal-acceptance-pullrequest(master)</strike></a></li><li>central-requirements<ul><li><a href="https://test-1-10.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/454818/">central-requirements/0/0</a></li></ul></li><li>functional-smoke-tomcat90-mysql57_stable<ul><li><a href="https://test-1-25.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/743499/">functional-smoke-tomcat90-mysql57_stable/0/0</a></li></ul></li><li>functional-upgrade-tomcat90-mysql57_stable<ul><li><a href="https://test-1-10.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/454843/">functional-upgrade-tomcat90-mysql57_stable/0/0</a></li><li><a href="https://test-1-9.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/476975/">functional-upgrade-tomcat90-mysql57_stable/0/1</a></li><li><a href="https://test-1-7.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/402990/">functional-upgrade-tomcat90-mysql57_stable/0/2</a></li></ul></li><li>js-unit<ul><li><a href="https://test-1-10.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/454819/">js-unit/0/0</a></li><li><a href="https://test-1-2.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/450974/"><strike>js-unit/1/0</strike></a></li></ul></li><li>modules-compile<ul><li><a href="https://test-1-5.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/394641/">modules-compile/0/0</a></li><li><a href="https://test-1-37.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1294427/">modules-compile/0/1</a></li><li><a href="https://test-1-10.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/454846/">modules-compile/0/2</a></li><li><a href="https://test-1-38.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1007253/">modules-compile/0/3</a></li><li><a href="https://test-1-3.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/502570/">modules-compile/0/4</a></li><li><a href="https://test-1-29.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1050294/">modules-compile/0/5</a></li><li><a href="https://test-1-6.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/460575/">modules-compile/0/6</a></li><li><a href="https://test-1-5.liferay [...]

2025-01-16 12:22 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-30.liferay.com/job/test-portal-acceptance-pullrequest(master)/10766/">test-portal-acceptance-pullrequest(master)#10766</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-30.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/10766/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>relevant<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-content-management/liferay-portal/pull/6216">liferay-content-management#6216</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/#/project/35392/routines/45357">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/#/project/35392/routines/45357/build/109930928">[master] ci:test:relevant - NemethNorbert &gt; liferay-content-management - PR#6216 - 2025-01-16[01:05:55]</a><br/></div><div><strong>Testray Build ID:</strong><span></span>109930928<br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-30.liferay.com/job/publish-testray-report/25506/">publish-testray-report#25506</a><br/></div></div>

2025-01-16 16:00 UTC, liferay-continuous-integration commented
<html><h3>:x: ci:test:sf - 0 out of 1 jobs passed in 5 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/89df9067788c65d4ac8974b2fa730f28d482d766">89df9067788c65d4ac8974b2fa730f28d482d766</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/NemethNorbert/liferay-portal/tree/LPD-41946">LPD-41946</a><br/>Branch GIT ID: <a href="https://github.com/NemethNorbert/liferay-portal/commit/4b4295934f8de4cc861e5661dc6ad28a2f682c4b">4b4295934f8de4cc861e5661dc6ad28a2f682c4b</a></p>0 out of 1jobs PASSED<div><h4>1 Failed Jobs:</h4><ul><li><a href="https://test-1-39.liferay.com/job/test-portal-source-format/7294/"><strike>test-portal-source-format</strike></a></li></ul></div><h5>For more details click <a href="https://test-1-39.liferay.com/userContent/jobs/test-portal-source-format/builds/7294/jenkins-report.html">here</a>.</h5><pre>     [exec] &gt; Task :packageRunCheckFormat
     [exec] yarn run v1.13.0
     [exec] \$ node-scripts check:ci
     [exec] 
     [exec] ⚙️ Running preflight checks...
     [exec] 
     [exec] ⚙️ Checking outdated tsconfig.json files ...
     [exec] 
     [exec] ⚙️ Running TypeScript checks on modified files...
     [exec] ℹ️ A total of 12 CPUs were detected: launching tsc using 12 workers
     [exec] 
     [exec] ⚙️ Running format checks on modified files...
     [exec] Done in 6.24s.
     [exec] 
     [exec] &gt; Task :portalYarnCheckFormat
     [exec] Gradle build finished at 2025-01-16 15:59:43.400.
     [exec] 
     [exec] 
     [exec] BUILD SUCCESSFUL in 19s
     [exec] 3 actionable tasks: 3 executed
     [exec] 
     [exec] See the profiling report at: file:///opt/dev/projects/github/liferay-portal/build/reports/profile/profile-2025-01-16-07-59-26.html
     [exec] A fine-grained performance profile is available: use the --scan option.
[beanshell] Executing Gradle task: packageRunCheckFormat
     [exec] To honour the JVM settings for this build a single-use Daemon process will be forked. For more on this, please refer to https://docs.gradle.org/8.5/userguide/gradle_daemon.html#sec:disabling_the_daemon in the Gradle documentation.
     [exec] Daemon will be stopped at the end of the build 
     [exec] &gt; Task :downloadNode
     [exec] 
     [exec] &gt; Task :npmInstall
     [exec] npm WARN config production Use `--omit=dev` instead.
     [exec] 
     [exec] added 130 packages, and audited 134 packages in 1s
     [exec] 
     [exec] 23 packages are looking for funding
     [exec]   run `npm fund` for details
     [exec] 
     [exec] found 0 vulnerabilities
     [exec] 
     [exec] &gt; Task :packageRunCheckFormat
     [exec] npm WARN config production Use `--omit=dev` instead.
     [exec] 
     [exec] &gt; @liferay/playwright@1.0.0 checkFormat
     [exec] &gt; tsc
     [exec] 
     [exec] tests/commerce/commerce-product-definitions-web/commerceAdminProductConfigurations.spec.ts(41,4): error TS2554: Expected 1 arguments, but got 2.
     [exec] tests/commerce/commerce-product-definitions-web/commerceAdminProductConfigurations.spec.ts(125,4): error TS2554: Expected 1 arguments, but got 2.
     [exec] 
     [exec] &gt; Task :packageRunCheckFormat FAILED
     [exec] Gradle build finished at 2025-01-16 16:00:10.302.
     [exec] 
     [exec] 
     [exec] FAILURE: Build failed with an exception.
     [exec] 
     [exec] * What went wrong:</pre></details></html>

2025-01-16 16:02 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-39.liferay.com/job/test-portal-source-format/7294/">test-portal-source-format#7294</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-39.liferay.com/userContent/jobs/test-portal-source-format/builds/7294/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-content-management/liferay-portal/pull/6216">liferay-content-management#6216</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/#/project/35392/routines/45357">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/#/project/35392/routines/45357/build/110092929">[master] ci:test:sf - NemethNorbert &gt; liferay-content-management - PR#6216 - 2025-01-16[07:55:43]</a><br/></div><div><strong>Testray Build ID:</strong><span></span>110092929<br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-39.liferay.com/job/publish-testray-report/26537/">publish-testray-report#26537</a><br/></div></div>

2025-01-17 09:01 UTC, boton commented
ci:forward

2025-01-17 09:01 UTC, liferay-continuous-integration commented
CI is automatically triggering the following test suites:
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**relevant**
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**sf**
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**stable**

The pull request will automatically be forwarded to the user `brianchandotcom` If the following test suites pass:
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**relevant**
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**sf**
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**stable**

2025-01-17 09:02 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>relevant</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-40.liferay.com/job/test-portal-acceptance-pullrequest(master)/12695/">test-portal-acceptance-pullrequest(master)</a></p><p><b>For more details click <a href="https://test-1-40.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/12695/jenkins-report.html">here</a>.</b></p>

2025-01-17 09:03 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-40.liferay.com/job/test-portal-source-format/7261/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-40.liferay.com/userContent/jobs/test-portal-source-format/builds/7261/jenkins-report.html">here</a>.</b></p>

2025-01-17 09:03 UTC, liferay-continuous-integration commented
<h1>Build completed.</h1><p>Jenkins URL: <a href="https://test-1-40.liferay.com/job/test-portal-acceptance-pullrequest(master)/12695/">test-portal-acceptance-pullrequest(master)</a></p><p>The <code>relevant</code> test suite did not execute tests because all modified files were excluded by the <b>modified.files.global.excludes</b> property in <code>test.properties</code>.</p><p>Please use <code>ci:test:sf</code> and/or <code>ci:forward</code> for this pull request to be forwarded or eligible for forwarding.</p>

2025-01-17 09:06 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-40.liferay.com/job/test-portal-acceptance-pullrequest(master)/12695/">test-portal-acceptance-pullrequest(master)#12695</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-40.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/12695/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>relevant<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-content-management/liferay-portal/pull/6216">liferay-content-management#6216</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/#/project/35392/routines/45357">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/#/project/35392/routines/45357/build/111019275">[master] ci:test:relevant - NemethNorbert &gt; liferay-content-management - PR#6216 - 2025-01-17[01:01:37]</a><br/></div><div><strong>Testray Build ID:</strong><span></span>111019275<br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-40.liferay.com/job/publish-testray-report/27635/">publish-testray-report#27635</a><br/></div></div>

2025-01-17 09:07 UTC, liferay-continuous-integration commented
<html><h3>:heavy_check_mark: ci:test:sf - 1 out of 1 jobs passed in 6 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/d1f1ba2114b232828a89aa605c18ef368ad23905">d1f1ba2114b232828a89aa605c18ef368ad23905</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/NemethNorbert/liferay-portal/tree/LPD-41946">LPD-41946</a><br/>Branch GIT ID: <a href="https://github.com/NemethNorbert/liferay-portal/commit/4b4295934f8de4cc861e5661dc6ad28a2f682c4b">4b4295934f8de4cc861e5661dc6ad28a2f682c4b</a></p>1 out of 1jobs PASSED<details><summary><strong>1 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-40.liferay.com/job/test-portal-source-format/7261/">test-portal-source-format</a></li></ul></details><h5>For more details click <a href="https://test-1-40.liferay.com/userContent/jobs/test-portal-source-format/builds/7261/jenkins-report.html">here</a>.</h5></details></html>

2025-01-17 09:07 UTC, liferay-continuous-integration commented
All required test suite(s) passed.
Forwarding pull request to `brianchandotcom`.
[Console](https://test-1-40.liferay.com/job/test-portal-source-format/7261//consoleFull)

2025-01-17 09:07 UTC, closed without merging

2025-01-17 09:07 UTC, liferay-continuous-integration commented
Pull request has been successfully forwarded to  https://github.com/brianchandotcom/liferay-portal/pull/157833
[Console](https://test-1-40.liferay.com/job/test-portal-source-format/7261//consoleFull)

2025-01-17 09:08 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-40.liferay.com/job/test-portal-source-format/7261/">test-portal-source-format#7261</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-40.liferay.com/userContent/jobs/test-portal-source-format/builds/7261/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-content-management/liferay-portal/pull/6216">liferay-content-management#6216</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/#/project/35392/routines/45357">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/#/project/35392/routines/45357/build/111019646">[master] ci:test:sf - NemethNorbert &gt; liferay-content-management - PR#6216 - 2025-01-17[01:01:37]</a><br/></div><div><strong>Testray Build ID:</strong><span></span>111019646<br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-40.liferay.com/job/publish-testray-report/27636/">publish-testray-report#27636</a><br/></div></div>